#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Misc/OrderConfirmationBasketItems.cshtml")]
    public partial class _Views_Misc_OrderConfirmationBasketItems_cshtml : System.Web.Mvc.WebViewPage<CheckoutDetails>
    {
        public _Views_Misc_OrderConfirmationBasketItems_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
  
    var lbc = new List<BasketContents>();
    var bt = new BasketTotals();

    if (Session["B_BasketArray"] != null)
    {
        lbc = (List<BasketContents>)Session["B_BasketArray"];
    }
    if (Session["B_BasketTotals"] != null)
    {
        bt = (BasketTotals)Session["B_BasketTotals"];
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" class=\"AXISTableText\"");

WriteLiteral(">\r\n    <tr>\r\n        <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
"");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; back" +
"ground-color: #F5F5F5; text-align: left;\"");

WriteLiteral("><strong>Stock Code</strong></th>\r\n                        <th");

WriteLiteral(" width=\"45%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; back" +
"ground-color: #F5F5F5; text-align: left;\"");

WriteLiteral("><strong>Description</strong></th>\r\n                        <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; back" +
"ground-color: #F5F5F5; text-align: right;\"");

WriteLiteral("><strong>Quantity</strong></th>\r\n                        <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; back" +
"ground-color: #F5F5F5; text-align: right;\"");

WriteLiteral("><strong>Price Each</strong></th>\r\n                        <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; back" +
"ground-color: #F5F5F5; text-align: right;\"");

WriteLiteral("><strong>Line Total</strong></th>\r\n                    </tr>\r\n                </t" +
"head>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n<table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" class=\"AXISTableText\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
     foreach (var item in lbc)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n");

            
            #line 40 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
            
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
             if (item.ItemType == BasketItemType.Item || item.ItemType == BasketItemType.AdminDiscount || item.ItemType == BasketItemType.CompatibleDiscount)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                        <tr>\r\n                            <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: l" +
"eft;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 46 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                           Write(item.PartNo);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td");

WriteLiteral(" width=\"45%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: l" +
"eft;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 49 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                           Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td");

WriteLiteral(" width=\"10%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 52 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                           Write(item.Quantity);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight;\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                £");

            
            #line 56 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                            Write(Math.Round(Math.Round(item.PriceInc, 2) / Convert.ToDecimal(ConfigurationManager.AppSettings["VatMultiplier"]), 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight;\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                £");

            
            #line 60 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                            Write(Math.Round(Math.Round(item.PriceInc, 2) * item.Quantity / Convert.ToDecimal(ConfigurationManager.AppSettings["VatMultiplier"]), 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n");

            
            #line 65 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n");

            
            #line 67 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 69 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
      
        var voucher = lbc.FirstOrDefault(x => x.ItemType == BasketItemType.Voucher);
        var delivery = lbc.FirstOrDefault(x => x.ItemType == BasketItemType.Delivery);
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 74 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
     if (voucher != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                    <tr>\r\n                        <td");

WriteLiteral(" width=\"85%\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; border-top: 1px solid #A4B2C0;\"");

WriteLiteral("><strong>Voucher</strong></td>\r\n                        <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; vertical-align: middle; border-top: 1px solid #A4B2C0;\"");

WriteLiteral("><strong>£");

            
            #line 81 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                                                                          Write(Math.Round(voucher.PriceEx, 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                    </tr>\r\n                </table>\r\n            " +
"</td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                    <tr>\r\n                        <td");

WriteLiteral(" width=\"85%\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight;\"");

WriteLiteral("><strong>");

            
            #line 90 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                              Write(delivery.Description);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                        <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; vertical-align: middle;\"");

WriteLiteral("><strong>£");

            
            #line 91 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                                           Write(Math.Round(delivery.PriceEx, 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                    </tr>\r\n                </table>\r\n            " +
"</td>\r\n        </tr>\r\n");

            
            #line 96 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                    <tr>\r\n                        <td");

WriteLiteral(" width=\"85%\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight;\"");

WriteLiteral("><strong>");

            
            #line 103 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                              Write(delivery.Description);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                        <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; vertical-align: middle;\"");

WriteLiteral("><strong>£");

            
            #line 104 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                                           Write(Math.Round(delivery.PriceEx, 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                    </tr>\r\n                </table>\r\n            " +
"</td>\r\n        </tr>\r\n");

            
            #line 109 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <tr>\r\n        <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"85%\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; border-top: 1px solid #A4B2C0;\"");

WriteLiteral("><strong>Subtotal</strong></td>\r\n                    <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; vertical-align: middle; border-top: 1px solid #A4B2C0;\"");

WriteLiteral("><strong>£");

            
            #line 116 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                                                                      Write(Math.Round(bt.GrandTotalExcVat, 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    <" +
"/tr>\r\n    <tr>\r\n        <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"85%\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight;\"");

WriteLiteral("><strong>VAT</strong></td>\r\n                    <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 12px; text-align: r" +
"ight; vertical-align: middle;\"");

WriteLiteral("><strong>£");

            
            #line 126 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                                       Write(Math.Round(bt.Vat, 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    <" +
"/tr>\r\n    <tr>\r\n        <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"font-family: arial, verdana, helvetica, sans-serif; font-size: 12px; bord" +
"er-collapse: collapse;\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"85%\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 14px; text-align: r" +
"ight; border-top: 1px solid #A4B2C0;\"");

WriteLiteral("><strong>Order total</strong></td>\r\n                    <td");

WriteLiteral(" width=\"15%\"");

WriteLiteral(" class=\"order-total\"");

WriteLiteral(" style=\"font-family: arial, helvetica, sans-serif; font-size: 14px; text-align: r" +
"ight; vertical-align: middle; border-top: 1px solid #A4B2C0;\"");

WriteLiteral("><strong>£");

            
            #line 136 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
                                                                                                                                                                                                          Write(Math.Round(bt.GrandTotalIncVat, 2).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    <" +
"/tr>\r\n</table>\r\n\r\n");

            
            #line 143 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
 if (Model.PaymentMethod == "Phone" || Model.PaymentMethod == "BACS")
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" style=\"font-family:arial, verdana, helvetica, sans-serif;font-size:12px;text-ali" +
"gn:left;\"");

WriteLiteral(">\r\n        <font");

WriteLiteral(" face=\"Arial, sans-serif\"");

WriteLiteral(">**Please note this order will not be dispatched until payment has been made.**</" +
"font>\r\n        <o:p></o:p>\r\n    </p>\r\n");

            
            #line 149 "..\..\Views\Misc\OrderConfirmationBasketItems.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
