//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class configurationSetting
    {
        public int configurationSettingID { get; set; }
        public string sectionName { get; set; }
        public string settingName { get; set; }
        public Nullable<int> websiteFK { get; set; }
        public string settingValue { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateLastUpdate { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
