//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.NetgiantMasterData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOrder
    {
        public BackOrder()
        {
            this.BackOrderItem = new HashSet<BackOrderItem>();
        }
    
        public int BackOrderId { get; set; }
        public int ProviderFK { get; set; }
        public string OrderReferenceNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string SupplierOrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int StatusFK { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmailAddress { get; set; }
        public int WebsiteFK { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual ICollection<BackOrderItem> BackOrderItem { get; set; }
        public virtual Website Website { get; set; }
        public virtual provider provider { get; set; }
    }
}
