//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.NetgiantMasterData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_productOverrideOLD
    {
        public int productOverrideID { get; set; }
        public string manufacturer { get; set; }
        public int dataSupplierID { get; set; }
        public string dsValue { get; set; }
        public string ngValue { get; set; }
        public int overrideTypeID { get; set; }
    }
}
