//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.NetgiantMasterData
{
    using System;
    using System.Collections.Generic;
    
    public partial class or_replacements
    {
        public int ReplacementId { get; set; }
        public int Type { get; set; }
        public string Original { get; set; }
        public string Replacement { get; set; }
        public int SearchableId { get; set; }
        public bool Deleted { get; set; }
    }
}
