//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.NetgiantMasterData
{
    using System;
    using System.Collections.Generic;
    
    public partial class productItemType
    {
        public productItemType()
        {
            this.product = new HashSet<product>();
        }
    
        public byte productItemTypeID { get; set; }
        public string productItemTypeName { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
