//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.NetgiantMasterData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInfoCard
    {
        public int WebsiteInfoCardId { get; set; }
        public int WebsiteId { get; set; }
        public string Category { get; set; }
        public string IconClass { get; set; }
        public string Title { get; set; }
        public string BodyText { get; set; }
        public string FindOutMoreContent { get; set; }
        public string ImageUrl { get; set; }
        public string LinkUrl { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
