#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Checkout\BasketDetails.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Checkout\BasketDetails.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Checkout\BasketDetails.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Checkout\BasketDetails.cshtml"
    using DataAccess.EntityFramework;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Checkout\BasketDetails.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Checkout\BasketDetails.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Checkout\BasketDetails.cshtml"
    using VmVoucherType = VMerchantWrapper.Entities.VoucherType;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/BasketDetails.cshtml")]
    public partial class _Views_Checkout_BasketDetails_cshtml : System.Web.Mvc.WebViewPage<CheckoutViewModel>
    {
        public _Views_Checkout_BasketDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Checkout\BasketDetails.cshtml"
 if (Model.BasketTotals.TotalExcVat - Model.BasketTotals.Delivery > 0)
{
    bool isAdminDiscount = Model.BasketContents.Exists(x => x.ItemType == BasketItemType.AdminDiscount);
    bool isCompatibleDiscount = Model.BasketContents.Exists(x => x.ItemType == BasketItemType.CompatibleDiscount);


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <hr");

WriteLiteral(" class=\"g-m-b-10 hidden-xs hidden-sm\"");

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"row g-fw-b\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-6 col-md-5\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-lg-10 col-md-12 pull-left\"");

WriteLiteral(">\r\n                                Items <span");

WriteLiteral(" class=\"g-fc-s\"");

WriteLiteral(">(<span");

WriteLiteral(" class=\"basketQuantity\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                    Write(Model.BasketTotals.Quantity.ToString("##0"));

            
            #line default
            #line hidden
WriteLiteral("</span>)</span>\r\n                            </div>\r\n                            " +
"<div");

WriteLiteral(" class=\"col-lg-2 g-m-l-a g-p-r-10 hidden-md hidden-sm hidden-xs pull-right\"");

WriteLiteral(">Price</div>\r\n                        </div>\r\n                    </div>\r\n       " +
"         </div>\r\n                <div");

WriteLiteral(" class=\"col-md-7 col-lg-6 hidden-xs hidden-sm\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-3 g-p-lr-0\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"g-m-l-10 text-center pull-left\"");

WriteLiteral(">\r\n                                    Quantity\r\n                                " +
"</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6 g-p-lr-0\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                    Potential Saving\r\n                        " +
"        </div>\r\n                            </div>\r\n                            " +
"<div");

WriteLiteral(" class=\"col-md-3 g-p-lr-0\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"g-m-l-a g-p-r-20 hidden-xs hidden-sm pull-right\"");

WriteLiteral(">\r\n                                    Sub-Total\r\n                               " +
" </div>\r\n                            </div>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n            </div>\r\n\r\n         " +
"   <div");

WriteLiteral(" id=\"basketSummary\"");

WriteLiteral(" class=\"basketSummaryContainer\"");

WriteLiteral(">\r\n");

            
            #line 54 "..\..\Views\Checkout\BasketDetails.cshtml"
                
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Checkout\BasketDetails.cshtml"
                  
                    bool isMultiBuy = false;
                    decimal multibuyAmount = decimal.Zero;
                    foreach (BasketContents bc in Model.BasketContents)
                    {
                        if (bc.ItemType == BasketItemType.Item || bc.ItemType == BasketItemType.AdminDiscount)
                        {
                            string neg = bc.ItemType == BasketItemType.AdminDiscount ? "-" : "";
                            string strike = "";
                            string discClass = "g-d-n";
                            decimal discUnitPrice = decimal.Zero;
                            List<int> noStock = new List<int> { 2, 3, 4, 8, 11 }; // Availability codes which indicate 0 stock
                            if (noStock.Contains(bc.Availability))
                            {
                                Model.CheckoutDetails.ZeroStock = true;
                            }
                            if (bc.Availability == 10)
                            {
                                Model.CheckoutDetails.IsSpecialOrder = true;
                            }
                            decimal subt = bc.PriceEx * bc.Quantity;
                            decimal discountRate = Utilities.GetUpsellRate();
                            //decimal potentialDiscountRate = decimal.Zero;
                            if (bc.IsCompatible && Session["V_Voucher"] == null &&
                                Convert.ToBoolean(ConfigurationManager.AppSettings["IsCompatibleUpsellActive"]) &&
                                !isAdminDiscount &&
                                //bc.IsUpsellTriggered &&
                                bc.Quantity > bc.QtyStart)
                            {
                                discUnitPrice = Math.Round(bc.PriceEx, 2) - Math.Round(bc.PriceEx * discountRate / 100, 2);
                                //discUnitPrice = Math.Round(bc.PriceEx * (100 - discountRate) / 100, 2);
                                subt = discUnitPrice * bc.Quantity;
                                strike = "g-s";
                                discClass = "";
                            }


            
            #line default
            #line hidden
WriteLiteral("                            <hr");

WriteLiteral(" class=\"g-m-tb-10\"");

WriteLiteral(" />\r\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"row basket-entry g-m-tb-10 clearfix atb-entry\"");

WriteLiteral(" data-productid=\"");

            
            #line 91 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                  Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-5 col-lg-6 clearfix\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-lg-4 col-md-5 g-p-lr-0 g-m-t-5\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5197), Tuple.Create("\"", 5218)
            
            #line 96 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 5204), Tuple.Create<System.Object, System.Int32>(bc.ProductUrl
            
            #line default
            #line hidden
, 5204), false)
);

WriteLiteral(">\r\n                                                    <img");

WriteLiteral(" class=\"g-b-1-p\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5294), Tuple.Create("\"", 5312)
            
            #line 97 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 5300), Tuple.Create<System.Object, System.Int32>(bc.ImageUrl
            
            #line default
            #line hidden
, 5300), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 5313), Tuple.Create("\"", 5334)
            
            #line 97 "..\..\Views\Checkout\BasketDetails.cshtml"
                 , Tuple.Create(Tuple.Create("", 5319), Tuple.Create<System.Object, System.Int32>(bc.Description
            
            #line default
            #line hidden
, 5319), false)
);

WriteAttribute("onerror", Tuple.Create(" onerror=\"", 5335), Tuple.Create("\"", 5418)
, Tuple.Create(Tuple.Create("", 5345), Tuple.Create("this.src", 5345), true)
, Tuple.Create(Tuple.Create(" ", 5353), Tuple.Create("=", 5354), true)
, Tuple.Create(Tuple.Create(" ", 5355), Tuple.Create("\'", 5356), true)
            
            #line 97 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 5357), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 5357), false)
, Tuple.Create(Tuple.Create("", 5397), Tuple.Create("/Images/noimage.jpg\';", 5397), true)
);

WriteLiteral(">\r\n                                                </a>\r\n                        " +
"                    </div>\r\n                                            <div");

WriteLiteral(" class=\"col-lg-6 col-md-7 g-p-lr-0 g-m-t-10\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5757), Tuple.Create("\"", 5778)
            
            #line 102 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 5764), Tuple.Create<System.Object, System.Int32>(bc.ProductUrl
            
            #line default
            #line hidden
, 5764), false)
);

WriteLiteral(">");

            
            #line 102 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                        Write(bc.Description);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                                </div>\r\n                   " +
"                             <div");

WriteLiteral(" class=\"g-fs-sm g-m-t-5\"");

WriteLiteral(">\r\n                                                    <strong>Product Code:</str" +
"ong> ");

            
            #line 105 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                              Write(bc.PartNo);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </div>\r\n                       " +
"                         <div");

WriteLiteral(" class=\"text-center g-m-t-10 g-fs-sm g-lh-20 hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 107 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                                 Write(Html.ProductAvailability(bc.Availability, Convert.ToBoolean(Model.CommonData["DeliveryDateIsOverridden"].ToString())));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                            </div>\r\n                     " +
"                       <div");

WriteLiteral(" class=\"col-lg-2 g-p-lr-0 g-m-l-a be-Price pull-right hidden-md hidden-sm hidden-" +
"xs text-center\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"g-m-tb-50p\"");

WriteLiteral(">\r\n                                                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 6660), Tuple.Create("\"", 6675)
            
            #line 111 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 6668), Tuple.Create<System.Object, System.Int32>(strike
            
            #line default
            #line hidden
, 6668), false)
);

WriteLiteral(">");

            
            #line 111 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                    Write(neg);

            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                        Write(string.Format("{0:C}", bc.PriceEx));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 6780), Tuple.Create("\"", 6798)
            
            #line 112 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 6788), Tuple.Create<System.Object, System.Int32>(discClass
            
            #line default
            #line hidden
, 6788), false)
);

WriteLiteral(">");

            
            #line 112 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                       Write(neg);

            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                           Write(string.Format("{0:C}", discUnitPrice));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                                </div>\r\n                 " +
"                           </div>\r\n                                            <" +
"div");

WriteLiteral(" class=\"col-xs-12 g-p-lr-0 be-Price hidden-lg\"");

WriteLiteral(">\r\n                                                <span");

WriteAttribute("class", Tuple.Create(" class=\"", 7108), Tuple.Create("\"", 7123)
            
            #line 116 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 7116), Tuple.Create<System.Object, System.Int32>(strike
            
            #line default
            #line hidden
, 7116), false)
);

WriteLiteral(">");

            
            #line 116 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                 Write(neg);

            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                     Write(string.Format("{0:C}", bc.PriceEx));

            
            #line default
            #line hidden
WriteLiteral("</span>&nbsp;\r\n                                                <span");

WriteAttribute("class", Tuple.Create(" class=\"", 7232), Tuple.Create("\"", 7250)
            
            #line 117 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 7240), Tuple.Create<System.Object, System.Int32>(discClass
            
            #line default
            #line hidden
, 7240), false)
);

WriteLiteral(">");

            
            #line 117 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                    Write(neg);

            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                        Write(string.Format("{0:C}", discUnitPrice));

            
            #line default
            #line hidden
WriteLiteral(" ea.</span>\r\n                                            </div>\r\n                " +
"                            <div");

WriteLiteral(" class=\"atb-add g-d-n\"");

WriteLiteral("\r\n                                                 data-price=\"0\"");

WriteLiteral("\r\n                                                 data-productid=\"");

            
            #line 121 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                            Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                 data-partno=\"");

            
            #line 122 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                         Write(bc.PartNo);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                 data-imageurl=\"");

            
            #line 123 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                           Write(bc.ImageUrl);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                 data-desc=\"");

            
            #line 124 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                       Write(bc.Description);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"              </div>\r\n                                    </div>\r\n              " +
"                  </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-7 col-lg-6\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-md-3 g-p-lr-0\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"g-m-l-10-md g-m-t-30 text-md-center\"");

WriteLiteral(">\r\n");

            
            #line 134 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                     if (!bc.IsFreeGift)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <div");

WriteLiteral(" class=\"g-w-78 g-h-40\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");

            
            #line 137 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                        Write(Html.Kendo().NumericTextBox<int>()
                                                          .Format("#")
                                                          .Name("qty-" + bc.StockRef)
                                                          .Value(int.Parse(bc.Quantity.ToString()))
                                                          .Placeholder("Enter quantity")
                                                          .HtmlAttributes(new { style = "width: 100%; height: 34px", @class = "atb-qty" })
                                                          .Min(1)
                                                          .Max(1000)
                                                          .Events(events => events
                                                              .Change(
                                                            item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n                                                                function(e) {\r\n" +
"                                                                changeBasketQty(" +
"\"");

            
            #line 149 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                 WriteTo(__razor_template_writer, bc.StockRef);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\", e.sender._value);\r\n                                                           " +
"     }\r\n                                                            ");

WriteLiteralTo(__razor_template_writer, "\r\n");

            
            #line 152 "..\..\Views\Checkout\BasketDetails.cshtml"
})                                                              ).Spin(
                                                            item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n                                                                function(e) {\r\n" +
"                                                                changeBasketQty(" +
"\"");

            
            #line 155 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                 WriteTo(__razor_template_writer, bc.StockRef);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\", e.sender._value);\r\n                                                           " +
"     }\r\n                                                            ");

WriteLiteralTo(__razor_template_writer, "\r\n");

            
            #line 158 "..\..\Views\Checkout\BasketDetails.cshtml"
})                                                              ))
                                                            );

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                                        </div>\r\n");

WriteLiteral("                                                        <div");

WriteLiteral(" class=\"delete g-m-t-10 g-fs-sm g-i g-cur-p\"");

WriteLiteral(" data-productid=\"");

            
            #line 162 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                                    Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" title=\"Remove this item from the basket\"");

WriteLiteral(">\r\n                                                            Remove\r\n          " +
"                                              </div>\r\n");

            
            #line 165 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                    }

            
            #line default
            #line hidden
WriteLiteral("                                                </div>\r\n                         " +
"                   </div>\r\n                                            <div");

WriteLiteral(" class=\"col-md-6 g-p-lr-0 text-md-right\"");

WriteLiteral(">\r\n");

            
            #line 169 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 169 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                 if (!bc.IsCompatible && !String.IsNullOrEmpty(bc.CrossSellingStockRef))
                                                {
                                                    List<int> inStock = new List<int> { 1, 7 }; // Availability codes which indicate item in stock
                                                    if (inStock.Contains(bc.CrossSellingAvailability))
                                                    {
                                                        decimal saving = (bc.PriceEx - bc.CrossSellingPriceEx) * bc.Quantity;
                                                        if (saving > 0)
                                                        {                                                            

            
            #line default
            #line hidden
WriteLiteral("                                                            <button");

WriteLiteral(" class=\"atb-replace btn g-butt-important g-br-3 g-m-t-30 g-p-lr-5 g-h-40\"");

WriteAttribute("title", Tuple.Create("\r\n                                                                    title=\"", 12022), Tuple.Create("\"", 12178)
, Tuple.Create(Tuple.Create("", 12099), Tuple.Create("Click", 12099), true)
, Tuple.Create(Tuple.Create(" ", 12104), Tuple.Create("to", 12105), true)
, Tuple.Create(Tuple.Create(" ", 12107), Tuple.Create("replace", 12108), true)
, Tuple.Create(Tuple.Create(" ", 12115), Tuple.Create("this", 12116), true)
, Tuple.Create(Tuple.Create(" ", 12120), Tuple.Create("item", 12121), true)
, Tuple.Create(Tuple.Create(" ", 12125), Tuple.Create("with", 12126), true)
, Tuple.Create(Tuple.Create(" ", 12130), Tuple.Create("the", 12131), true)
, Tuple.Create(Tuple.Create(" ", 12134), Tuple.Create("equivalent", 12135), true)
, Tuple.Create(Tuple.Create(" ", 12145), Tuple.Create("&#10;", 12146), true)
            
            #line 178 "..\..\Views\Checkout\BasketDetails.cshtml"
                                              , Tuple.Create(Tuple.Create("", 12151), Tuple.Create<System.Object, System.Int32>(bc.CrossSellingDescription
            
            #line default
            #line hidden
, 12151), false)
);

WriteLiteral("\r\n                                                                    data-produc" +
"tid=\"");

            
            #line 179 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                               Write(bc.CrossSellingStockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                                    data-price=" +
"\"");

            
            #line 180 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                           Write(bc.CrossSellingPriceEx);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                                    data-remove" +
"id=\"");

            
            #line 181 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                              Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                                    data-qty=\"");

            
            #line 182 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                         Write(bc.Quantity.ToString());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                                                Save ");

            
            #line 183 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                Write(string.Format("{0:C}", saving));

            
            #line default
            #line hidden
WriteLiteral(" Now!\r\n                                                                <div");

WriteLiteral(" class=\"g-fs-sm\"");

WriteLiteral(">Replace with compatible product</div>\r\n                                         " +
"                   </button>\r\n");

            
            #line 186 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                        }
                                                                }
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                ");

            
            #line 189 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                 if (bc.IsCompatible && Session["V_Voucher"] == null &&
                                                     Convert.ToBoolean(ConfigurationManager.AppSettings["IsCompatibleUpsellActive"]) &&
                                                     !isAdminDiscount)
                                                {
                                                    decimal saving = Math.Round(bc.PriceEx * discountRate / 100, 2);
                                                    string btnMsg = "";
                                                    if (bc.Quantity <= bc.QtyStart)
                                                    {
                                                        btnMsg = "Get " + discountRate + "% off (" + saving.ToString("C") + " ex VAT)<div class=\"g-fs-sm\">Each item when you put " + (bc.QtyStart + 1)  + "+ in the basket</div>"; // "Save " + saving.ToString("C") + " ex VAT per item</div>");

            
            #line default
            #line hidden
WriteLiteral("                                                        <button");

WriteLiteral(" class=\"btn g-butt-important g-br-3 g-m-t-30 g-p-lr-5 g-h-40\"");

WriteLiteral("\r\n                                                                title=\"Click to" +
" get this offer\"");

WriteAttribute("onclick", Tuple.Create("\r\n                                                                onclick=\"", 14290), Tuple.Create("\"", 14416)
, Tuple.Create(Tuple.Create("", 14365), Tuple.Create("changeBasketQty(\'", 14365), true)
            
            #line 200 "..\..\Views\Checkout\BasketDetails.cshtml"
         , Tuple.Create(Tuple.Create("", 14382), Tuple.Create<System.Object, System.Int32>(bc.StockRef
            
            #line default
            #line hidden
, 14382), false)
, Tuple.Create(Tuple.Create("", 14394), Tuple.Create("\',", 14394), true)
            
            #line 200 "..\..\Views\Checkout\BasketDetails.cshtml"
                        , Tuple.Create(Tuple.Create(" ", 14396), Tuple.Create<System.Object, System.Int32>(bc.QtyStart + 1
            
            #line default
            #line hidden
, 14397), false)
, Tuple.Create(Tuple.Create("", 14415), Tuple.Create(")", 14415), true)
);

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");

            
            #line 201 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                       Write(Html.Raw(btnMsg));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        </button>\r\n");

            
            #line 203 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                    }
                                                    else
                                                    {
                                                        if (bc.Quantity > 1)
                                                        {
                                                            btnMsg = "Wow, you're saving " + discountRate + "%, that's<div>" + saving.ToString("C") + " ex VAT on each item!";

            
            #line default
            #line hidden
WriteLiteral("                                                            <button");

WriteLiteral(" class=\"btn g-butt-important g-br-3 g-m-t-30 g-p-lr-5 g-h-40\"");

WriteLiteral("\r\n                                                                    title=\"Clic" +
"k to add another to the basket\"");

WriteAttribute("onclick", Tuple.Create("\r\n                                                                    onclick=\"", 15287), Tuple.Create("\"", 15417)
, Tuple.Create(Tuple.Create("", 15366), Tuple.Create("changeBasketQty(\'", 15366), true)
            
            #line 211 "..\..\Views\Checkout\BasketDetails.cshtml"
             , Tuple.Create(Tuple.Create("", 15383), Tuple.Create<System.Object, System.Int32>(bc.StockRef
            
            #line default
            #line hidden
, 15383), false)
, Tuple.Create(Tuple.Create("", 15395), Tuple.Create("\',", 15395), true)
            
            #line 211 "..\..\Views\Checkout\BasketDetails.cshtml"
                            , Tuple.Create(Tuple.Create(" ", 15397), Tuple.Create<System.Object, System.Int32>(bc.Quantity + 1
            
            #line default
            #line hidden
, 15398), false)
, Tuple.Create(Tuple.Create("", 15416), Tuple.Create(")", 15416), true)
);

WriteLiteral(">");

            
            #line 211 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                                             Write(Html.Raw(btnMsg));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                            </button>\r\n");

            
            #line 213 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                        }
                                                    }
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </div>\r\n                             " +
"               <div");

WriteLiteral(" class=\"col-md-3 g-p-lr-0\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"g-m-l-a g-m-t-40 g-p-r-20 text-md-right\"");

WriteLiteral(">\r\n                                                    <div>");

            
            #line 219 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                    Write(neg);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 219 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                         Write(string.Format("{0:C}", subt));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 220 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 220 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                      
                                                        if (Session["V_Voucher"] != null)
                                                        {
                                                            VoucherPromo vp = (VoucherPromo)Session["V_Voucher"];
                                                            if (bc.IsVoucherQualifyingItem && vp.VoucherTypeFk == (int) VmVoucherType.Percentage)
                                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                                <div");

WriteLiteral(" class=\"g-m-t-20 g-fs-sm g-fc-pm g-i g-cur-p\"");

WriteLiteral(">\r\n                                                                    Voucher Ap" +
"plied\r\n                                                                </div>\r\n");

            
            #line 229 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                            }
                                                        }
                                                    
            
            #line default
            #line hidden
WriteLiteral(@"
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
");

            
            #line 238 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                            }
                        if (bc.ItemType == BasketItemType.CompatibleDiscount)
                        {
                            isMultiBuy = true;
                            multibuyAmount = bc.PriceEx;
                            
                        }
                    }


            
            #line default
            #line hidden
WriteLiteral("                    <hr");

WriteLiteral(" class=\"g-m-tb-10\"");

WriteLiteral(" />\r\n");

            
            #line 248 "..\..\Views\Checkout\BasketDetails.cshtml"
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 252 "..\..\Views\Checkout\BasketDetails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"basket-voucher col-md-8\"");

WriteLiteral(">\r\n");

            
            #line 255 "..\..\Views\Checkout\BasketDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 255 "..\..\Views\Checkout\BasketDetails.cshtml"
             if((Model.CheckoutDetails.ZeroStock || Model.CheckoutDetails.IsSpecialOrder) && !Convert.ToBoolean(Session["U_IsPortalUser"]))
            {
                Dictionary<string, string> replacements = new Dictionary<string, string>();

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"g-bc-note g-b-1-p g-p-10 g-m-t-10 g-w-345\"");

WriteLiteral(">");

            
            #line 258 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                   Write(Html.RawFromDict(Model.CheckoutData, "ZeroStock", replacements));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 259 "..\..\Views\Checkout\BasketDetails.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 261 "..\..\Views\Checkout\BasketDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 261 "..\..\Views\Checkout\BasketDetails.cshtml"
             if(!isAdminDiscount)
            {
                if (Session["B_VoucherCode"].ToSafeString() != "")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"g-fc-secondary g-m-t-10\"");

WriteLiteral(">\r\n                        <strong>Voucher code</strong>\r\n                    </d" +
"iv>\r\n");

WriteLiteral("                    <div id = \"voucher-msg\" class=\"g-m-t-10\">\r\n                  " +
"      <span>Voucher<strong> ");

            
            #line 269 "..\..\Views\Checkout\BasketDetails.cshtml"
                                         Write(Session["B_VoucherCode"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("</strong> has been recognised. Please note that only one offer can be applied to " +
"an order.</span>\r\n                        <span>\r\n                            <a" +
"");

WriteLiteral(" class=\"remove-voucher\"");

WriteLiteral(">[Remove]</a>\r\n                        </span>\r\n                    </div>\r\n");

            
            #line 274 "..\..\Views\Checkout\BasketDetails.cshtml"
                    if (!string.IsNullOrEmpty(ViewBag.VoucherMessage))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"g-d-ib\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"error-message g-m-t-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 278 "..\..\Views\Checkout\BasketDetails.cshtml"
                           Write(Html.Raw(ViewBag.VoucherMessage));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 281 "..\..\Views\Checkout\BasketDetails.cshtml"
                    }
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"g-fc-secondary g-m-t-10\"");

WriteLiteral(">\r\n                        <strong>Add a voucher code</strong>\r\n                 " +
"   </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"bkt-voucher input-group g-m-t-10 g-w-345\"");

WriteLiteral(">\r\n                        <input id = \"voucher-code\" class=\"form-control g-h-40 " +
"pull-left\" placeholder=\"Enter Voucher Code ...\" type=\"text\">\r\n                  " +
"      <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                            <button id = \"apply-voucher\" class=\"g-butt-seconda" +
"ry g-butt-lg g-fs-n\" type=\"button\">Apply Voucher</button>\r\n                     " +
"     </span>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"g-d-ib\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"error-message g-d-n g-m-t-10\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-exclamation-triangle g-fs-20 g-p-r-10\"");

WriteLiteral("></i>\r\n                            <p");

WriteLiteral(" class=\"g-m-0 g-d-i g-p-r-10\"");

WriteLiteral("></p>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 300 "..\..\Views\Checkout\BasketDetails.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 302 "..\..\Views\Checkout\BasketDetails.cshtml"
             if(Convert.ToBoolean(Session["U_IsPortalUser"]))
                                                                {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"g-m-t-60 g-m-b-20 g-br-0 panel panel-default\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-heading g-fw-b\"");

WriteLiteral(">Customer Service Tools</div>\r\n                    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 307 "..\..\Views\Checkout\BasketDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 307 "..\..\Views\Checkout\BasketDetails.cshtml"
                         if(String.IsNullOrEmpty(Session["B_VoucherCode"] as string))
                        {
                            if (isAdminDiscount)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"g-m-t-10 g-fw-b\"");

WriteLiteral(">ADMIN DISCOUNT HAS BEEN APPLIED TO THIS ORDER</div>\r\n");

            
            #line 312 "..\..\Views\Checkout\BasketDetails.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"g-fc-secondary g-m-t-10\"");

WriteLiteral(">Administrator Discount Inc.Vat</div>\r\n");

WriteLiteral("                                <div");

WriteLiteral(" class=\"atb-entry bkt-discount input-group g-m-t-10 g-w-345\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"input-group-addon g-br-0 g-fc-tt g-b-n g-bc-s\"");

WriteLiteral(" style=\"border-right: 1px solid #cccccc !important;\"");

WriteLiteral(">-&pound;</span>\r\n                                    <input id = \"admin-discount" +
"\" class=\"form-control g-h-40 pull-left\" placeholder=\"Enter discount ...\" type=\"n" +
"umber\">\r\n                                    <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(@">
                                        <button id = ""apply-discount"" class=""g-butt-secondary g-butt-lg g-fs-n"" type=""button"">Apply Discount</button>
                                          <button id = ""discount-atb"" class=""atb-add g-d-n""
                                                data-vatm=""");

            
            #line 322 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                      Write(Model.VatMultiplier);

            
            #line default
            #line hidden
WriteLiteral(@"""
                                                data-productid=""4957""
                                                data-partno=""""
                                                data-price=""""
                                                data-itemtype=""2""></button>
                                    </span>
                                </div>
");

            
            #line 329 "..\..\Views\Checkout\BasketDetails.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"g-m-t-10 basket-entry\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"atb-entry input-group g-m-t-10 g-w-345\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"input-group-addon g-br-0 g-b-n g-bc-s\"");

WriteLiteral(@">Clear All Products</span>
                                <button id = ""admn-clear-basket"" class=""g-butt g-butt-secondary g-butt-lg pull-right""
                                        title=""Clear all items from the basket"">
                                    Clear
                                </button>
                            </div>
                            <div");

WriteLiteral(" class=\"g-m-t-10\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"atb-entry input-group g-m-t-10 g-w-345\"");

WriteLiteral(">\r\n");

            
            #line 341 "..\..\Views\Checkout\BasketDetails.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 341 "..\..\Views\Checkout\BasketDetails.cshtml"
                                     if(ViewBag.OrderIsOnHold)
                                                                {

            
            #line default
            #line hidden
WriteLiteral("                                        <span");

WriteLiteral(" class=\"input-group-addon g-br-0 g-b-n g-bc-s\"");

WriteLiteral(">Order is On Hold</span>\r\n");

WriteLiteral("                                         <button");

WriteLiteral(" class=\"g-butt g-butt-secondary g-butt-lg delete pull-right\"");

WriteLiteral("\r\n                                                data-productid=\"ONHOLD\"");

WriteLiteral("\r\n                                                title=\"Remove from on hold\"");

WriteLiteral(">\r\n                                            Remove\r\n                          " +
"              </button>\r\n");

            
            #line 349 "..\..\Views\Checkout\BasketDetails.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <span");

WriteLiteral(" class=\"input-group-addon g-br-0 g-b-n g-bc-s\"");

WriteLiteral(">Place Order On Hold</span>\r\n");

WriteLiteral("                                        <button");

WriteLiteral(" class=\"g-butt g-butt-secondary g-butt-lg atb-add pull-right\"");

WriteLiteral("\r\n                                                data-price=\"0.00\"");

WriteLiteral("\r\n                                                data-productid=\"ONHOLD\"");

WriteLiteral("\r\n                                                data-partno=\"ONHOLD\"");

WriteLiteral("\r\n                                                data-imageurl=\"unknown.jpg\"");

WriteLiteral("\r\n                                                data-itemtype=\"3\"");

WriteLiteral("\r\n                                                title=\"Place this order on hold" +
"\"");

WriteLiteral(">\r\n                                            Place On Hold\r\n                   " +
"                     </button>\r\n");

            
            #line 362 "..\..\Views\Checkout\BasketDetails.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n                            </div>\r\n     " +
"                   </div>\r\n                    </div>\r\n                </div>\r\n");

            
            #line 368 "..\..\Views\Checkout\BasketDetails.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-m-t-10 clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>Delivery</strong>\r\n                </div>\r\n       " +
"         <div");

WriteLiteral(" class=\"pull-right g-p-r-20\"");

WriteLiteral(">\r\n");

            
            #line 376 "..\..\Views\Checkout\BasketDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 376 "..\..\Views\Checkout\BasketDetails.cshtml"
                     if(Model.BasketTotals.Delivery == 0)
                                                                {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("FREE\r\n");

            
            #line 379 "..\..\Views\Checkout\BasketDetails.cshtml"
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 382 "..\..\Views\Checkout\BasketDetails.cshtml"
                   Write(Html.Raw("&pound;" + string.Format("{0:N2}", Math.Abs(Model.BasketTotals.Delivery))));

            
            #line default
            #line hidden
            
            #line 382 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                             
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"g-m-t-10 clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>Sub Total</strong>\r\n                </div>\r\n      " +
"          <div");

WriteLiteral(" class=\"pull-right g-p-r-20\"");

WriteLiteral(">&pound;");

            
            #line 390 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                   Write(string.Format("{0:N2}", Model.BasketTotals.TotalExcVat - Model.BasketTotals.Delivery));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"g-m-t-10 clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>VAT</strong>\r\n                </div>\r\n            " +
"    <div");

WriteLiteral(" class=\"pull-right g-p-r-20\"");

WriteLiteral(">&pound;");

            
            #line 396 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                   Write(string.Format("{0:N2}", Model.BasketTotals.Vat + Model.BasketTotals.VoucherVat));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 26151), Tuple.Create("\"", 26196)
            
            #line 399 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 26159), Tuple.Create<System.Object, System.Int32>(ViewBag.HideVoucher ? "g-d-n" : ""
            
            #line default
            #line hidden
, 26159), false)
);

WriteLiteral(">\r\n                <hr");

WriteLiteral(" class=\"g-m-tb-10\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" id=\"voucherTotal\"");

WriteLiteral(" class=\"g-m-t-10 clearfix g-lh-40\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                        <strong>Voucher</strong>\r\n                    </div>\r\n" +
"                    <div");

WriteLiteral(" class=\"pull-right g-p-r-20 g-i g-fc-pm\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"voucherValue\"");

WriteLiteral(">\r\n");

            
            #line 407 "..\..\Views\Checkout\BasketDetails.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 407 "..\..\Views\Checkout\BasketDetails.cshtml"
                             if (Model.BasketTotals.Voucher == 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                ");

WriteLiteral("FREE GIFT\r\n");

            
            #line 410 "..\..\Views\Checkout\BasketDetails.cshtml"
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 413 "..\..\Views\Checkout\BasketDetails.cshtml"
                            Write((Model.BasketTotals.Voucher < 0 ? "-" : ""));

            
            #line default
            #line hidden
            
            #line 413 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                              
                                
            
            #line default
            #line hidden
            
            #line 414 "..\..\Views\Checkout\BasketDetails.cshtml"
                           Write(Html.Raw(("&pound;" + string.Format("{0:N2}", Math.Abs(Model.BasketTotals.Voucher)) + " (inc VAT)")));

            
            #line default
            #line hidden
            
            #line 414 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                                                     
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </span>\r\n                    </div>\r\n                </di" +
"v>\r\n            </div>\r\n            \r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 27177), Tuple.Create("\"", 27213)
            
            #line 421 "..\..\Views\Checkout\BasketDetails.cshtml"
, Tuple.Create(Tuple.Create("", 27185), Tuple.Create<System.Object, System.Int32>(isMultiBuy ? "" : "g-d-n"
            
            #line default
            #line hidden
, 27185), false)
);

WriteLiteral(">\r\n                <hr");

WriteLiteral(" class=\"g-m-tb-10\"");

WriteLiteral(" />\r\n                <div");

WriteLiteral(" id=\"voucherTotal\"");

WriteLiteral(" class=\"g-m-t-10 clearfix g-lh-40\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                        <strong>You have saved</strong>\r\n                    <" +
"/div>\r\n                    <div");

WriteLiteral(" class=\"pull-right g-p-r-20 g-i g-fc-pm\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"voucherValue\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 429 "..\..\Views\Checkout\BasketDetails.cshtml"
                       Write(Html.Raw(("&pound;" + string.Format("{0:N2}", multibuyAmount) + " (ex VAT)")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n\r\n            <hr");

WriteLiteral(" class=\"g-m-tb-10\"");

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"g-m-t-10 clearfix g-lh-40\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>Grand Total</strong>\r\n                </div>\r\n    " +
"            <div");

WriteLiteral(" class=\"pull-right g-fs-lg g-p-r-20\"");

WriteLiteral(">\r\n                    <strong>\r\n                        <span>&pound;");

            
            #line 442 "..\..\Views\Checkout\BasketDetails.cshtml"
                                Write(string.Format("{0:N2}", Model.BasketTotals.GrandTotalIncVat));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </strong>\r\n                </div>\r\n            </div" +
">\r\n\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"checkout-button btn g-butt-primary g-butt-100p g-m-t-20 g-m-b-20 pull-rig" +
"ht\"");

WriteLiteral(" title=\"Checkout\"");

WriteLiteral(">Proceed to Checkout</button>\r\n            <form");

WriteLiteral(" id=\"co-form\"");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 28484), Tuple.Create("\"", 28511)
, Tuple.Create(Tuple.Create("", 28493), Tuple.Create<System.Object, System.Int32>(Href("~/Checkout/Stage1/")
, 28493), false)
);

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 450 "..\..\Views\Checkout\BasketDetails.cshtml"
           Write(Html.HiddenFor(x => x.CheckoutDetails.IsNewCustomer));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 451 "..\..\Views\Checkout\BasketDetails.cshtml"
           Write(Html.HiddenFor(x => x.CheckoutDetails.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 452 "..\..\Views\Checkout\BasketDetails.cshtml"
           Write(Html.HiddenFor(x => x.CheckoutDetails.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 453 "..\..\Views\Checkout\BasketDetails.cshtml"
           Write(Html.HiddenFor(x => x.CheckoutDetails.ZeroStock));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n\r\n");

            
            #line 456 "..\..\Views\Checkout\BasketDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 456 "..\..\Views\Checkout\BasketDetails.cshtml"
             if (!Convert.ToBoolean(Session["U_IsPortalUser"]) && Model.BasketTotals.GrandTotalIncVat > 0.01m)
                {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" id=\"paypal-button\"");

WriteLiteral(" class=\"g-m-t-20\"");

WriteLiteral("></div>\r\n");

WriteLiteral("                    <form");

WriteLiteral(" id=\"paypal-form\"");

WriteLiteral(" action=\"/checkout/stage3/\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"PayPalPaid\"");

WriteLiteral(" id=\"PayPalPaid\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                    </form>\r\n");

            
            #line 462 "..\..\Views\Checkout\BasketDetails.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 465 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                        }
                                                        else
                                                        {

            
            #line default
            #line hidden
WriteLiteral("                                                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                                                    <span>Your" +
" basket is currently empty, ");

            
            #line 470 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                                                                     Write(Html.ActionLink("continue shopping", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                                </div>\r\n" +
"                                                            </div>\r\n");

            
            #line 473 "..\..\Views\Checkout\BasketDetails.cshtml"
                                                        }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
