#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Product\PrintersForProducts.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Product\PrintersForProducts.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Product\PrintersForProducts.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Product\PrintersForProducts.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 4 "..\..\Views\Product\PrintersForProducts.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Product/PrintersForProducts.cshtml")]
    public partial class _Views_Product_PrintersForProducts_cshtml : System.Web.Mvc.WebViewPage<SearchViewModel>
    {
        public _Views_Product_PrintersForProducts_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h2>Printers that accept ");

            
            #line 11 "..\..\Views\Product\PrintersForProducts.cshtml"
                            Write(Model.EquipmentDetail.Rows[0]["Description"].ToString());

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"g-tt-c\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\Product\PrintersForProducts.cshtml"
                                                                                                          Write(Model.EquipmentDetail.Rows[0]["CartridgeTypeName"].RangeReplace(false));

            
            #line default
            #line hidden
WriteLiteral("</span></h2>\r\n    </div>\r\n");

            
            #line 13 "..\..\Views\Product\PrintersForProducts.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Product\PrintersForProducts.cshtml"
     foreach (DataRow dr in Model.PrintersForProducts.Rows)
    {
        string link = "/model/" + dr["Description"].ToString().Replace(" ", "-") + "-" + dr["CartridgeType"].RangeReplace() + "/";

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-6 g-p-b-10\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-chevron-right g-p-r-10\"");

WriteLiteral("></i>\r\n            <a");

WriteLiteral(" class=\"primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 745), Tuple.Create("\"", 757)
            
            #line 18 "..\..\Views\Product\PrintersForProducts.cshtml"
, Tuple.Create(Tuple.Create("", 752), Tuple.Create<System.Object, System.Int32>(link
            
            #line default
            #line hidden
, 752), false)
);

WriteLiteral(">");

            
            #line 18 "..\..\Views\Product\PrintersForProducts.cshtml"
                                        Write(dr["Description"].ToString());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </div>\r\n");

            
            #line 20 "..\..\Views\Product\PrintersForProducts.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
