//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provider()
        {
            this.BackOrders = new HashSet<BackOrder>();
            this.OrderTracking = new HashSet<OrderTracking>();
            this.fieldMapping = new HashSet<fieldMapping>();
            this.ftpDetails = new HashSet<ftpDetails>();
            this.priorityProvider = new HashSet<priorityProvider>();
            this.providerInventory = new HashSet<providerInventory>();
            this.skuMapping = new HashSet<skuMapping>();
            this.supplierManuMapping = new HashSet<supplierManuMapping>();
        }
    
        public int providerID { get; set; }
        public string providerName { get; set; }
        public string providerDesc { get; set; }
        public int providerTypeFK { get; set; }
        public System.DateTime dateLastUpdate { get; set; }
        public Nullable<int> axisSupplierRef { get; set; }
        public Nullable<System.DateTime> feedFileDateTime { get; set; }
        public bool active { get; set; }
        public Nullable<int> reviewTotal { get; set; }
        public Nullable<decimal> reviewRating { get; set; }
        public string shortName { get; set; }
        public string url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackOrder> BackOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTracking> OrderTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fieldMapping> fieldMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftpDetails> ftpDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<priorityProvider> priorityProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<providerInventory> providerInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skuMapping> skuMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplierManuMapping> supplierManuMapping { get; set; }
    }
}
