#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Portal\RequestData.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 2 "..\..\Views\Portal\RequestData.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Portal/RequestData.cshtml")]
    public partial class _Views_Portal_RequestData_cshtml : System.Web.Mvc.WebViewPage<CommonViewModel>
    {
        public _Views_Portal_RequestData_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>Variable Name</th>\r\n   " +
"             <th>Variable Value</th>\r\n            </tr>\r\n        </thead>\r\n     " +
"   <tbody>\r\n");

            
            #line 15 "..\..\Views\Portal\RequestData.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Portal\RequestData.cshtml"
             foreach (string s in Request.Params.Keys)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 18 "..\..\Views\Portal\RequestData.cshtml"
                   Write(s.ToString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 19 "..\..\Views\Portal\RequestData.cshtml"
                   Write(Request.Params[s]);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 21 "..\..\Views\Portal\RequestData.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n\r\n<h2>Request Properties</h2>\r\n<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>Variable Name</th>\r\n   " +
"             <th>Variable Value</th>\r\n            </tr>\r\n        </thead>\r\n     " +
"   <tbody>\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"white-space: nowrap;\"");

WriteLiteral(">UserHostAddress</td>\r\n                <td>");

            
            #line 38 "..\..\Views\Portal\RequestData.cshtml"
               Write(Request.UserHostAddress);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"white-space: nowrap;\"");

WriteLiteral(">IP Used By WebApp</td>\r\n                <td>");

            
            #line 42 "..\..\Views\Portal\RequestData.cshtml"
               Write(ViewBag.ClientIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n</div>\r\n\r\n<h2>Request.H" +
"eaders</h2>\r\n<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>Variable Name</th>\r\n   " +
"             <th>Variable Value</th>\r\n            </tr>\r\n        </thead>\r\n     " +
"   <tbody>\r\n");

            
            #line 58 "..\..\Views\Portal\RequestData.cshtml"
            
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Portal\RequestData.cshtml"
              
                var headers = Request.Headers;
            
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 62 "..\..\Views\Portal\RequestData.cshtml"
            
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Portal\RequestData.cshtml"
             for (var i = 0; i < headers.Count; i++)
            {
                var key = headers.GetKey(i);
                var value = headers.Get(i);


            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" style=\"white-space: nowrap;\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Portal\RequestData.cshtml"
                                                Write(key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 69 "..\..\Views\Portal\RequestData.cshtml"
                   Write(value);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 71 "..\..\Views\Portal\RequestData.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
