#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\CSCheck.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    using CommonUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/CSCheck.cshtml")]
    public partial class _Views_Shared_CSCheck_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_CSCheck_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Shared\CSCheck.cshtml"
 if (Convert.ToBoolean(Session["U_IsPortalUser"]) && Session["U_CSUser"] == null)
{
    //string repl = "";

    List<SelectListItem> users = DataCache.GetCustLookups(x => x.LookupType.LookupTypeName == "Customer Service Users")
                .OrderBy(x => x.Sequence)
                .Select(x => new SelectListItem
                {
                    Text = x.LookupName.Split('|')[0],
                    Value = x.Sequence.ToString()
                })
                .OrderBy(x => x.Text)
                .ToList();

    string repl = HttpUtility.UrlEncode(Html.DropDownList("csuser-dropdown", users, null, new { @class = "form-control" }).ToString().Replace("\r\n", ""));


            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            $(function () {\r\n            launchPopup(\'CSAuth\', \'popup-csuser\'," +
" \'md\', \'selectlist=\' + \'");

            
            #line 21 "..\..\Views\Shared\CSCheck.cshtml"
                                                                    Write(repl);

            
            #line default
            #line hidden
WriteLiteral(@"', { backdrop: 'static', keyboard: false });

            $('.btn-csuser').click(function () {
                if ($('#csuser-dropdown').val()) {
                    SetCSUser($('#csuser-dropdown').val());
                }
            });
        });

        function SetCSUser(orderSource) {
            $.ajax({
            url: ""/Portal/SetCustomerServiceUser"",
                dataType: 'json',
                taditional: true,
                type: 'post',
                data: {
                orderSource: orderSource
                },
                async: false,
                success: function (e) {
                    if (e.savereturn.IsSuccess)
                        window.location.reload();
                },
                error: function (e) {
                    logAjaxScriptError(""/Portal/SetCustomerServiceUser"", xhr, textStatus, thrownError);
                }
            });
    }
    </script>
");

            
            #line 50 "..\..\Views\Shared\CSCheck.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
