//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public int WebsiteFk { get; set; }
        public string User { get; set; }
        public byte Type { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string Description { get; set; }
        public string Entry { get; set; }
        public string Url { get; set; }
        public string QueryString { get; set; }
        public string FormData { get; set; }
        public bool Deleted { get; set; }
        public string DeveloperComments { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
