//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryCode
    {
        public categoryCode()
        {
            this.categoryCode1 = new HashSet<categoryCode>();
            this.priceRule = new HashSet<priceRule>();
            this.secondaryCategoryLookup = new HashSet<secondaryCategoryLookup>();
            this.websiteInventory = new HashSet<websiteInventory>();
        }
    
        public int categoryCodeID { get; set; }
        public string categoryCodeName { get; set; }
        public Nullable<int> parentCategoryCodeID { get; set; }
        public int websiteFK { get; set; }
        public string AXISGroupID { get; set; }
        public System.DateTime dateLastUpdate { get; set; }
        public string AXISGroupNo { get; set; }
        public bool isPrimary { get; set; }
    
        public virtual ICollection<categoryCode> categoryCode1 { get; set; }
        public virtual categoryCode categoryCode2 { get; set; }
        public virtual ICollection<priceRule> priceRule { get; set; }
        public virtual ICollection<secondaryCategoryLookup> secondaryCategoryLookup { get; set; }
        public virtual ICollection<websiteInventory> websiteInventory { get; set; }
        public virtual Website Website { get; set; }
    }
}
