//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturerNotes
    {
        public int manufacturerNotesID { get; set; }
        public int websiteFK { get; set; }
        public Nullable<int> manufacturerFK { get; set; }
        public int eqCartridgeTypeFK { get; set; }
        public string note { get; set; }
    
        public virtual eqCartridgeType eqCartridgeType { get; set; }
        public virtual manufacturer manufacturer { get; set; }
        public virtual Website Website { get; set; }
    }
}
