//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.DiplomatReplacement
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerLine
    {
        public long LedgerLineId { get; set; }
        public int LedgerFk { get; set; }
        public Nullable<int> ProductFk { get; set; }
        public short Year { get; set; }
        public byte Period { get; set; }
        public byte LedgerTransactionTypeFk { get; set; }
        public byte LedgerRecordTypeFk { get; set; }
        public int ProductGroupFk { get; set; }
        public string AxisStockReference { get; set; }
        public int NominalAccount { get; set; }
        public int SalesGroupCode { get; set; }
        public System.DateTime DateInvoiced { get; set; }
        public int QuantityOrdered { get; set; }
        public Nullable<int> QuantityCredited { get; set; }
        public int QuantityOutstanding { get; set; }
        public double UnitPrice { get; set; }
        public double Nett { get; set; }
        public double Vat { get; set; }
        public double CostOfSales { get; set; }
        public Nullable<double> VatRate { get; set; }
        public int VatCode { get; set; }
        public string Description { get; set; }
        public string CountryOfDespatch { get; set; }
    
        public virtual Ledger Ledger { get; set; }
    }
}
