#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 3 "..\..\Views\Shared\JSTrackingAllHdr.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\JSTrackingAllHdr.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\JSTrackingAllHdr.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/JSTrackingAllHdr.cshtml")]
    public partial class _Views_Shared_JSTrackingAllHdr_cshtml : System.Web.Mvc.WebViewPage<CommonViewModel>
    {
        public _Views_Shared_JSTrackingAllHdr_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\JSTrackingAllHdr.cshtml"
  
    int websiteId = int.Parse(ConfigurationManager.AppSettings["WebsiteId"].ToString());
    string vwoId = "";
    switch (websiteId)
    {
        case 1:
        {
            vwoId = "32310";
            break;
        }
        case 2:
        {
            vwoId = "32310";
            break;
        }
        case 3:
        {
            vwoId = "32310";
            break;
        }
    }
    // VWO
    if (ConfigurationManager.AppSettings["VwoIsOn"] == "True" && vwoId != "")
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n            var _vwo_code=(function(){\r\n            var account_id=");

            
            #line 33 "..\..\Views\Shared\JSTrackingAllHdr.cshtml"
                      Write(vwoId);

            
            #line default
            #line hidden
WriteLiteral(@",
            settings_tolerance=2000,
            library_tolerance=2500,
            use_existing_jquery=false,
            // DO NOT EDIT BELOW THIS LINE
            f=false,d=document;return{use_existing_jquery:function(){return use_existing_jquery;},library_tolerance:function(){return library_tolerance;},finish:function(){if(!f){f=true;var a=d.getElementById('_vis_opt_path_hides');if(a)a.parentNode.removeChild(a);}},finished:function(){return f;},load:function(a){var b=d.createElement('script');b.src=a;b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};d.getElementsByTagName('head')[0].appendChild(b);},init:function(){settings_timer=setTimeout('_vwo_code.finish()',settings_tolerance);var a=d.createElement('style'),b='body{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;}',h=d.getElementsByTagName('head')[0];a.setAttribute('id','_vis_opt_path_hides');a.setAttribute('type','text/css');if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(d.createTextNode(b));h.appendChild(a);this.load('//dev.visualwebsiteoptimizer.com/j.php?a='+account_id+'&u='+encodeURIComponent(d.URL)+'&r='+Math.random());return settings_timer;}};}());_vwo_settings_timer=_vwo_code.init();
        ");

WriteLiteral("\r\n");

            
            #line 40 "..\..\Views\Shared\JSTrackingAllHdr.cshtml"
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
