#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Search\Autocomplete.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Search\Autocomplete.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Search\Autocomplete.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Search\Autocomplete.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Search/Autocomplete.cshtml")]
    public partial class _Views_Search_Autocomplete_cshtml : System.Web.Mvc.WebViewPage<SearchViewModel>
    {
        public _Views_Search_Autocomplete_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Search\Autocomplete.cshtml"
 if (Model.Results.Count > 0)
{
    foreach (var result in Model.Results)
    {
        string urlLink = "";
        string description = "";
        string imgUrl = "";
        if (result.ItemType == "Product")
        {
            urlLink = result.ProductUrl;
            description = result.FriendlyDescription;
            imgUrl = result.ImageUrl.Contains("http://") || result.ImageUrl.Contains("https://") ? result.ImageUrl : ConfigurationManager.AppSettings["CDN"] + "/" + result.ImageUrl;
        }
        else if (result.ItemType == "Equipment")
        {
            urlLink = result.FriendlyModel != null && result.CartridgeType != null ? $"/model/{result.FriendlyModel.Replace(" ", "-")}-{result.CartridgeType.Replace(" ", "-").Replace("HP-Range", "Toner-Cartridges").ToLower()}" : "";
            description = result.FriendlyModel;
            imgUrl = ConfigurationManager.AppSettings["CDN"] + "/" + result.ImageUrl;
        }
        else if (result.ItemType == "Category")
        {
            urlLink = result.FriendlyModel != null ? string.Format("/{0}/{1}-{2}", result.ProductCount > 0 ? "products" : "catalogue", Utilities.CleanUrl(result.Model.Replace(" ", "-")), result.ItemId) : "";
            description = result.FriendlyModel;
            imgUrl = ConfigurationManager.AppSettings["CDN"] + "/Images/category-icons/" + Utilities.CleanUrl(result.FriendlyModel.ToLower()) + ".jpg";
        }


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"g-m-tb-5 g-of-h\"");

WriteLiteral(" style=\"text-overflow: ellipsis; white-space: nowrap;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"primary g-d-b\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1715), Tuple.Create("\"", 1730)
            
            #line 35 "..\..\Views\Search\Autocomplete.cshtml"
, Tuple.Create(Tuple.Create("", 1722), Tuple.Create<System.Object, System.Int32>(urlLink
            
            #line default
            #line hidden
, 1722), false)
);

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1754), Tuple.Create("\"", 1767)
            
            #line 36 "..\..\Views\Search\Autocomplete.cshtml"
, Tuple.Create(Tuple.Create("", 1760), Tuple.Create<System.Object, System.Int32>(imgUrl
            
            #line default
            #line hidden
, 1760), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 1768), Tuple.Create("\"", 1801)
            
            #line 36 "..\..\Views\Search\Autocomplete.cshtml"
, Tuple.Create(Tuple.Create("", 1774), Tuple.Create<System.Object, System.Int32>(result.FriendlyDescription
            
            #line default
            #line hidden
, 1774), false)
);

WriteLiteral(" width=\"40\"");

WriteAttribute("onerror", Tuple.Create("\r\n                     onerror=\"", 1813), Tuple.Create("\"", 1916)
, Tuple.Create(Tuple.Create("", 1845), Tuple.Create("this.src=\'", 1845), true)
            
            #line 37 "..\..\Views\Search\Autocomplete.cshtml"
, Tuple.Create(Tuple.Create("", 1855), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1855), false)
, Tuple.Create(Tuple.Create("", 1895), Tuple.Create("/Images/noimage.jpg\';", 1895), true)
);

WriteLiteral(" class=\"g-d-b pull-left\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"g-m-l-10 g-lh-40\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Search\Autocomplete.cshtml"
               Write(Html.HighlightKeyWords(description, (string)ViewBag.Term, "search-highlight", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"g-fc-s\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Views\Search\Autocomplete.cshtml"
                Write(result.ProductCount > 0 ? $"({result.ProductCount} Products)" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n            </a>\r\n        </div>\r\n");

            
            #line 46 "..\..\Views\Search\Autocomplete.cshtml"
    }


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"text-center g-va-m\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"secondary g-d-b g-butt-second-reg g-butt-100p\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2427), Tuple.Create("\"", 2475)
, Tuple.Create(Tuple.Create("", 2434), Tuple.Create("/search-results?keyword=", 2434), true)
            
            #line 49 "..\..\Views\Search\Autocomplete.cshtml"
               , Tuple.Create(Tuple.Create("", 2458), Tuple.Create<System.Object, System.Int32>(Model.SearchTerm
            
            #line default
            #line hidden
, 2458), false)
);

WriteLiteral(" style=\"height: 100%; line-height: 40px;\"");

WriteLiteral(">Show All Results</a>\r\n    </div>\r\n");

            
            #line 51 "..\..\Views\Search\Autocomplete.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"text-center g-p-t-10\"");

WriteLiteral(">\r\n        No results found\r\n    </div>\r\n");

            
            #line 57 "..\..\Views\Search\Autocomplete.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
