#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Views\MyAccount\OrderDetail.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 5 "..\..\Views\MyAccount\OrderDetail.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\MyAccount\OrderDetail.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\MyAccount\OrderDetail.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\MyAccount\OrderDetail.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MyAccount/OrderDetail.cshtml")]
    public partial class _Views_MyAccount_OrderDetail_cshtml : System.Web.Mvc.WebViewPage<MyAccountViewModel>
    {
        public _Views_MyAccount_OrderDetail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"details container-fluid g-b-b-1\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row g-m-t-10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"text-left col-md-6\"");

WriteLiteral(">\r\n            <strong>Your Items <span");

WriteLiteral(" class=\"g-fc-s\"");

WriteLiteral(">((");

            
            #line 12 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                 Write(Html.Raw(Model.Order.OrderLines.Count(x => !x.IsVoucher && !x.IsDelivery)));

            
            #line default
            #line hidden
WriteLiteral(")</span></strong>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"text-center col-sm-3 visible-lg\"");

WriteLiteral(">\r\n                        <strong>Price</strong>\r\n                    </div>\r\n  " +
"                  <div");

WriteLiteral(" class=\"text-center col-sm-3 visible-lg\"");

WriteLiteral(">\r\n                        <strong>Quantity</strong>\r\n                    </div>\r" +
"\n                    <div");

WriteLiteral(" class=\"text-center col-sm-3 visible-lg\"");

WriteLiteral(">\r\n                        <strong>Sub-Total</strong>\r\n                    </div>" +
"\r\n                    <div");

WriteLiteral(" class=\"text-center col-sm-3 visible-lg\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-info-circle\"");

WriteLiteral("\r\n                           data-toggle=\"tooltip\"");

WriteLiteral("\r\n                           data-placement=\"bottom\"");

WriteLiteral("\r\n                           title=\"Prices shown may have changed since last orde" +
"r.\"");

WriteLiteral(">\r\n                        </i>\r\n                        <strong>Reorder</strong>" +
"\r\n                    </div>\r\n                </div>\r\n            </div>\r\n      " +
"  </div>\r\n    </div>\r\n");

            
            #line 38 "..\..\Views\MyAccount\OrderDetail.cshtml"
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\MyAccount\OrderDetail.cshtml"
      
        foreach (OrderLine ol in Model.Order.OrderLines)
        {
            if (!ol.IsVoucher && !ol.IsDelivery && !string.IsNullOrEmpty(ol.Description))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row g-b-b-1d g-p-tb-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" class=\"g-b-1-p g-p-10 g-w-100\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1924), Tuple.Create("\"", 1942)
            
            #line 47 "..\..\Views\MyAccount\OrderDetail.cshtml"
, Tuple.Create(Tuple.Create("", 1930), Tuple.Create<System.Object, System.Int32>(ol.ImageUrl
            
            #line default
            #line hidden
, 1930), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 1943), Tuple.Create("\"", 1964)
            
            #line 47 "..\..\Views\MyAccount\OrderDetail.cshtml"
            , Tuple.Create(Tuple.Create("", 1949), Tuple.Create<System.Object, System.Int32>(ol.Description
            
            #line default
            #line hidden
, 1949), false)
);

WriteAttribute("onerror", Tuple.Create(" onerror=\"", 1965), Tuple.Create("\"", 2047)
, Tuple.Create(Tuple.Create("", 1975), Tuple.Create("this.src", 1975), true)
, Tuple.Create(Tuple.Create(" ", 1983), Tuple.Create("=", 1984), true)
, Tuple.Create(Tuple.Create(" ", 1985), Tuple.Create("\'", 1986), true)
            
            #line 47 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 1987), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1987), false)
, Tuple.Create(Tuple.Create("", 2027), Tuple.Create("/Images/noimage.jpg\'", 2027), true)
);

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"pull-left g-p-l-20 g-w-190 g-w-250-sm\"");

WriteLiteral(" style=\"overflow-wrap: break-word\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"g-flex-column g-h-100\"");

WriteLiteral(">\r\n                                <div>\r\n");

WriteLiteral("                                    ");

            
            #line 53 "..\..\Views\MyAccount\OrderDetail.cshtml"
                               Write(Html.ActionLink(ol.Description, "Index", "Product", new { productname = "", id = ol.Reference }, new { @class = "secondary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"g-fs-sm g-m-t-10 hidden-xs\"");

WriteLiteral(">\r\n                                    <strong>Order Code: </strong>");

            
            #line 56 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                            Write(ol.AltRef);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"g-fc-st text-center g-m-t-a g-fs-sm g-lh-20\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 59 "..\..\Views\MyAccount\OrderDetail.cshtml"
                               Write(Html.ProductAvailability(ol.Availability, Convert.ToBoolean(Model.CommonData["DeliveryDateIsOverridden"].ToString()), true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                    <di" +
"v");

WriteLiteral(" class=\"col-lg-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"text-center col-sm-3 visible-lg\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                                        Write(ol.PriceNet.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                <div");

WriteLiteral(" class=\"text-center col-sm-3 visible-lg\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                                        Write(ol.Quantity.ToString("#,##0"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                <div");

WriteLiteral(" class=\"text-center col-sm-3 hidden-xs\"");

WriteLiteral(">");

            
            #line 69 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                                       Write(ol.SubTotal.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                <div");

WriteLiteral(" class=\"text-center text-right-sm col-md-3 col-xs-12 atb-entry\"");

WriteLiteral(">\r\n");

            
            #line 71 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                     if (ol.IsDiscontinued)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        ");

WriteLiteral("Discontinued Item\r\n");

            
            #line 74 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                                }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <button");

WriteLiteral(" class=\"atb-add btn g-butt-second-reg g-butt-md-2 g-m-t-10\"");

WriteLiteral("\r\n                                                role=\"button\"");

WriteLiteral("\r\n                                                data-price=\"0\"");

WriteLiteral("\r\n                                                data-productid=\"");

            
            #line 80 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                           Write(ol.Reference);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                data-partno=\"");

            
            #line 81 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                        Write(ol.AltRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                data-imageurl=\"");

            
            #line 82 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                          Write(ConfigurationManager.AppSettings["CDN"]);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 82 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                                                                   Write(ol.ImageUrl);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                data-desc=\"");

            
            #line 83 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                      Write(ol.Description);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                            Reorder\r\n                         " +
"               </button>\r\n");

            
            #line 86 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n                            </div>\r\n     " +
"                   </div>\r\n                    </div>\r\n                </div>\r\n");

            
            #line 92 "..\..\Views\MyAccount\OrderDetail.cshtml"
            }
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-4 g-m-tb-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-b-1-p\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"g-b-b-1 g-p-10\"");

WriteLiteral(">\r\n                    <strong>Billing Address</strong>\r\n                </div>\r\n" +
"                <div");

WriteLiteral(" class=\"g-p-10 g-h-150\"");

WriteLiteral(">\r\n                    <div>");

            
            #line 102 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.BillingAddress.Line1);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 103 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.BillingAddress.Line2);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 104 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.BillingAddress.Line3);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 105 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.BillingAddress.Line4);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 106 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.BillingAddress.Line5);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 107 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.BillingAddress.PostCode);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-lg-4 g-m-tb-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-b-1-p\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"g-b-b-1 g-p-10\"");

WriteLiteral(">\r\n                    <strong>Delivery Address</strong>\r\n                </div>\r" +
"\n                <div");

WriteLiteral(" class=\"g-p-10 g-h-150\"");

WriteLiteral(">\r\n                    <div>");

            
            #line 117 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.DeliveryAddress.Line1);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 118 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.DeliveryAddress.Line2);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 119 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.DeliveryAddress.Line3);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 120 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.DeliveryAddress.Line4);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 121 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.DeliveryAddress.Line5);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div>");

            
            #line 122 "..\..\Views\MyAccount\OrderDetail.cshtml"
                    Write(Model.Order.DeliveryAddress.PostCode);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-lg-4 g-m-tb-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>Delivery</strong>\r\n                </div>\r\n       " +
"         <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">&pound;");

            
            #line 131 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                          Write(Model.Order.TotalDel.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n");

            
            #line 133 "..\..\Views\MyAccount\OrderDetail.cshtml"
            
            
            #line default
            #line hidden
            
            #line 133 "..\..\Views\MyAccount\OrderDetail.cshtml"
             if (Model.Order.TotalVoucher != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"clearfix g-m-t-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                        <strong>Voucher</strong>\r\n                    </div>\r\n" +
"                    <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">&pound;");

            
            #line 139 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                              Write(Model.Order.TotalVoucher.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n");

            
            #line 141 "..\..\Views\MyAccount\OrderDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"clearfix g-m-t-10\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>Sub-Total</strong>\r\n                </div>\r\n      " +
"          <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">&pound;");

            
            #line 146 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                          Write(Model.Order.AccTotal.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix g-m-t-10\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                    <strong>VAT</strong>\r\n                </div>\r\n            " +
"    <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">&pound;");

            
            #line 152 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                          Write(Model.Order.TotalVat.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n            <hr");

WriteLiteral(" class=\"g-m-t-10\"");

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"clearfix g-m-t-15\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left g-lh-35\"");

WriteLiteral(">\r\n                    <strong>Grand Total</strong>\r\n                </div>\r\n    " +
"            <div");

WriteLiteral(" class=\"pull-right g-fs-lg\"");

WriteLiteral(">\r\n                    <strong>&pound;");

            
            #line 160 "..\..\Views\MyAccount\OrderDetail.cshtml"
                              Write(Model.Order.Total.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"g-m-t-15\"");

WriteLiteral(">\r\n");

            
            #line 164 "..\..\Views\MyAccount\OrderDetail.cshtml"
                
            
            #line default
            #line hidden
            
            #line 164 "..\..\Views\MyAccount\OrderDetail.cshtml"
                 if (Model.Order.InvoiceExists)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"btn g-butt-primary g-butt-100p\"");

WriteAttribute("href", Tuple.Create(" href=\"", 8200), Tuple.Create("\"", 8298)
, Tuple.Create(Tuple.Create("", 8207), Tuple.Create("//", 8207), true)
            
            #line 166 "..\..\Views\MyAccount\OrderDetail.cshtml"
, Tuple.Create(Tuple.Create("", 8209), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 8209), false)
, Tuple.Create(Tuple.Create("", 8249), Tuple.Create("/media/archive/INV", 8249), true)
            
            #line 166 "..\..\Views\MyAccount\OrderDetail.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 8267), Tuple.Create<System.Object, System.Int32>(Model.Order.OrderNumber
            
            #line default
            #line hidden
, 8267), false)
, Tuple.Create(Tuple.Create("", 8293), Tuple.Create("A.pdf", 8293), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" download>Download Invoice</a>\r\n");

            
            #line 167 "..\..\Views\MyAccount\OrderDetail.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span>There is no invoice for this order.</span>\r\n");

            
            #line 171 "..\..\Views\MyAccount\OrderDetail.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
