#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    
    #line 2 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using System.Web.Configuration;
    
    #line default
    #line hidden
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    #line 5 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    
    #line 6 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 3 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LayoutCheckout.cshtml")]
    public partial class _Views_Shared__LayoutCheckout_cshtml : System.Web.Mvc.WebViewPage<CommonViewModel>
    {
        public _Views_Shared__LayoutCheckout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Shared\_LayoutCheckout.cshtml"
  
    int sessionTimeout = (Session.Timeout > 1 ? Session.Timeout - 1 : 1) * 60;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-cache, no-store, must-revalidate\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Pragma\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Expires\"");

WriteLiteral(" content=\"0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"refresh\"");

WriteAttribute("content", Tuple.Create(" content=\"", 691), Tuple.Create("\"", 766)
            
            #line 23 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 701), Tuple.Create<System.Object, System.Int32>(sessionTimeout.ToString()
            
            #line default
            #line hidden
, 701), false)
, Tuple.Create(Tuple.Create("", 727), Tuple.Create(";", 727), true)
, Tuple.Create(Tuple.Create(" ", 728), Tuple.Create("URL=/checkout?pm=SessionExpired&sz=md", 729), true)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"format-detection\"");

WriteLiteral(" content=\"telephone=no\"");

WriteLiteral(">\r\n    <title>");

            
            #line 25 "..\..\Views\Shared\_LayoutCheckout.cshtml"
      Write(Html.RawFromDict(Model.MetaData, "Title"));

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 920), Tuple.Create("\"", 978)
            
            #line 26 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 930), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Description")
            
            #line default
            #line hidden
, 930), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"msvalidate.01\"");

WriteLiteral(" content=\"25C06F8BDF2376F495D44F19998FAE5F\"");

WriteLiteral(">\r\n\r\n    <meta");

WriteLiteral(" property=\"og:title\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1089), Tuple.Create("\"", 1141)
            
            #line 29 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1099), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Title")
            
            #line default
            #line hidden
, 1099), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:type\"");

WriteLiteral(" content=\"website\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:image\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1223), Tuple.Create("\"", 1294)
            
            #line 31 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1233), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1233), false)
, Tuple.Create(Tuple.Create("", 1273), Tuple.Create(")/images/soc-logo.png", 1273), true)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:image:width\"");

WriteLiteral(" content=\"1200\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:image:height\"");

WriteLiteral(" content=\"630\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:url\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1431), Tuple.Create("\"", 1492)
, Tuple.Create(Tuple.Create("", 1441), Tuple.Create("//", 1441), true)
            
            #line 34 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1443), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 1443), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:site_name\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1529), Tuple.Create("\"", 1586)
            
            #line 35 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1539), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SiteName")
            
            #line default
            #line hidden
, 1539), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1625), Tuple.Create("\"", 1683)
            
            #line 36 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1635), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Description")
            
            #line default
            #line hidden
, 1635), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:title\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1717), Tuple.Create("\"", 1769)
            
            #line 37 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1727), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Title")
            
            #line default
            #line hidden
, 1727), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:card\"");

WriteLiteral(" content=\"summary_large_image\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1871), Tuple.Create("\"", 1929)
            
            #line 39 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1881), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Description")
            
            #line default
            #line hidden
, 1881), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:image\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1963), Tuple.Create("\"", 2033)
            
            #line 40 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 1973), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1973), false)
, Tuple.Create(Tuple.Create("", 2013), Tuple.Create("/images/soc-logo.jpg", 2013), true)
);

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"https://fonts.googleapis.com/css?family=Asap:400,400i,700,700i&display=swa" +
"p\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"preload\"");

WriteLiteral(" as=\"font\"");

WriteLiteral(" crossorigin");

WriteLiteral(" type=\"font/woff2\"");

WriteLiteral(" href=\"/fonts/fontawesome-webfont.woff2?v=4.7.0\"");

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2299), Tuple.Create("\"", 2378)
, Tuple.Create(Tuple.Create("", 2306), Tuple.Create("//", 2306), true)
            
            #line 45 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 2308), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 2308), false)
, Tuple.Create(Tuple.Create("", 2357), Tuple.Create("touch-icon-iphone.png", 2357), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"76x76\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2430), Tuple.Create("\"", 2507)
, Tuple.Create(Tuple.Create("", 2437), Tuple.Create("//", 2437), true)
            
            #line 46 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 2439), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 2439), false)
, Tuple.Create(Tuple.Create("", 2488), Tuple.Create("touch-icon-ipad.png", 2488), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"120x120\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2561), Tuple.Create("\"", 2647)
, Tuple.Create(Tuple.Create("", 2568), Tuple.Create("//", 2568), true)
            
            #line 47 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 2570), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 2570), false)
, Tuple.Create(Tuple.Create("", 2619), Tuple.Create("touch-icon-iphone-retina.png", 2619), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"152x152\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2701), Tuple.Create("\"", 2785)
, Tuple.Create(Tuple.Create("", 2708), Tuple.Create("//", 2708), true)
            
            #line 48 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 2710), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 2710), false)
, Tuple.Create(Tuple.Create("", 2759), Tuple.Create("touch-icon-ipad-retina.png", 2759), true)
);

WriteLiteral(" />\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2802), Tuple.Create("\"", 2862)
            
            #line 50 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 2809), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "GooglePlusPage")
            
            #line default
            #line hidden
, 2809), false)
);

WriteLiteral(" rel=\"publisher\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" type=\"application/ld+json\"");

WriteLiteral(">\r\n        [\r\n");

WriteLiteral("        ");

            
            #line 54 "..\..\Views\Shared\_LayoutCheckout.cshtml"
   Write(Html.RawFromDict(Model.CommonData, "Nap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ]\r\n    </script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 58 "..\..\Views\Shared\_LayoutCheckout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Shared\_LayoutCheckout.cshtml"
          
            Html.RenderPartial("~/Views/Shared/JSTrackingAllHdr.cshtml", Model);
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 63 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(RenderSection("AddScript", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 65 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(Styles.Render("~/Content/cssBundle.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 66 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(RenderSection("AddTags", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 67 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(Scripts.Render("~/bundles/jqueryBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"g-ps-r\"");

WriteLiteral(">\r\n\r\n    <section");

WriteLiteral(" class=\"navbar navbar-inverse visible-xs visible-sm\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"mobile-menu\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle pull-left\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n                <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"/Content/Images/1pxTrans.png\"");

WriteLiteral(" class=\"msp_siteLogo visible-xs-inline visible-sm-inline navbar-brand g-m-t-10\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 4043), Tuple.Create("\"", 4096)
            
            #line 81 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                                                                , Tuple.Create(Tuple.Create("", 4049), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SiteName")
            
            #line default
            #line hidden
, 4049), false)
);

WriteLiteral(" />\r\n                </a>\r\n            </div>\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4160), Tuple.Create("\"", 4275)
, Tuple.Create(Tuple.Create("", 4168), Tuple.Create("navbar-collapse", 4168), true)
, Tuple.Create(Tuple.Create(" ", 4183), Tuple.Create("collapse", 4184), true)
, Tuple.Create(Tuple.Create(" ", 4192), Tuple.Create("g-ps-a", 4193), true)
            
            #line 84 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create(" ", 4199), Tuple.Create<System.Object, System.Int32>(Authentication.IsAuthenticated() ? "authenticated" : "not-authenticated"
            
            #line default
            #line hidden
, 4200), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 85 "..\..\Views\Shared\_LayoutCheckout.cshtml"
           Write(Html.Raw(Model.Menu));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </section>\r\n    <section");

WriteLiteral(" class=\"container hidden-xs hidden-sm\"");

WriteLiteral(" id=\"checkout-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row g-m-t-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"clearfix g-d-t\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"clearfix g-w-360 g-va-t\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" src=\"/Content/Images/1pxTrans.png\"");

WriteLiteral(" class=\"msp_siteLogo img-responsive\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 4763), Tuple.Create("\"", 4816)
            
            #line 95 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                             , Tuple.Create(Tuple.Create("", 4769), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SiteName")
            
            #line default
            #line hidden
, 4769), false)
);

WriteLiteral(" />\r\n                        </a>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"clearfix g-fc-s g-va-t\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"g-fw-b g-m-t-5\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-xs-4 text-left\"");

WriteLiteral(">Delivery</div>\r\n                            <div");

WriteLiteral(" class=\"col-xs-4 text-center\"");

WriteLiteral(">Billing &amp; Payment</div>\r\n                            <div");

WriteLiteral(" class=\"col-xs-4 text-right\"");

WriteLiteral(">Complete</div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"g-d-t g-ps-r g-p-t-10\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"g-w-33p\"");

WriteLiteral(">\r\n                                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5416), Tuple.Create("\"", 5461)
, Tuple.Create(Tuple.Create("", 5424), Tuple.Create("cohead-stage", 5424), true)
, Tuple.Create(Tuple.Create(" ", 5436), Tuple.Create("g-m-l-20", 5437), true)
            
            #line 106 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create(" ", 5445), Tuple.Create<System.Object, System.Int32>(ViewBag.Stage1
            
            #line default
            #line hidden
, 5446), false)
);

WriteLiteral("></div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"g-w-33p\"");

WriteLiteral(">\r\n                                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5594), Tuple.Create("\"", 5639)
, Tuple.Create(Tuple.Create("", 5602), Tuple.Create("cohead-stage", 5602), true)
, Tuple.Create(Tuple.Create(" ", 5614), Tuple.Create("g-m-lr-a", 5615), true)
            
            #line 109 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create(" ", 5623), Tuple.Create<System.Object, System.Int32>(ViewBag.Stage2
            
            #line default
            #line hidden
, 5624), false)
);

WriteLiteral("></div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"g-w-33p\"");

WriteLiteral(">\r\n                                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5772), Tuple.Create("\"", 5828)
, Tuple.Create(Tuple.Create("", 5780), Tuple.Create("cohead-stage", 5780), true)
, Tuple.Create(Tuple.Create(" ", 5792), Tuple.Create("g-m-r-20", 5793), true)
, Tuple.Create(Tuple.Create(" ", 5801), Tuple.Create("pull-right", 5802), true)
            
            #line 112 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create(" ", 5812), Tuple.Create<System.Object, System.Int32>(ViewBag.Stage3
            
            #line default
            #line hidden
, 5813), false)
);

WriteLiteral("></div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"cohead-connect g-bc-secondary\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"        <div");

WriteLiteral(" class=\"clearfix g-w-200 text-right g-va-b\"");

WriteLiteral(">\r\n");

            
            #line 118 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                         if (ViewBag.AllowEdit == true)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"btn g-butt-second-reg g-butt-lg g-m-b-15\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6246), Tuple.Create("\"", 6255)
, Tuple.Create(Tuple.Create("", 6253), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 6253), false)
);

WriteLiteral(" role=\"button\"");

WriteLiteral(">Continue Shopping</a>\r\n");

            
            #line 121 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </div>\r\n        <" +
"/div>\r\n    </section>\r\n\r\n");

WriteLiteral("    ");

            
            #line 128 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <footer");

WriteLiteral(" class=\"text-left\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-12 payment-container text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 135 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                   Write(Html.RawFromDict(Model.CommonData, "FooterPartners"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <hr />\r\n                </div>\r\n            </div>\r\n      " +
"      <div");

WriteLiteral(" class=\"row legal-text text-center\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 147 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 147 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                          
                            Dictionary<string, string> replacements = new Dictionary<string, string>();
                            replacements.Add("[Year]", DateTime.Now.Year.ToString());
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 151 "..\..\Views\Shared\_LayoutCheckout.cshtml"
                    Write(Html.RawFromDict(Model.CommonData, "FooterCopyright", replacements));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </footer>\r\n\r\n    <section");

WriteLiteral(" class=\"g-ps-f g-btm-50 hidden-xs hidden-sm\"");

WriteLiteral(">\r\n");

            
            #line 159 "..\..\Views\Shared\_LayoutCheckout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 159 "..\..\Views\Shared\_LayoutCheckout.cshtml"
         if (ConfigurationManager.AppSettings["ChatIsOn"] == "True")
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"lhnChatButton\"");

WriteLiteral(" id=\"lhnChatButton1\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 162 "..\..\Views\Shared\_LayoutCheckout.cshtml"
           Write(Html.Hidden("liveagent_id", Html.RawFromDict(Model.CommonData, "LiveChatID")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 164 "..\..\Views\Shared\_LayoutCheckout.cshtml"
        }            

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"ft_gcs\"");

WriteLiteral("></div>\r\n    </section>\r\n\r\n");

WriteLiteral("    ");

            
            #line 168 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(Scripts.Render("~/bundles/bootstrapBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 169 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(Scripts.Render("~/bundles/jqueryvalBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 171 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 171 "..\..\Views\Shared\_LayoutCheckout.cshtml"
     if (ConfigurationManager.AppSettings["ChatIsOn"] == "True")
    {

            
            #line default
            #line hidden
WriteLiteral("        <!--script type=\"text/javascript\" src=\"https://c.la2w2.salesforceliveagen" +
"t.com/content/g/js/30.0/deployment.js\"></script-->\r\n");

WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8286), Tuple.Create("\"", 8387)
, Tuple.Create(Tuple.Create("", 8292), Tuple.Create("https://", 8292), true)
            
            #line 174 "..\..\Views\Shared\_LayoutCheckout.cshtml"
, Tuple.Create(Tuple.Create("", 8300), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 8300), false)
, Tuple.Create(Tuple.Create("", 8351), Tuple.Create("data/static-files/cpy_sfliveagent.js", 8351), true)
);

WriteLiteral("></script>\r\n");

            
            #line 175 "..\..\Views\Shared\_LayoutCheckout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 177 "..\..\Views\Shared\_LayoutCheckout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 177 "..\..\Views\Shared\_LayoutCheckout.cshtml"
          
            Html.RenderPartial("~/Views/Shared/JSTrackingAll.cshtml", Model);

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 180 "..\..\Views\Shared\_LayoutCheckout.cshtml"
           Write(Html.RawFromDict(Model.CommonData, "MessageAndRedirect"));

            
            #line default
            #line hidden
WriteLiteral(";\r\n            ");

WriteLiteral("\r\n");

            
            #line 182 "..\..\Views\Shared\_LayoutCheckout.cshtml"
        
            
            #line default
            #line hidden
WriteLiteral("\r\n</script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 185 "..\..\Views\Shared\_LayoutCheckout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
