#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\BasketSummary.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 8 "..\..\Views\Shared\BasketSummary.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\BasketSummary.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\BasketSummary.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 5 "..\..\Views\Shared\BasketSummary.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\BasketSummary.cshtml"
    using DataAccess.EntityFramework;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\BasketSummary.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\BasketSummary.cshtml"
    using VmVoucherType = VMerchantWrapper.Entities.VoucherType;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/BasketSummary.cshtml")]
    public partial class _Views_Shared_BasketSummary_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_BasketSummary_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 9 "..\..\Views\Shared\BasketSummary.cshtml"
  
    var bt = (BasketTotals)Session["B_BasketTotals"];
    Tuple<string, decimal> summPrice = Utilities.SetPrice(bt.GrandTotalIncVat, bt.GrandTotalExcVat);

    List<BasketContents> lbc = Utilities.LoadSession<List<BasketContents>>("B_BasketArray");

    bool isVatExempt = HttpContext.Current.Session["D_IsVatExempt"] != null && Convert.ToBoolean(HttpContext.Current.Session["D_IsVatExempt"]);
    decimal vatMultiplier = Convert.ToDecimal(ConfigurationManager.AppSettings["VatMultiplier"]);
    bool hasSwitchProducts = false;
    decimal basketSwitchSaving = 0;
    List<BasketContents> switchProducts = new List<BasketContents>();
    bool isAdminDiscount = false;//Model.BasketContents.Exists(x => x.ItemType == BasketItemType.AdminDiscount);
    bool isCompatibleDiscount = false;// Model.BasketContents.Exists(x => x.ItemType == BasketItemType.CompatibleDiscount);
    int switchCount = 0;

    bool isTradeCustomer = HttpContext.Current.Session["U_IsTradeCustomer"] != null && Convert.ToBoolean(HttpContext.Current.Session["U_IsTradeCustomer"]);
    // (17:30 Mon-Thu, 17:00 Fri), switching to "Free Next Working Day Delivery" after that -
    // this covers Friday evening through the weekend until Monday's cutoff. TG has no spend
    // threshold for free delivery (that's a CartridgeMonkey-only rule).


    DateTime nowLocal = DateTime.Now;
    TimeSpan orderCutoff = nowLocal.DayOfWeek == DayOfWeek.Friday ? new TimeSpan(17, 0, 0) : new TimeSpan(17, 30, 0);
    bool isDeliveryWeekday = nowLocal.DayOfWeek >= DayOfWeek.Monday && nowLocal.DayOfWeek <= DayOfWeek.Friday;
    bool beforeDeliveryCutoff = isDeliveryWeekday && nowLocal.TimeOfDay < orderCutoff;
    string deliveryMessage = beforeDeliveryCutoff ? "Free Next Day Delivery" : "Free Next Working Day Delivery";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n");

WriteLiteral("@media (min-width: 992px) {\r\n.hdr-utility-menu {\r\nbackground-color: rgb(255 255 2" +
"55 / 100%) !important;\r\nbox-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\r\n}\r\n}\r\n:root" +
" {\r\n--dark: #2b2b2b;\r\n--pink: #e6007e;\r\n--green: #00a651;\r\n--border: #e5e5e5;\r\n-" +
"-text: #333;\r\n--muted: #777;\r\n}\r\n.mini-cart {\r\nmax-width: 100%;\r\nmargin: 0 auto;" +
"\r\nbackground: #fff;\r\nborder: 1px solid var(--border);\r\ndisplay: flex;\r\nflex-dire" +
"ction: column;\r\nmax-height: 90vh;\r\n}\r\n\r\n.mini-cart__header {\r\nbackground: var(--" +
"dark);\r\ncolor: #fff;\r\npadding: 14px 16px;\r\ndisplay: flex;\r\nalign-items: center;\r" +
"\njustify-content: space-between;\r\nfont-size: 16px;\r\nfont-weight: 600;\r\n}\r\n\r\n.min" +
"i-cart__close {\r\nbackground: none;\r\nborder: none;\r\ncolor: #fff;\r\nfont-size: 16px" +
";\r\ncursor: pointer;\r\nwidth: 26px;\r\nheight: 26px;\r\nborder: 1px solid #666;\r\nborde" +
"r-radius: 50%;\r\n}\r\n\r\n.mini-cart__body {\r\nflex: 1;\r\noverflow-y: auto;\r\npadding: 1" +
"2px 16px;\r\n}\r\n/* Cart item */\r\n.cart-item {\r\ndisplay: flex;\r\ngap: 10px;\r\npadding" +
": 14px 0;\r\nborder-bottom: 1px solid var(--border);\r\n}\r\n\r\n.cart-item__link {\r\nfle" +
"x-shrink: 0;\r\ndisplay: block;\r\n}\r\n\r\n.cart-item__img {\r\nwidth: 48px;\r\nheight: 48p" +
"x;\r\nobject-fit: contain;\r\nflex-shrink: 0;\r\n}\r\n\r\n.cart-item__details {\r\nflex: 1;\r" +
"\nmin-width: 0;\r\n}\r\n\r\n.cart-item__title {\r\ndisplay: block;\r\nfont-size: 13px;\r\nfon" +
"t-weight: 600;\r\ncolor: var(--text);\r\nmargin: 0 0 6px;\r\nline-height: 1.3;\r\ntext-d" +
"ecoration: none;\r\n}\r\n\r\n.cart-item__title:hover {\r\ncolor: #000;\r\ntext-decoration:" +
" underline;\r\n}\r\n\r\n.cart-item__sku {\r\nfont-size: 11px;\r\ncolor: var(--muted);\r\nmar" +
"gin: 0 0 6px;\r\n}\r\n\r\n.cart-item__price {\r\nfont-size: 17px;\r\nfont-weight: 700;\r\nco" +
"lor: #09c;\r\nmargin: 0;\r\n}\r\n\r\n.cart-item__price .vat {\r\nfont-size: 11px;\r\nfont-we" +
"ight: 400;\r\ncolor: var(--muted);\r\n}\r\n\r\n.cart-item__actions {\r\ndisplay: flex;\r\nfl" +
"ex-direction: column;\r\nalign-items: flex-end;\r\njustify-content: space-between;\r\n" +
"gap: 8px;\r\n}\r\n\r\n.cart-item__remove {\r\nbackground: none;\r\nborder: none;\r\ncursor: " +
"pointer;\r\ncolor: var(--muted);\r\nfont-size: 14px;\r\n}\r\n\r\n.qty-stepper {\r\ndisplay: " +
"flex;\r\nalign-items: center;\r\nborder: 1px solid var(--border);\r\nborder-radius: 4p" +
"x;\r\noverflow: hidden;\r\n}\r\n\r\n.qty-stepper button {\r\nbackground: #fafafa;\r\nborder:" +
" none;\r\nwidth: 24px;\r\nheight: 24px;\r\ncursor: pointer;\r\nfont-size: 14px;\r\nline-he" +
"ight: 1;\r\ncolor: #000000;\r\n}\r\n\r\n.qty-stepper input {\r\nwidth: 28px;\r\ntext-align: " +
"center;\r\nborder: none;\r\nborder-left: 1px solid var(--border);\r\nborder-right: 1px" +
" solid var(--border);\r\nfont-size: 13px;\r\nheight: 24px;\r\ncolor: #000000;\r\n}\r\n/* S" +
"witch & Save */\r\n.switch-save {\r\nborder: 1px solid var(--pink);\r\nborder-radius: " +
"6px;\r\npadding: 14px;\r\nmargin: 10px 0 16px;\r\nposition: relative;\r\n}\r\n\r\n.switch-sa" +
"ve__label {\r\nposition: absolute;\r\ntop: -9px;\r\nleft: 12px;\r\nbackground: #fff;\r\npa" +
"dding: 0 6px;\r\ncolor: var(--pink);\r\nfont-size: 12px;\r\nfont-weight: 700;\r\n}\r\n\r\n.s" +
"witch-save__content {\r\ndisplay: flex;\r\ngap: 10px;\r\n}\r\n\r\n.switch-save__img {\r\nwid" +
"th: 48px;\r\nheight: 48px;\r\nobject-fit: contain;\r\nflex-shrink: 0;\r\n}\r\n\r\n.switch-sa" +
"ve__title {\r\ndisplay: block;\r\nfont-size: 13px;\r\nfont-weight: 600;\r\ncolor: var(--" +
"text);\r\ntext-decoration: none;\r\nmargin: 0 0 4px;\r\n}\r\n\r\n.switch-save__title:hover" +
" {\r\ncolor: var(--pink);\r\ntext-decoration: underline;\r\n}\r\n\r\n.switch-save__sku {\r\n" +
"font-size: 11px;\r\ncolor: var(--muted);\r\nmargin: 0 0 6px;\r\n}\r\n\r\n.switch-save__pri" +
"ce {\r\nfont-size: 14px;\r\nfont-weight: 700;\r\nmargin: 0 0 2px;\r\ncolor: #000000;\r\n}\r" +
"\n\r\n.switch-save__save {\r\nfont-size: 12px;\r\nfont-weight: 700;\r\ncolor: var(--pink)" +
";\r\nmargin: 0 0 10px;\r\n}\r\n\r\n.switch-save__btn {\r\ndisplay: block;\r\nwidth: 100%;\r\nb" +
"ackground: #fff;\r\nborder: 1px solid var(--pink);\r\ncolor: var(--pink);\r\nfont-weig" +
"ht: 700;\r\nfont-size: 13px;\r\npadding: 8px;\r\nborder-radius: 4px;\r\ncursor: pointer;" +
"\r\n}\r\n/* Footer */\r\n.mini-cart__footer {\r\nborder-top: 1px solid var(--border);\r\np" +
"adding: 14px 16px 16px;\r\n}\r\n\r\n.total-row {\r\ndisplay: flex;\r\njustify-content: spa" +
"ce-between;\r\nalign-items: center;\r\nfont-size: 16px;\r\nfont-weight: 700;\r\nmargin-b" +
"ottom: 10px;\r\ncolor: #000000;\r\n}\r\n\r\n.promo {\r\nmargin-bottom: 12px;\r\n}\r\n\r\n.promo " +
"summary {\r\nfont-size: 13px;\r\ncolor: #000;\r\ncursor: pointer;\r\nlist-style: none;\r\n" +
"display: flex;\r\njustify-content: space-between;\r\nalign-items: center;\r\npadding: " +
"4px 0;\r\n}\r\n\r\n.promo summary::-webkit-details-marker {\r\ndisplay: none;\r\n}\r\n\r\n.pro" +
"mo summary::after {\r\ncontent: \"▾\";\r\ntransition: transform .2s;\r\nfont-size: 20px;" +
"\r\n}\r\n\r\n.promo[open] summary::after {\r\ntransform: rotate(180deg);\r\n}\r\n\r\n.promo-fo" +
"rm {\r\ndisplay: flex;\r\ngap: 8px;\r\nmargin-top: 8px;\r\n}\r\n\r\n.promo-form input {\r\nfle" +
"x: 1;\r\nborder: 1px solid var(--border);\r\nborder-radius: 4px;\r\npadding: 8px 10px;" +
"\r\nfont-size: 13px;\r\n}\r\n\r\n.promo-form button {\r\nbackground: var(--green);\r\ncolor:" +
" #fff !important;\r\nborder: none;\r\nborder-radius: 4px;\r\npadding: 8px 16px;\r\nfont-" +
"size: 13px;\r\nfont-weight: 600;\r\ncursor: pointer;\r\n}\r\n\r\n.free-delivery {\r\ndisplay" +
": flex;\r\nalign-items: center;\r\ngap: 6px;\r\nfont-size: 12px;\r\ncolor: var(--green);" +
"\r\nmargin-bottom: 12px;\r\n}\r\n.checkout-btn {\r\ndisplay: block;\r\nwidth: 100%;\r\nbackg" +
"round: var(--green);\r\ncolor: #fff !important;\r\nborder: none;\r\nborder-radius: 4px" +
";\r\npadding: 14px;\r\nfont-size: 15px;\r\nfont-weight: 700;\r\ncursor: pointer;\r\n}\r\n\r\n." +
"checkout-btn:hover {\r\nbackground: #008f45;\r\n}\r\n.sidebar-offcanvas * {\r\ncolor: bl" +
"ack !important;\r\n}\r\n/*16-08-26*/\r\n");

WriteLiteral("@media (min-width: 992px) {\r\n.hdr-utility-menu .navbar-toggle>div {\r\npadding: 0 0" +
"px !important;\r\n}\r\n.hdr-utility-menu .active .header {\r\npadding: 0px 10px !impor" +
"tant;\r\n}\r\n.hdr-utility-menu .active .header span { color:#fff !important; font-s" +
"ize:18px}\r\n.mini-cart__header small {color:#fff !important; font-weight:500 !imp" +
"ortant;}\r\n.mini-cart__header button i {color:#fff !important;  font-weight:500 !" +
"important;}\r\n.free-delivery span {color:#00a651 !important; font-weight:500;}\r\n." +
"free-delivery i {color:#00a651 !important; font-weight:500;}\r\n.stock-status.in-s" +
"tock span, .stock-status.in-stock i {color:#00a651 !important; font-weight:600}\r" +
"\n.stock-status.in-stock span, .stock-status.in-stock i {color:#00a651 !important" +
"; font-weight:600; margin-bottom:8px}\r\n.delivery-cutoff  {color:#262626 !importa" +
"nt; margin-bottom:8px}\r\n.delivery-cutoff i {color:#262626 !important; }\r\n.cart-i" +
"tem__price {color:#09c !important}\r\n.switch-save__price strong {color:#09c !impo" +
"rtant}\r\n.switch-save__save {color:#09c !important; font-size:16px; margin-top:6p" +
"x;}\r\n.cart-item__remove i{ color:#ff0000ad !important; font-size:18px}\r\n.sidebar" +
"-offcanvas .checkout-btn {color: #fff !important;}\r\n.view-basket-link {display:b" +
"lock; text-align:center; margin-top:12px;}\r\n/*.view-basket-link:hover { text-dec" +
"oration:underline}\r\n\r\n    .hdr-utility-menu {\r\n        background-color: transpa" +
"rent !important;\r\n        box-shadow: none !important;\r\n    }\r\n\r\n        .hdr-ut" +
"ility-menu.active {\r\n            background-color: rgb(255 255 255) !important;\r" +
"\n            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15) !important;\r\n        }\r\n" +
"\r\n        .hdr-utility-menu .navbar-toggle .header {\r\n            padding: 0 10p" +
"x !important;\r\n        }\r\n\r\n        .hdr-utility-menu .header {\r\n            bac" +
"kground-color: #069;\r\n        }\r\n\r\n        .hdr-utility-menu .content > * {\r\n   " +
"         width: 100% !important;\r\n        }\r\n\r\n        .hdr-utility-menu .header" +
" span {\r\n            color: #fff !important;\r\n            font-size: 18px;\r\n    " +
"    }\r\n    hdr-utility-menu .navbar-toggle.active .header {\r\n        display: no" +
"ne;\r\n        overflow: hidden\r\n    }\r\n\r\n    .tab-open[data-toggle=\"offcanvas-clo" +
"se\"] {\r\n        display: none!important\r\n    }\r\n\r\n    .hdr-utility-menu .content" +
" > * {\r\n        border: none;\r\n    }\r\n    .navbar-toggle.active > .header {\r\n   " +
"     display: none !important\r\n    }*/\r\n}\r\n</style>\r\n\r\n<div");

WriteLiteral(" id=\"basket\"");

WriteLiteral(" class=\"navbar-toggle offcanvas-toggle collapsed pull-left\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"offcanvas-open\"");

WriteLiteral("\r\n     data-target=\"#utility-bar\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"header g-flex-vcenter\"");

WriteLiteral(" data-label=\"View Basket\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle Basket</span>\r\n        <img");

WriteLiteral(" class=\"msp_basket\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10012), Tuple.Create("\"", 10047)
, Tuple.Create(Tuple.Create("", 10018), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 10018), false)
);

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"g-fs-lg g-p-l-20\"");

WriteLiteral(">Basket</span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"content clearfix\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"mini-cart\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"mini-cart__header\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\" color: white !important; \"");

WriteLiteral(">\r\n                    Summary\r\n                </span>\r\n\r\n                <butto" +
"n");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                        class=\"mini-cart__close\"");

WriteLiteral("\r\n                        data-toggle=\"offcanvas-close\"");

WriteLiteral("\r\n                        data-target=\"#utility-bar\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral("></i>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"mini-cart__body\"");

WriteLiteral(">\r\n");

            
            #line 459 "..\..\Views\Shared\BasketSummary.cshtml"
                
            
            #line default
            #line hidden
            
            #line 459 "..\..\Views\Shared\BasketSummary.cshtml"
                 if (lbc.Count > 0)
                {
                    //bool isAdminDiscount = false;// Model.BasketContents.Exists(y => y.ItemType == BasketItemType.AdminDiscount);
                    //bool isCompatibleDiscount = false;// Model.BasketContents.Exists(x => x.ItemType == BasketItemType.CompatibleDiscount);
                    bool isMultiBuy = false;
                    decimal multibuyAmount = decimal.Zero;
                    // Model.CheckZeroStock();

                    // Logic to build Basket Switch & Save section

                    var list = lbc;
                    if (list != null && list.Count > 1)
                    {
                        foreach (BasketContents item in lbc)
                        {
                            // Ignore non-product lines
                            if (item.ItemType != BasketItemType.Item)
                            { continue; }

                            // Ignore compatible products (already switched)
                            if (item.IsCompatible)
                            { continue; }

                            // Ignore excluded products
                            if (item.ExcludeFromUpSell)
                            { continue; }

                            // Cross-sell product must exist
                            if (item.CrossSellingStockRef == null || item.CrossSellingStockRef == "")
                            {
                                continue;
                            }

                            // Cross-sell product must be in stock
                            if (item.CrossSellingAvailability != 1 &&
                            item.CrossSellingAvailability != 7)
                            { continue; }

                            decimal lineSaving =
                            (item.PriceEx - item.CrossSellingPriceEx) * item.Quantity;

                            // Only show if customer actually saves money
                            if (lineSaving <= 0)
                            { continue; }

                            basketSwitchSaving += lineSaving;
                            switchProducts.Add(item);
                        }
                        hasSwitchProducts = switchProducts.Count > 0;
                        switchCount = switchProducts.Count;
                    }
                    if (hasSwitchProducts && switchCount>1)
                    {



            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"basket-switch-save\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"btn switchsave\"");

WriteLiteral(">\r\n                                Switch &amp; Save\r\n                           " +
" </button>\r\n                            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n\r\n                                Switch &amp; Save\r\n\r\n                       " +
"         <p>\r\n                                    Save £");

            
            #line 523 "..\..\Views\Shared\BasketSummary.cshtml"
                                     Write(string.Format("{0:N2}", basketSwitchSaving));

            
            #line default
            #line hidden
WriteLiteral(" by switching your basket to compatible products.\r\n                              " +
"  </p>\r\n\r\n                            </div>\r\n\r\n                            <div" +
"");

WriteLiteral(" class=\"basket-switch-btn\"");

WriteLiteral(">\r\n\r\n                            </div><button");

WriteLiteral(" id=\"btnSwitchAll\"");

WriteLiteral(" class=\"btn replaceall\"");

WriteLiteral(">\r\n                                Switch All Products\r\n                         " +
"   </button>\r\n\r\n                        </div>\r\n");

            
            #line 535 "..\..\Views\Shared\BasketSummary.cshtml"
                    }
                    foreach (BasketContents bc in list)
                    {
                        if (bc.ItemType == BasketItemType.Item || bc.ItemType == BasketItemType.AdminDiscount)
                        {
                            string neg = bc.ItemType == BasketItemType.AdminDiscount ? "-" : "";
                            string strike = "";
                            string discClass = "g-d-n";
                            decimal discUnitPrice = decimal.Zero;
                            decimal subt = bc.PriceEx * bc.Quantity;
                            decimal discountRate = Utilities.GetUpsellRate();
                            if (!bc.IsCompatible &&
                            !String.IsNullOrEmpty(bc.CrossSellingStockRef) &&
                            !bc.ExcludeFromUpSell &&
                            (bc.CrossSellingAvailability == 1 || bc.CrossSellingAvailability == 7))
                            {
                                decimal lineSaving = (bc.PriceEx - bc.CrossSellingPriceEx) * bc.Quantity;

                                if (lineSaving > 0)
                                {
                                    basketSwitchSaving += lineSaving;
                                    hasSwitchProducts = true;
                                }
                            }
                            if (bc.IsCompatible && Session["V_Voucher"] == null &&
                                Convert.ToBoolean(ConfigurationManager.AppSettings["IsCompatibleUpsellActive"]) &&
                                !Convert.ToBoolean(Session["U_IsTradeCustomer"]) &&
                                !isAdminDiscount &&
                                bc.Quantity > bc.QtyStart)
                            {
                                discUnitPrice = Math.Round(bc.PriceEx, 2) - Math.Round(bc.PriceEx * discountRate / 100, 2);
                                subt = discUnitPrice * bc.Quantity;
                                strike = "g-s";
                                discClass = "";
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <div>\r\n                                <div");

WriteLiteral(" class=\"cart-item atb-entry\"");

WriteLiteral(" data-productid=\"");

            
            #line 571 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                            Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

            
            #line 572 "..\..\Views\Shared\BasketSummary.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 572 "..\..\Views\Shared\BasketSummary.cshtml"
                                      
                                        var productUrl = bc.ProductUrl.StartsWith("/")
                                            ? bc.ProductUrl
                                            : "/" + bc.ProductUrl;
                                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <!-- Product Image -->\r\n                   " +
"                 <a");

WriteAttribute("href", Tuple.Create(" href=\"", 16663), Tuple.Create("\"", 16681)
            
            #line 578 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 16670), Tuple.Create<System.Object, System.Int32>(productUrl
            
            #line default
            #line hidden
, 16670), false)
);

WriteLiteral(" class=\"cart-item__link\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 16753), Tuple.Create("\"", 16771)
            
            #line 579 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 16759), Tuple.Create<System.Object, System.Int32>(bc.ImageUrl
            
            #line default
            #line hidden
, 16759), false)
);

WriteAttribute("alt", Tuple.Create("\r\n                                             alt=\"", 16772), Tuple.Create("\"", 16839)
            
            #line 580 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 16824), Tuple.Create<System.Object, System.Int32>(bc.Description
            
            #line default
            #line hidden
, 16824), false)
);

WriteLiteral("\r\n                                             class=\"cart-item__img\"");

WriteAttribute("onerror", Tuple.Create("\r\n                                             onerror=\"", 16909), Tuple.Create("\"", 17036)
, Tuple.Create(Tuple.Create("", 16965), Tuple.Create("this.src=\'", 16965), true)
            
            #line 582 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 16975), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 16975), false)
, Tuple.Create(Tuple.Create("", 17015), Tuple.Create("/Images/noImage.jpg\';", 17015), true)
);

WriteLiteral(" />\r\n                                    </a>\r\n\r\n                                " +
"    <!-- Product Details -->\r\n                                    <div");

WriteLiteral(" class=\"cart-item__details\"");

WriteLiteral(">\r\n\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17262), Tuple.Create("\"", 17280)
            
            #line 588 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 17269), Tuple.Create<System.Object, System.Int32>(productUrl
            
            #line default
            #line hidden
, 17269), false)
);

WriteLiteral(" class=\"cart-item__title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 589 "..\..\Views\Shared\BasketSummary.cshtml"
                                       Write(bc.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </a>\r\n\r\n                               " +
"         <div");

WriteLiteral(" class=\"cart-item__sku\"");

WriteLiteral(">\r\n                                            Product Code: ");

            
            #line 593 "..\..\Views\Shared\BasketSummary.cshtml"
                                                     Write(bc.PartNo);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n\r\n                             " +
"           <div");

WriteLiteral(" class=\"basket-status\"");

WriteLiteral(">\r\n\r\n\r\n                                        </div>\r\n\r\n                        " +
"                <div");

WriteLiteral(" class=\"cart-item__price\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                                            ");

            
            #line 603 "..\..\Views\Shared\BasketSummary.cshtml"
                                       Write(neg);

            
            #line default
            #line hidden
            
            #line 603 "..\..\Views\Shared\BasketSummary.cshtml"
                                           Write(string.Format("{0:N2}", bc.PriceEx));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                            <span");

WriteLiteral(" class=\"vat\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 606 "..\..\Views\Shared\BasketSummary.cshtml"
                                            Write(isTradeCustomer ? "Trade Price, ex VAT" : "Ex VAT");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span>\r\n\r\n");

            
            #line 609 "..\..\Views\Shared\BasketSummary.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 609 "..\..\Views\Shared\BasketSummary.cshtml"
                                             if (discUnitPrice > 0)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"price-saving\"");

WriteLiteral(">\r\n                                                    Save ");

            
            #line 612 "..\..\Views\Shared\BasketSummary.cshtml"
                                                    Write(string.Format("{0:N2}", bc.PriceEx - discUnitPrice));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </div>\r\n");

            
            #line 614 "..\..\Views\Shared\BasketSummary.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n\r\n                             " +
"       </div>\r\n\r\n                                    <!-- Right Actions -->\r\n   " +
"                                 <div");

WriteLiteral(" class=\"cart-item__actions\"");

WriteLiteral(">\r\n\r\n");

            
            #line 623 "..\..\Views\Shared\BasketSummary.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 623 "..\..\Views\Shared\BasketSummary.cshtml"
                                         if (!bc.IsFreeGift)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <button");

WriteLiteral(" class=\"cart-item__remove basket-remove delete\"");

WriteLiteral("\r\n                                                    data-productid=\"");

            
            #line 626 "..\..\Views\Shared\BasketSummary.cshtml"
                                                               Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                    type=\"button\"");

WriteLiteral(">\r\n                                                <i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral("></i>\r\n                                            </button>\r\n");

            
            #line 630 "..\..\Views\Shared\BasketSummary.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"qty-stepper\"");

WriteLiteral(">\r\n\r\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                                                        ");

            
            #line 634 "..\..\Views\Shared\BasketSummary.cshtml"
                                                    Write(bc.Quantity <= 1 ? "disabled" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        onclick=\"changeBasketQt" +
"y(\'");

            
            #line 635 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                             Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 635 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                                             Write(Math.Max(1, bc.Quantity-1));

            
            #line default
            #line hidden
WriteLiteral(")\">\r\n                                                    -\r\n                     " +
"                           </button>\r\n\r\n                                        " +
"        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                                                       readonly");

WriteAttribute("value", Tuple.Create("\r\n                                                       value=\"", 19858), Tuple.Create("\"", 19934)
            
            #line 641 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 19922), Tuple.Create<System.Object, System.Int32>(bc.Quantity
            
            #line default
            #line hidden
, 19922), false)
);

WriteLiteral(" />\r\n\r\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteAttribute("onclick", Tuple.Create("\r\n                                                        onclick=\"", 20011), Tuple.Create("\"", 20127)
, Tuple.Create(Tuple.Create("", 20078), Tuple.Create("changeBasketQty(\'", 20078), true)
            
            #line 644 "..\..\Views\Shared\BasketSummary.cshtml"
 , Tuple.Create(Tuple.Create("", 20095), Tuple.Create<System.Object, System.Int32>(bc.StockRef
            
            #line default
            #line hidden
, 20095), false)
, Tuple.Create(Tuple.Create("", 20107), Tuple.Create("\',", 20107), true)
            
            #line 644 "..\..\Views\Shared\BasketSummary.cshtml"
                , Tuple.Create(Tuple.Create(" ", 20109), Tuple.Create<System.Object, System.Int32>(bc.Quantity+1
            
            #line default
            #line hidden
, 20110), false)
, Tuple.Create(Tuple.Create("", 20126), Tuple.Create(")", 20126), true)
);

WriteLiteral(">\r\n                                                    +\r\n                       " +
"                         </button>\r\n\r\n                                          " +
"  </div>\r\n");

            
            #line 649 "..\..\Views\Shared\BasketSummary.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 651 "..\..\Views\Shared\BasketSummary.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 651 "..\..\Views\Shared\BasketSummary.cshtml"
                                         if (Session["V_Voucher"] != null)
                                        {
                                            VoucherPromo vp = (VoucherPromo)Session["V_Voucher"];

                                            if (bc.IsVoucherQualifyingItem &&
                                                vp.VoucherTypeFk == (int)VmVoucherType.Percentage)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"voucher-applied\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-check-circle\"");

WriteLiteral("></i>\r\n                                                    Voucher Applied\r\n     " +
"                                           </div>\r\n");

            
            #line 662 "..\..\Views\Shared\BasketSummary.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n\r\n                                <" +
"/div>\r\n                                ");

WriteLiteral("\r\n");

            
            #line 673 "..\..\Views\Shared\BasketSummary.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 673 "..\..\Views\Shared\BasketSummary.cshtml"
                                 if (!bc.IsCompatible && !String.IsNullOrEmpty(bc.CrossSellingStockRef) && !bc.ExcludeFromUpSell)
                                {
                                    List<int> inStock = new List<int> { 1, 7 };

                                    if (inStock.Contains(bc.CrossSellingAvailability))
                                    {
                                        decimal switchUnitPriceEx = bc.CrossSellingPriceEx;
                                        decimal switchLinePriceEx = switchUnitPriceEx * bc.Quantity;
                                        decimal switchLinePriceInc = switchLinePriceEx * Model.VatMultiplier;
                                        decimal saving = (bc.PriceEx - switchUnitPriceEx) * bc.Quantity;

                                        if (saving > 0)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"switch-save\"");

WriteLiteral(">\r\n\r\n                                                <span");

WriteLiteral(" class=\"switch-save__label\"");

WriteLiteral(">\r\n                                                    SWITCH &amp; SAVE\r\n       " +
"                                         </span>\r\n\r\n                            " +
"                    <div");

WriteLiteral(" class=\"switch-save__content\"");

WriteLiteral(">\r\n\r\n                                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 23045), Tuple.Create("\"", 23066)
            
            #line 694 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 23052), Tuple.Create<System.Object, System.Int32>(bc.ProductUrl
            
            #line default
            #line hidden
, 23052), false)
);

WriteLiteral(">\r\n\r\n                                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 23132), Tuple.Create("\"", 23227)
            
            #line 696 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 23138), Tuple.Create<System.Object, System.Int32>(!String.IsNullOrEmpty(bc.CrossSellingImageURL) ? bc.CrossSellingImageURL : bc.ImageUrl
            
            #line default
            #line hidden
, 23138), false)
);

WriteAttribute("alt", Tuple.Create("\r\n                                                             alt=\"", 23228), Tuple.Create("\"", 23323)
            
            #line 697 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 23296), Tuple.Create<System.Object, System.Int32>(bc.CrossSellingDescription
            
            #line default
            #line hidden
, 23296), false)
);

WriteLiteral("\r\n                                                             class=\"switch-save" +
"__img\"");

WriteAttribute("onerror", Tuple.Create("\r\n                                                             onerror=\"", 23411), Tuple.Create("\"", 23554)
, Tuple.Create(Tuple.Create("", 23483), Tuple.Create("this.src=\'", 23483), true)
            
            #line 699 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 23493), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 23493), false)
, Tuple.Create(Tuple.Create("", 23533), Tuple.Create("/Images/noImage.jpg\';", 23533), true)
);

WriteLiteral(" />\r\n\r\n                                                    </a>\r\n\r\n              " +
"                                      <div");

WriteLiteral(" style=\"flex:1;\"");

WriteLiteral(">\r\n\r\n                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 23757), Tuple.Create("\"", 23778)
            
            #line 705 "..\..\Views\Shared\BasketSummary.cshtml"
, Tuple.Create(Tuple.Create("", 23764), Tuple.Create<System.Object, System.Int32>(bc.ProductUrl
            
            #line default
            #line hidden
, 23764), false)
);

WriteLiteral("\r\n                                                           class=\"switch-save__" +
"title\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                                                            ");

            
            #line 708 "..\..\Views\Shared\BasketSummary.cshtml"
                                                       Write(bc.CrossSellingDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                                        </a>\r\n\r\n             " +
"                                           <div");

WriteLiteral(" class=\"switch-save__sku\"");

WriteLiteral(">\r\n                                                            Compatible for ");

            
            #line 713 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                      Write(bc.PartNo);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        </div>\r\n\r\n             " +
"                                           <div");

WriteLiteral(" class=\"switch-save__price\"");

WriteLiteral(">\r\n                                                            £");

            
            #line 717 "..\..\Views\Shared\BasketSummary.cshtml"
                                                        Write(string.Format("{0:N2}", switchLinePriceEx));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                            <span");

WriteLiteral(" class=\"vat\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                                ");

            
            #line 719 "..\..\Views\Shared\BasketSummary.cshtml"
                                                            Write(isTradeCustomer ? "Trade Price, ex VAT" : "exc. VAT");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                            </span>\r\n          " +
"                                              </div>\r\n\r\n                        " +
"                                <div");

WriteLiteral(" class=\"switch-save__save\"");

WriteLiteral(">\r\n                                                            Save £");

            
            #line 724 "..\..\Views\Shared\BasketSummary.cshtml"
                                                             Write(string.Format("{0:N2}", saving));

            
            #line default
            #line hidden
WriteLiteral(" ex VAT\r\n                                                        </div>\r\n\r\n      " +
"                                                  <button");

WriteLiteral(" class=\"switch-save__btn atb-replace\"");

WriteLiteral("\r\n                                                                data-productid=" +
"\"");

            
            #line 728 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                           Write(bc.CrossSellingStockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                                data-price=\"");

            
            #line 729 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                       Write(bc.CrossSellingPriceEx);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                                data-removeid=\"" +
"");

            
            #line 730 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                          Write(bc.StockRef);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                                                data-qty=\"");

            
            #line 731 "..\..\Views\Shared\BasketSummary.cshtml"
                                                                     Write(bc.Quantity);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(@">

                                                            Switch Now

                                                        </button>

                                                    </div>

                                                </div>

                                            </div>
");

            
            #line 742 "..\..\Views\Shared\BasketSummary.cshtml"
                                        }
                                    }
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n");

            
            #line 746 "..\..\Views\Shared\BasketSummary.cshtml"

                        }
                        if (bc.ItemType == BasketItemType.CompatibleDiscount)
                        {
                            isMultiBuy = true;
                            multibuyAmount = bc.PriceEx;

                        }
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"mini-cart__footer\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"total-row\"");

WriteLiteral(">\r\n                    <span>Total Payable</span>\r\n\r\n                    <span>\r\n" +
"                        £");

            
            #line 763 "..\..\Views\Shared\BasketSummary.cshtml"
                    Write(bt.GrandTotalIncVat.ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n                </div>\r\n\r\n");

            
            #line 767 "..\..\Views\Shared\BasketSummary.cshtml"
                
            
            #line default
            #line hidden
            
            #line 767 "..\..\Views\Shared\BasketSummary.cshtml"
                 if (Session["B_VoucherCode"].ToSafeString() != "")
                {
                    decimal totalSaving = bt.Voucher + bt.VoucherVat;


            
            #line default
            #line hidden
WriteLiteral("                    <details");

WriteLiteral(" class=\"promo\"");

WriteLiteral(" open=\"open\"");

WriteLiteral(">\r\n\r\n                        <summary>\r\n                            Promotion Cod" +
"e\r\n                        </summary>\r\n\r\n                        <div");

WriteLiteral(" class=\"promo-applied\"");

WriteLiteral(">\r\n\r\n                            <span");

WriteLiteral(" class=\"promo-applied__code\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 780 "..\..\Views\Shared\BasketSummary.cshtml"
                           Write(Session["B_VoucherCode"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                                    class=\"voucher-remove\"");

WriteLiteral("\r\n                                    title=\"Remove voucher code\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral("></i>\r\n                            </button>\r\n\r\n                            <span" +
"");

WriteLiteral(" class=\"promo-applied__saving\"");

WriteLiteral(">\r\n                                -£");

            
            #line 790 "..\..\Views\Shared\BasketSummary.cshtml"
                             Write(Math.Abs(totalSaving).ToString("0.00"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n\r\n                        </div>\r\n\r\n      " +
"              </details>\r\n");

            
            #line 796 "..\..\Views\Shared\BasketSummary.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <details");

WriteLiteral(" class=\"promo\"");

WriteLiteral(">\r\n\r\n                        <summary>\r\n                            Promotion Cod" +
"e\r\n                        </summary>\r\n\r\n                        <div");

WriteLiteral(" class=\"promo-form\"");

WriteLiteral(">\r\n\r\n                            <input");

WriteLiteral(" id=\"voucher-code1\"");

WriteLiteral("\r\n                                   type=\"text\"");

WriteLiteral("\r\n                                   placeholder=\"Enter voucher code\"");

WriteLiteral(" />\r\n\r\n                            <button");

WriteLiteral(" id=\"apply-voucher\"");

WriteLiteral("\r\n                                    type=\"button\"");

WriteLiteral(">\r\n\r\n                                Apply\r\n\r\n                            </butto" +
"n>\r\n\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" id=\"voucher-code-error\"");

WriteLiteral(" class=\"promo-error g-v-h\"");

WriteLiteral("></div>\r\n\r\n                    </details>\r\n");

            
            #line 823 "..\..\Views\Shared\BasketSummary.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"free-delivery\"");

WriteLiteral(">\r\n\r\n                    <i");

WriteLiteral(" class=\"fa fa-truck\"");

WriteLiteral("></i>\r\n\r\n                    <span>\r\n");

WriteLiteral("                        ");

            
            #line 830 "..\..\Views\Shared\BasketSummary.cshtml"
                   Write(deliveryMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n\r\n                </div>\r\n\r\n                <butto" +
"n");

WriteLiteral(" class=\"checkout-btn\"");

WriteLiteral("\r\n                        type=\"button\"");

WriteLiteral("\r\n                        onclick=\"proceedToCheckout()\"");

WriteLiteral(">\r\n\r\n                    Proceed to Checkout\r\n\r\n                </button>\r\n\r\n    " +
"            <a");

WriteLiteral(" href=\"/checkout/\"");

WriteLiteral("\r\n                   class=\"view-basket-link\"");

WriteLiteral(@">

                    View / Edit Basket

                </a>

            </div>
        </div>


    </div>
</div>
<script>
    $(document).ready(function () {
        document.querySelectorAll('.sidebar-offcanvas').forEach(function (el) {
           // el.classList.remove('sidebar-offcanvas');
        });

    });
</script>





");

        }
    }
}
#pragma warning restore 1591
