#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 3 "..\..\Views\Checkout\JSTracking.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 4 "..\..\Views\Checkout\JSTracking.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Checkout\JSTracking.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Checkout\JSTracking.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Checkout\JSTracking.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/JSTracking.cshtml")]
    public partial class _Views_Checkout_JSTracking_cshtml : System.Web.Mvc.WebViewPage<CheckoutViewModel>
    {

#line 507 "..\..\Views\Checkout\JSTracking.cshtml"
public System.Web.WebPages.HelperResult WriteGoogleTag(
    string Id,
    string Label,
    decimal Price)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 511 "..\..\Views\Checkout\JSTracking.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, "\r\n    <!-- Adwords event snippet for Order Complete ");


#line 513 "..\..\Views\Checkout\JSTracking.cshtml"
                    WriteTo(__razor_helper_writer, Id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " -->\r\n        <script>\r\n            gtag(\'event\',\r\n                \'conversion\',\r" +
"\n                {\r\n                    \'send_to\': \'AW-");


#line 518 "..\..\Views\Checkout\JSTracking.cshtml"
     WriteTo(__razor_helper_writer, Id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "/");


#line 518 "..\..\Views\Checkout\JSTracking.cshtml"
         WriteTo(__razor_helper_writer, Label);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\',\r\n                    \'value\': ");


#line 519 "..\..\Views\Checkout\JSTracking.cshtml"
WriteTo(__razor_helper_writer, Price.ToString("F2"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ",\r\n                    \'currency\': \'GBP\'\r\n                });\r\n        </script>\r" +
"\n    ");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 524 "..\..\Views\Checkout\JSTracking.cshtml"


#line default
#line hidden
});

#line 524 "..\..\Views\Checkout\JSTracking.cshtml"
}
#line default
#line hidden

        public _Views_Checkout_JSTracking_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Checkout\JSTracking.cshtml"
  
    int websiteId = int.Parse(ConfigurationManager.AppSettings["WebsiteId"].ToString());
    //string trackmethod = "";
    string gaEcommId = "";
    string googleReviewsId = "";
    string adwordsId1 = "";
    string adwordsId2 = "";
    string adwordsId3 = "";
    string adwordsId4 = "";
    string adwordsLabel1 = "";
    string adwordsLabel2 = "";
    string adwordsLabel3 = "";
    string adwordsLabel4 = "";
    string kenshooId1 = "";
    string kenshooId2 = "";
    string kenshooId3 = "";
    string kenshooId4 = "";
    string bingId = "";
    string facebookId = "";
    string affiliateWindowId = "";
    string twitterId = "";
    string linkedInId = "";
    string linkedInConvId = "";

    switch (websiteId)
    {
        case 1:
            {
                gaEcommId = "UA-1727271-1";
                googleReviewsId = "9099197";
                adwordsId1 = "1062996651";      // Tonergiant
                adwordsId2 = "1004936566";      // Tonergiant - Shopping
                adwordsId3 = "929223363";       // Tonergiant IBC
                adwordsLabel1 = "iGPXCPXI6AEQq5Xw-gM";
                adwordsLabel2 = "j6kMCOqHmAMQ9rqY3wM";
                adwordsLabel3 = "shGxCJeN22QQw6WLuwM";
                kenshooId1 = "7667d005-3c55-4261-b83f-c041c23e845b";
                kenshooId2 = "cf2a741e-df38-4338-b145-c00a1fe32199";
                bingId = "4017809";
                facebookId = "1512021432429512";
                affiliateWindowId = "5500";
                twitterId = "ntucn";
                linkedInId = "548697";
                linkedInConvId = "641058";
                break;
            }
        case 2:
            {
                gaEcommId = "UA-788128-1";
                googleReviewsId = "9103257";
                adwordsId1 = "1054433765";      // CartridgeMonkey
                adwordsId2 = "1007814028";      // CartridgeMonkey - Shopping
                adwordsLabel1 = "Xq7aCNfcZxDlw-X2Aw";
                adwordsLabel2 = "aG1HCKTL0wIQjIvI4AM";
                kenshooId1 = "e014d516-1d91-4e97-ac57-7c7de5b5c34f";
                kenshooId2 = "848a8f9e-282c-440d-a7fe-785c83b44ef6";
                kenshooId3 = "30d63788-e18f-4793-af0f-aed24b4e7fd8";
                affiliateWindowId = "808";
                break;
            }
        case 3:
            {
                gaEcommId = "UA-49671214-1";
                googleReviewsId = "";
                adwordsId1 = "1003559772";      // Netgiant - Branded
                adwordsId2 = "1011141398";      // Netgiant - Unbranded
                adwordsId3 = "963271532";       // Netgiant - Shopping
                adwordsId4 = "1004178977";      // Netgiant - IBC
                adwordsLabel1 = "vMdECIT09gIQ3LbE3gM";
                adwordsLabel2 = "W3enCPSki2sQlpaT4gM";
                adwordsLabel3 = "A8riCMbtg1cQ7LapywM";
                adwordsLabel4 = "P4xgCM_k1QIQoZzq3gM";
                kenshooId1 = "b6cf34b1-8ef0-4fc0-afb0-2eb8821587ac";
                kenshooId2 = "a811eb45-0caf-4572-915f-872d16a579ac";
                kenshooId3 = "6a7f1a33-7280-4f88-83ef-6f6a8efd973f";
                kenshooId4 = "b8e96e89-3e24-4d49-9d6c-01e34e52e479";
                facebookId = "988029194576258";
                affiliateWindowId = "6704";
                break;
            }
    }

    // Checkout/Stage3
    if (Html.Controller() == "checkout" && Html.Action() == "stage3")
    {
        // Google Analytics
        if (gaEcommId != "")
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<!-- Google Analytics -->\r\n");

WriteLiteral("            ");

WriteLiteral("<script type=\"text/javascript\">\r\n");

WriteLiteral("            ");

WriteLiteral("\r\n                    var _gaq = _gaq || [];\r\n                    _gaq.push([\'_se" +
"tAccount\', \'");

            
            #line 101 "..\..\Views\Checkout\JSTracking.cshtml"
                                          Write(gaEcommId);

            
            #line default
            #line hidden
WriteLiteral("\']);\r\n                    _gaq.push([\'_trackPageview\']);\r\n                    _ga" +
"q.push([\r\n                        \'_addTrans\',\r\n                        \'");

            
            #line 105 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\',                    // transaction ID - required\r\n                        \'");

            
            #line 106 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(Html.RawFromDict(Model.CommonData, "SiteName").ToString());

            
            #line default
            #line hidden
WriteLiteral("\',   // Store Name – Example Toner Giant\r\n                        \'");

            
            #line 107 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\',          // Ex Vat total - required\r\n                        \'");

            
            #line 108 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(Model.BasketTotals.Vat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\',                       // tax\r\n                        \'");

            
            #line 109 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(Model.BasketTotals.Delivery.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(@"',                  // shipping cost
                        '',                                                             // city
                        '',                                                             // state or province
                        ''                                                              // country
                    ]);
            ");

WriteLiteral("\r\n");

            
            #line 115 "..\..\Views\Checkout\JSTracking.cshtml"

            foreach (BasketContents bc in Model.BasketContents)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n                    _gaq.push([\r\n                        \'_addItem\',\r\n         " +
"               \'");

            
            #line 121 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\', // transaction ID - required\r\n                        \'");

            
            #line 122 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(bc.PartNo);

            
            #line default
            #line hidden
WriteLiteral("\',                               // SKU/code - required\r\n                        " +
"\'");

            
            #line 123 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(bc.Description);

            
            #line default
            #line hidden
WriteLiteral("\',                          // product name\r\n                        \'");

            
            #line 124 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(bc.GroupName);

            
            #line default
            #line hidden
WriteLiteral("\',                            // EBusiness group – Example HP Toner\r\n            " +
"            \'");

            
            #line 125 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(bc.PriceEx.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\',               // unit price ex Vat - required\r\n                        \'");

            
            #line 126 "..\..\Views\Checkout\JSTracking.cshtml"
                    Write(bc.Quantity.ToString());

            
            #line default
            #line hidden
WriteLiteral("\'                   // quantity - required\r\n                    ]);\r\n            " +
"    ");

WriteLiteral("\r\n");

            
            #line 129 "..\..\Views\Checkout\JSTracking.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n\r\n                    _gaq.push([\'_trackTrans\']);         //submits transaction" +
" to the Analytics servers\r\n            ");

WriteLiteral("\r\n");

WriteLiteral("            ");

WriteLiteral("</script>\r\n");

            
            #line 136 "..\..\Views\Checkout\JSTracking.cshtml"
        }


            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("<!-- Google Reviews + Affiliate Window -->\r\n");

            
            #line 139 "..\..\Views\Checkout\JSTracking.cshtml"
        if (!Convert.ToBoolean(HttpContext.Current.Session["U_IsPortalUser"]))
        {
            string awinitems = "";
            string pipe = "";
            string testmode = ConfigurationManager.AppSettings["Environment"] == "Live" ? "0" : "1";
            foreach (BasketContents bc in Model.BasketContents)
            {
                if (!bc.IsDelivery && !bc.IsVoucher)
                {
                    awinitems += pipe + bc.AffiliateCommissionGroup + ":" + ((bc.PriceEx * bc.Quantity) - bc.VoucherAmount).ToString("F2");
                    pipe = "|";
                }
            }
            string awinsaleamount = websiteId == 2 ? Model.BasketTotals.GrandTotalIncVat.ToString("F2") : Model.BasketTotals.GrandTotalExcVat.ToString("F2");


            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<img height=\"0\" width=\"0\" style=\"display:none;\" alt=\"\" src=\"https://www.awin1.com" +
"/sread.img?tt=ns&tv=2&merchant=");

            
            #line 154 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                          Write(affiliateWindowId);

            
            #line default
            #line hidden
WriteLiteral("&amount=");

            
            #line 154 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                      Write(awinsaleamount);

            
            #line default
            #line hidden
WriteLiteral("&ref=");

            
            #line 154 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                            Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("&parts=");

            
            #line 154 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                              Write(awinitems);

            
            #line default
            #line hidden
WriteLiteral("&vc=");

            
            #line 154 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                              Write(Model.CheckoutDetails.VoucherCode);

            
            #line default
            #line hidden
WriteLiteral("&testmode=");

            
            #line 154 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                                                            Write(testmode);

            
            #line default
            #line hidden
WriteLiteral("&cr=GBP\" />\r\n");

            
            #line 155 "..\..\Views\Checkout\JSTracking.cshtml"



            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<script src=\"https://apis.google.com/js/platform.js?onload=renderOptIn\" async def" +
"er></script>\r\n");

WriteLiteral("            ");

WriteLiteral("<script type=\"text/javascript\">\r\n");

            
            #line 159 "..\..\Views\Checkout\JSTracking.cshtml"
            if (googleReviewsId != "")
            {
                //<!-- Google Reviews -->

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(@"
                    window.renderOptIn = function () {
                        window.gapi.load('surveyoptin',
                            function() {
                                window.gapi.surveyoptin.render({
                                    ""merchant_id"": ");

            
            #line 167 "..\..\Views\Checkout\JSTracking.cshtml"
                                              Write(googleReviewsId);

            
            #line default
            #line hidden
WriteLiteral(",\r\n                                    \"order_id\": \"");

            
            #line 168 "..\..\Views\Checkout\JSTracking.cshtml"
                                             Write(string.IsNullOrEmpty(Model.CheckoutDetails.Reference) ? Model.CheckoutDetails.BackOfficeOrderRef : Model.CheckoutDetails.Reference);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                                    \"email\": \"");

            
            #line 169 "..\..\Views\Checkout\JSTracking.cshtml"
                                         Write(Model.CheckoutDetails.Email);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                                    \"delivery_country\": \"GB\",\r\n              " +
"                      \"estimated_delivery_date\":\r\n                              " +
"          \"");

            
            #line 172 "..\..\Views\Checkout\JSTracking.cshtml"
                                     Write(Convert.ToDateTime(Session["D_StandardDeliveryDate"]).ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                               });\r\n                        });\r\n             " +
"       }\r\n                ");

WriteLiteral("\r\n");

            
            #line 177 "..\..\Views\Checkout\JSTracking.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n                var AWIN = {};\r\n                AWIN.Tracking = {};\r\n          " +
"      AWIN.Tracking.Sale = {};\r\n                AWIN.Tracking.Sale.amount = \"");

            
            #line 182 "..\..\Views\Checkout\JSTracking.cshtml"
                                        Write(awinsaleamount);

            
            #line default
            #line hidden
WriteLiteral("\";  /*** TG & NG Ex VAT Amount , CM Inc VAT ***/\r\n                AWIN.Tracking.S" +
"ale.currency = \"GBP\";\r\n                AWIN.Tracking.Sale.orderRef = \"");

            
            #line 184 "..\..\Views\Checkout\JSTracking.cshtml"
                                          Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                AWIN.Tracking.Sale.parts = \"");

            
            #line 185 "..\..\Views\Checkout\JSTracking.cshtml"
                                       Write(awinitems);

            
            #line default
            #line hidden
WriteLiteral("\";                                            /*** Ebusiness Group Code|Item Pric" +
"e (All Sites Should be ex Vat) ***/\r\n                AWIN.Tracking.Sale.voucher " +
"= \"");

            
            #line 186 "..\..\Views\Checkout\JSTracking.cshtml"
                                         Write(Model.CheckoutDetails.VoucherCode);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                AWIN.Tracking.Sale.test = \"");

            
            #line 187 "..\..\Views\Checkout\JSTracking.cshtml"
                                      Write(testmode);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            ");

WriteLiteral("\r\n");

WriteLiteral("            ");

WriteLiteral("</script>\r\n");

            
            #line 190 "..\..\Views\Checkout\JSTracking.cshtml"
        }

        // Kenshoo
        if (!Convert.ToBoolean(HttpContext.Current.Session["U_IsPortalUser"]))
        {
            int orderCount = Model.BasketContents.FindAll(x => !x.IsDelivery && !x.IsVoucher).Count;
            int compatCount = Model.BasketContents.FindAll(x => !x.IsDelivery && !x.IsVoucher && x.IsCompatible).Count;
            decimal compatRevenue = Model.BasketContents.FindAll(x => !x.IsDelivery && !x.IsVoucher && x.IsCompatible).Sum(x => ((Math.Round(x.PriceInc, 2) * x.Quantity) / Convert.ToDecimal(ConfigurationManager.AppSettings["VatMultiplier"])));
            string newUser = Model.CheckoutDetails.IsNewCustomer ? "New" : "Returning";
            if (kenshooId1 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Kenshoo Main -->\r\n");

WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9951), Tuple.Create("\"", 10014)
, Tuple.Create(Tuple.Create("", 9957), Tuple.Create("https://services.xg4ken.com/js/kenshoo.js?cid=", 9957), true)
            
            #line 203 "..\..\Views\Checkout\JSTracking.cshtml"
                     , Tuple.Create(Tuple.Create("", 10003), Tuple.Create<System.Object, System.Int32>(kenshooId1
            
            #line default
            #line hidden
, 10003), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        kenshoo.trackConversion(\'21\',\r\n                       " +
"     \'");

            
            #line 206 "..\..\Views\Checkout\JSTracking.cshtml"
                        Write(kenshooId1);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            {\r\n                                conversionType" +
": \'conv\',\r\n                                revenue:\r\n");

WriteLiteral("                                    ");

            
            #line 210 "..\..\Views\Checkout\JSTracking.cshtml"
                               Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(", //numeric conversion value. example convValue: 12.34\r\n                         " +
"       currency: \'GBP\',\r\n                                orderId: \'");

            
            #line 212 "..\..\Views\Checkout\JSTracking.cshtml"
                                     Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\', //example orderId: \'TA456\'\r\n                                promoCode: \'");

            
            #line 213 "..\..\Views\Checkout\JSTracking.cshtml"
                                       Write(Model.CheckoutDetails.VoucherCode);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                New_Returning_Customer: \'");

            
            #line 214 "..\..\Views\Checkout\JSTracking.cshtml"
                                                    Write(newUser);

            
            #line default
            #line hidden
WriteLiteral("\', //New or retunring customer, Example \'New\'\r\n                                //" +
"Customer_Order_Count:\'{Current Order Count}\', //Tracks the customer order count," +
" Example \'5\'\r\n                                QTY_Items_Bought: \'");

            
            #line 216 "..\..\Views\Checkout\JSTracking.cshtml"
                                              Write(orderCount);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                QTY_Compatible_Items_Bought: \'");

            
            #line 217 "..\..\Views\Checkout\JSTracking.cshtml"
                                                         Write(compatCount);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                Compatible_Revenue: \'");

            
            #line 218 "..\..\Views\Checkout\JSTracking.cshtml"
                                                Write(compatRevenue.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\'\r\n                            })\r\n                    </script>\r\n\r\n             " +
"       <noscript>\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 11292), Tuple.Create("\"", 11653)
, Tuple.Create(Tuple.Create("", 11298), Tuple.Create("https://21.xg4ken.com/pixel/v1?track=1&token=", 11298), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create("", 11343), Tuple.Create<System.Object, System.Int32>(kenshooId1
            
            #line default
            #line hidden
, 11343), false)
, Tuple.Create(Tuple.Create("", 11356), Tuple.Create("&conversionType=conv&revenue=", 11356), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
                                         , Tuple.Create(Tuple.Create("", 11385), Tuple.Create<System.Object, System.Int32>(Model.BasketTotals.TotalExcVat.ToString("F2")
            
            #line default
            #line hidden
, 11385), false)
, Tuple.Create(Tuple.Create("", 11433), Tuple.Create("&currency=GBP&orderId=", 11433), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 11455), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.BackOfficeOrderRef
            
            #line default
            #line hidden
, 11455), false)
, Tuple.Create(Tuple.Create("", 11498), Tuple.Create("&promoCode=", 11498), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 11509), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.VoucherCode
            
            #line default
            #line hidden
, 11509), false)
, Tuple.Create(Tuple.Create("", 11545), Tuple.Create("&New_Returning_Customer=", 11545), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 11569), Tuple.Create<System.Object, System.Int32>(newUser
            
            #line default
            #line hidden
, 11569), false)
, Tuple.Create(Tuple.Create("", 11579), Tuple.Create("&QTY_Items_Bought=", 11579), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                             , Tuple.Create(Tuple.Create("", 11597), Tuple.Create<System.Object, System.Int32>(orderCount
            
            #line default
            #line hidden
, 11597), false)
, Tuple.Create(Tuple.Create("", 11610), Tuple.Create("&QTY_Compatible_Items_Bought=", 11610), true)
            
            #line 223 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                                                                       , Tuple.Create(Tuple.Create("", 11639), Tuple.Create<System.Object, System.Int32>(compatCount
            
            #line default
            #line hidden
, 11639), false)
);

WriteLiteral(" width=\"1\"");

WriteLiteral(" height=\"1\"");

WriteLiteral(" />\r\n                    </noscript>\r\n                ");

WriteLiteral("\r\n");

            
            #line 226 "..\..\Views\Checkout\JSTracking.cshtml"
            }
            if (kenshooId2 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Kenshoo Shopping -->\r\n");

WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 11922), Tuple.Create("\"", 11985)
, Tuple.Create(Tuple.Create("", 11928), Tuple.Create("https://services.xg4ken.com/js/kenshoo.js?cid=", 11928), true)
            
            #line 231 "..\..\Views\Checkout\JSTracking.cshtml"
                     , Tuple.Create(Tuple.Create("", 11974), Tuple.Create<System.Object, System.Int32>(kenshooId2
            
            #line default
            #line hidden
, 11974), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        kenshoo.trackConversion(\'21\',\r\n                       " +
"     \'");

            
            #line 234 "..\..\Views\Checkout\JSTracking.cshtml"
                        Write(kenshooId2);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            {\r\n                                conversionType" +
": \'conv\',\r\n                                revenue:\r\n");

WriteLiteral("                                    ");

            
            #line 238 "..\..\Views\Checkout\JSTracking.cshtml"
                               Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(", //numeric conversion value. example convValue: 12.34\r\n                         " +
"       currency: \'GBP\',\r\n                                orderId: \'");

            
            #line 240 "..\..\Views\Checkout\JSTracking.cshtml"
                                     Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\', //example orderId: \'TA456\'\r\n                                promoCode: \'");

            
            #line 241 "..\..\Views\Checkout\JSTracking.cshtml"
                                       Write(Model.CheckoutDetails.VoucherCode);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                New_Returning_Customer: \'");

            
            #line 242 "..\..\Views\Checkout\JSTracking.cshtml"
                                                    Write(newUser);

            
            #line default
            #line hidden
WriteLiteral("\', //New or retunring customer, Example \'New\'\r\n                                //" +
"Customer_Order_Count:\'{Current Order Count}\', //Tracks the customer order count," +
" Example \'5\'\r\n                                QTY_Items_Bought: \'");

            
            #line 244 "..\..\Views\Checkout\JSTracking.cshtml"
                                              Write(orderCount);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                QTY_Compatible_Items_Bought: \'");

            
            #line 245 "..\..\Views\Checkout\JSTracking.cshtml"
                                                         Write(compatCount);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                                Compatible_Revenue: \'");

            
            #line 246 "..\..\Views\Checkout\JSTracking.cshtml"
                                                Write(compatRevenue.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\'\r\n                            })\r\n                    </script>\r\n\r\n             " +
"       <noscript>\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 13263), Tuple.Create("\"", 13624)
, Tuple.Create(Tuple.Create("", 13269), Tuple.Create("https://21.xg4ken.com/pixel/v1?track=1&token=", 13269), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create("", 13314), Tuple.Create<System.Object, System.Int32>(kenshooId2
            
            #line default
            #line hidden
, 13314), false)
, Tuple.Create(Tuple.Create("", 13327), Tuple.Create("&conversionType=conv&revenue=", 13327), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
                                         , Tuple.Create(Tuple.Create("", 13356), Tuple.Create<System.Object, System.Int32>(Model.BasketTotals.TotalExcVat.ToString("F2")
            
            #line default
            #line hidden
, 13356), false)
, Tuple.Create(Tuple.Create("", 13404), Tuple.Create("&currency=GBP&orderId=", 13404), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 13426), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.BackOfficeOrderRef
            
            #line default
            #line hidden
, 13426), false)
, Tuple.Create(Tuple.Create("", 13469), Tuple.Create("&promoCode=", 13469), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 13480), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.VoucherCode
            
            #line default
            #line hidden
, 13480), false)
, Tuple.Create(Tuple.Create("", 13516), Tuple.Create("&New_Returning_Customer=", 13516), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 13540), Tuple.Create<System.Object, System.Int32>(newUser
            
            #line default
            #line hidden
, 13540), false)
, Tuple.Create(Tuple.Create("", 13550), Tuple.Create("&QTY_Items_Bought=", 13550), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                             , Tuple.Create(Tuple.Create("", 13568), Tuple.Create<System.Object, System.Int32>(orderCount
            
            #line default
            #line hidden
, 13568), false)
, Tuple.Create(Tuple.Create("", 13581), Tuple.Create("&QTY_Compatible_Items_Bought=", 13581), true)
            
            #line 251 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                                                                       , Tuple.Create(Tuple.Create("", 13610), Tuple.Create<System.Object, System.Int32>(compatCount
            
            #line default
            #line hidden
, 13610), false)
);

WriteLiteral(" width=\"1\"");

WriteLiteral(" height=\"1\"");

WriteLiteral(" />\r\n                    </noscript>\r\n                ");

WriteLiteral("\r\n");

            
            #line 254 "..\..\Views\Checkout\JSTracking.cshtml"
            }
            if (kenshooId3 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Kenshoo IBC -->\r\n");

WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 13888), Tuple.Create("\"", 13951)
, Tuple.Create(Tuple.Create("", 13894), Tuple.Create("https://services.xg4ken.com/js/kenshoo.js?cid=", 13894), true)
            
            #line 259 "..\..\Views\Checkout\JSTracking.cshtml"
                     , Tuple.Create(Tuple.Create("", 13940), Tuple.Create<System.Object, System.Int32>(kenshooId3
            
            #line default
            #line hidden
, 13940), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        kenshoo.trackConversion(\'21\',\r\n                       " +
"     \'");

            
            #line 262 "..\..\Views\Checkout\JSTracking.cshtml"
                        Write(kenshooId3);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            {\r\n                                conversionType" +
": \'conv\',\r\n                                revenue:\r\n");

WriteLiteral("                                    ");

            
            #line 266 "..\..\Views\Checkout\JSTracking.cshtml"
                               Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(", //numeric conversion value. example convValue: 12.34\r\n                         " +
"       currency: \'GBP\',\r\n                                orderId: \'");

            
            #line 268 "..\..\Views\Checkout\JSTracking.cshtml"
                                     Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\', //example orderId: \'TA456\'\r\n                                promoCode: \'");

            
            #line 269 "..\..\Views\Checkout\JSTracking.cshtml"
                                       Write(Model.CheckoutDetails.VoucherCode);

            
            #line default
            #line hidden
WriteLiteral(@"',
                                customParam1: '', /*any custom parameter. example: Airport: 'JFK'*/
                                customParam2: '', /*any custom parameter. example: Rooms: '3'*/
                                customParamN: ''
                            })
                    </script>

                    <noscript>
                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 15008), Tuple.Create("\"", 15369)
, Tuple.Create(Tuple.Create("", 15014), Tuple.Create("https://21.xg4ken.com/pixel/v1?track=1&token=", 15014), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create("", 15059), Tuple.Create<System.Object, System.Int32>(kenshooId3
            
            #line default
            #line hidden
, 15059), false)
, Tuple.Create(Tuple.Create("", 15072), Tuple.Create("&conversionType=conv&revenue=", 15072), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
                                         , Tuple.Create(Tuple.Create("", 15101), Tuple.Create<System.Object, System.Int32>(Model.BasketTotals.TotalExcVat.ToString("F2")
            
            #line default
            #line hidden
, 15101), false)
, Tuple.Create(Tuple.Create("", 15149), Tuple.Create("&currency=GBP&orderId=", 15149), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 15171), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.BackOfficeOrderRef
            
            #line default
            #line hidden
, 15171), false)
, Tuple.Create(Tuple.Create("", 15214), Tuple.Create("&promoCode=", 15214), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 15225), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.VoucherCode
            
            #line default
            #line hidden
, 15225), false)
, Tuple.Create(Tuple.Create("", 15261), Tuple.Create("&New_Returning_Customer=", 15261), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 15285), Tuple.Create<System.Object, System.Int32>(newUser
            
            #line default
            #line hidden
, 15285), false)
, Tuple.Create(Tuple.Create("", 15295), Tuple.Create("&QTY_Items_Bought=", 15295), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                             , Tuple.Create(Tuple.Create("", 15313), Tuple.Create<System.Object, System.Int32>(orderCount
            
            #line default
            #line hidden
, 15313), false)
, Tuple.Create(Tuple.Create("", 15326), Tuple.Create("&QTY_Compatible_Items_Bought=", 15326), true)
            
            #line 277 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                                                                       , Tuple.Create(Tuple.Create("", 15355), Tuple.Create<System.Object, System.Int32>(compatCount
            
            #line default
            #line hidden
, 15355), false)
);

WriteLiteral(" width=\"1\"");

WriteLiteral(" height=\"1\"");

WriteLiteral(" />\r\n                    </noscript>\r\n                ");

WriteLiteral("\r\n");

            
            #line 280 "..\..\Views\Checkout\JSTracking.cshtml"
            }
            if (kenshooId4 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Kenshoo IBC -->\r\n");

WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 15633), Tuple.Create("\"", 15696)
, Tuple.Create(Tuple.Create("", 15639), Tuple.Create("https://services.xg4ken.com/js/kenshoo.js?cid=", 15639), true)
            
            #line 285 "..\..\Views\Checkout\JSTracking.cshtml"
                     , Tuple.Create(Tuple.Create("", 15685), Tuple.Create<System.Object, System.Int32>(kenshooId4
            
            #line default
            #line hidden
, 15685), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        kenshoo.trackConversion(\'21\',\r\n                       " +
"     \'");

            
            #line 288 "..\..\Views\Checkout\JSTracking.cshtml"
                        Write(kenshooId4);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            {\r\n                                conversionType" +
": \'conv\',\r\n                                revenue:\r\n");

WriteLiteral("                                    ");

            
            #line 292 "..\..\Views\Checkout\JSTracking.cshtml"
                               Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(", //numeric conversion value. example convValue: 12.34\r\n                         " +
"       currency: \'GBP\',\r\n                                orderId: \'");

            
            #line 294 "..\..\Views\Checkout\JSTracking.cshtml"
                                     Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\', //example orderId: \'TA456\'\r\n                                promoCode: \'");

            
            #line 295 "..\..\Views\Checkout\JSTracking.cshtml"
                                       Write(Model.CheckoutDetails.VoucherCode);

            
            #line default
            #line hidden
WriteLiteral(@"',
                                customParam1: '', /*any custom parameter. example: Airport: 'JFK'*/
                                customParam2: '', /*any custom parameter. example: Rooms: '3'*/
                                customParamN: ''
                            })
                    </script>

                    <noscript>
                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 16753), Tuple.Create("\"", 17114)
, Tuple.Create(Tuple.Create("", 16759), Tuple.Create("https://21.xg4ken.com/pixel/v1?track=1&token=", 16759), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create("", 16804), Tuple.Create<System.Object, System.Int32>(kenshooId4
            
            #line default
            #line hidden
, 16804), false)
, Tuple.Create(Tuple.Create("", 16817), Tuple.Create("&conversionType=conv&revenue=", 16817), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
                                         , Tuple.Create(Tuple.Create("", 16846), Tuple.Create<System.Object, System.Int32>(Model.BasketTotals.TotalExcVat.ToString("F2")
            
            #line default
            #line hidden
, 16846), false)
, Tuple.Create(Tuple.Create("", 16894), Tuple.Create("&currency=GBP&orderId=", 16894), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 16916), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.BackOfficeOrderRef
            
            #line default
            #line hidden
, 16916), false)
, Tuple.Create(Tuple.Create("", 16959), Tuple.Create("&promoCode=", 16959), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 16970), Tuple.Create<System.Object, System.Int32>(Model.CheckoutDetails.VoucherCode
            
            #line default
            #line hidden
, 16970), false)
, Tuple.Create(Tuple.Create("", 17006), Tuple.Create("&New_Returning_Customer=", 17006), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 17030), Tuple.Create<System.Object, System.Int32>(newUser
            
            #line default
            #line hidden
, 17030), false)
, Tuple.Create(Tuple.Create("", 17040), Tuple.Create("&QTY_Items_Bought=", 17040), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                             , Tuple.Create(Tuple.Create("", 17058), Tuple.Create<System.Object, System.Int32>(orderCount
            
            #line default
            #line hidden
, 17058), false)
, Tuple.Create(Tuple.Create("", 17071), Tuple.Create("&QTY_Compatible_Items_Bought=", 17071), true)
            
            #line 303 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                                                                                       , Tuple.Create(Tuple.Create("", 17100), Tuple.Create<System.Object, System.Int32>(compatCount
            
            #line default
            #line hidden
, 17100), false)
);

WriteLiteral(" width=\"1\"");

WriteLiteral(" height=\"1\"");

WriteLiteral(" />\r\n                    </noscript>\r\n                ");

WriteLiteral("\r\n");

            
            #line 306 "..\..\Views\Checkout\JSTracking.cshtml"
            }
        }

        // Bing
        if (!Convert.ToBoolean(HttpContext.Current.Session["U_IsPortalUser"]))
        {
            if (bingId != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Bing -->\r\n");

WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        (function(w, d, t, r, u) {\r\n                          " +
"  var f, n, i;\r\n                            w[u] = w[u] || [], f = function() {\r" +
"\n                                var o = { ti: \"");

            
            #line 320 "..\..\Views\Checkout\JSTracking.cshtml"
                                           Write(bingId);

            
            #line default
            #line hidden
WriteLiteral(@""" };
                                o.q = w[u], w[u] = new UET(o), w[u].push(""pageLoad"")
                            }, n = d.createElement(t), n.src = r, n.async = 1, n.onload = n.onreadystatechange =
                                function() {
                                    var s = this.readyState;
                                    s && s !== ""loaded"" && s !== ""complete"" ||
                                        (f(), n.onload = n.onreadystatechange = null)
                                }, i = d.getElementsByTagName(t)[0], i.parentNode.insertBefore(n, i)
                        })(window, document, ""script"", ""//bat.bing.com/bat.js"", ""uetq"");

                        var uetq = uetq || [];
                        uetq.push({
                            'gv': ");

            
            #line 332 "..\..\Views\Checkout\JSTracking.cshtml"
                             Write(Model.BasketTotals.GrandTotalIncVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        }); // Compute and pass the computed goal value\r\n\r\n    " +
"                </script>\r\n\r\n                    <noscript>\r\n                   " +
"     <img");

WriteAttribute("src", Tuple.Create(" src=\"", 18721), Tuple.Create("\"", 18827)
, Tuple.Create(Tuple.Create("", 18727), Tuple.Create("//bat.bing.com/action/0?ti=", 18727), true)
            
            #line 338 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create("", 18754), Tuple.Create<System.Object, System.Int32>(bingId
            
            #line default
            #line hidden
, 18754), false)
, Tuple.Create(Tuple.Create("", 18763), Tuple.Create("&Ver=2&gv=", 18763), true)
            
            #line 338 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create(" ", 18773), Tuple.Create<System.Object, System.Int32>(Model.BasketTotals.GrandTotalIncVat.ToString("F2")
            
            #line default
            #line hidden
, 18774), false)
);

WriteLiteral(" height=\"0\"");

WriteLiteral(" width=\"0\"");

WriteLiteral(" style=\"display: none; visibility: hidden;\"");

WriteLiteral(" />\r\n                    </noscript>\r\n                ");

WriteLiteral("\r\n");

            
            #line 341 "..\..\Views\Checkout\JSTracking.cshtml"
            }
        }

        // Social Media
        if (!Convert.ToBoolean(HttpContext.Current.Session["U_IsPortalUser"]))
        {
            if (facebookId != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Facebook -->\r\n");

            
            #line 350 "..\..\Views\Checkout\JSTracking.cshtml"
                StringBuilder sb = new StringBuilder();
                foreach (BasketContents bc in Model.BasketContents)
                {
                    if (bc.IsDelivery == false)
                    {
                        if (sb.Length > 0)
                        {
                            sb.Append(" , ");
                        }
                        sb.Append(bc.PartNo);
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                        !function(f, b, e, v, n, t, s) {
                            if (f.fbq) return;
                            n = f.fbq = function() {
                                n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments)
                            };
                            if (!f._fbq) f._fbq = n;
                            n.push = n;
                            n.loaded = !0;
                            n.version = '2.0';
                            n.queue = [];
                            t = b.createElement(e);
                            t.async = !0;
                            t.src = v;
                            s = b.getElementsByTagName(e)[0];
                            s.parentNode.insertBefore(t, s)
                        }(window,
                            document,
                            'script',
                            '//connect.facebook.net/en_US/fbevents.js');

                        fbq('init', '");

            
            #line 384 "..\..\Views\Checkout\JSTracking.cshtml"
                                Write(facebookId);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                        fbq(\'track\', \"PageView\");\r\n\r\n                       " +
" fbq(\'track\',\r\n                            \'Purchase\',\r\n                        " +
"    {\r\n                                content_ids: [\'");

            
            #line 390 "..\..\Views\Checkout\JSTracking.cshtml"
                                          Write(sb.ToString());

            
            #line default
            #line hidden
WriteLiteral("\'],\r\n                                content_type: \'product\',\r\n                  " +
"              value: ");

            
            #line 392 "..\..\Views\Checkout\JSTracking.cshtml"
                                  Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                                currency: \'GBP\'\r\n                            }" +
");\r\n\r\n                    </script>\r\n                    <noscript>\r\n           " +
"             <img");

WriteLiteral(" height=\"1\"");

WriteLiteral(" width=\"1\"");

WriteLiteral(" style=\"display: none\"");

WriteAttribute("src", Tuple.Create("\r\n                             src=\"", 21343), Tuple.Create("\"", 21444)
, Tuple.Create(Tuple.Create("", 21379), Tuple.Create("https://www.facebook.com/tr?id=", 21379), true)
            
            #line 399 "..\..\Views\Checkout\JSTracking.cshtml"
, Tuple.Create(Tuple.Create("", 21410), Tuple.Create<System.Object, System.Int32>(facebookId
            
            #line default
            #line hidden
, 21410), false)
, Tuple.Create(Tuple.Create("", 21421), Tuple.Create("&ev=PageView&noscript=1", 21421), true)
);

WriteLiteral(" />\r\n                    </noscript>\r\n                ");

WriteLiteral("\r\n");

            
            #line 402 "..\..\Views\Checkout\JSTracking.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<!-- Twitter -->\r\n");

            
            #line 405 "..\..\Views\Checkout\JSTracking.cshtml"
            if (twitterId != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n                    <script");

WriteLiteral(" src=\"//platform.twitter.com/oct.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        //twttr.conversion.trackPid(\'");

            
            #line 410 "..\..\Views\Checkout\JSTracking.cshtml"
                                                Write(twitterId);

            
            #line default
            #line hidden
WriteLiteral("\', { tw_sale_amount: ");

            
            #line 410 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                               Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral(", tw_order_quantity: ");

            
            #line 410 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                       Write(Model.BasketTotals.Quantity);

            
            #line default
            #line hidden
WriteLiteral(@" });

                        !function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments); 
                            },s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js', 
                            a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script'); 
                        // Insert Twitter Pixel ID and Standard Event data below 
                        twq('init','");

            
            #line 416 "..\..\Views\Checkout\JSTracking.cshtml"
                               Write(twitterId);

            
            #line default
            #line hidden
WriteLiteral("\'); \r\n                        twq(\'track\',\'Purchase\', { \r\n                       " +
"     value: \'");

            
            #line 418 "..\..\Views\Checkout\JSTracking.cshtml"
                               Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\', \r\n                            currency: \'GBP\', \r\n                            n" +
"um_items: \'");

            
            #line 420 "..\..\Views\Checkout\JSTracking.cshtml"
                                   Write(Model.BasketTotals.Quantity);

            
            #line default
            #line hidden
WriteLiteral("\', \r\n                            order_id: \'");

            
            #line 421 "..\..\Views\Checkout\JSTracking.cshtml"
                                  Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\' \r\n                        });\r\n                    </script>\r\n                 " +
"   <!--<noscript>\r\n                        <img height=\"1\" width=\"1\" style=\"disp" +
"lay:none;\" alt=\"\" src=\"https://analytics.twitter.com/i/adsct?txn_id=");

            
            #line 425 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                            Write(twitterId);

            
            #line default
            #line hidden
WriteLiteral("&p_id=Twitter&tw_sale_amount=");

            
            #line 425 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                   Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("&tw_order_quantity=");

            
            #line 425 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                                         Write(Model.BasketTotals.Quantity);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        <img height=\"1\" width=\"1\" style=\"display:none;\" alt" +
"=\"\" src=\"//t.co/i/adsct?txn_id=");

            
            #line 426 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                     Write(twitterId);

            
            #line default
            #line hidden
WriteLiteral("&p_id=Twitter&tw_sale_amount=");

            
            #line 426 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                            Write(Model.BasketTotals.GrandTotalExcVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("&tw_order_quantity=");

            
            #line 426 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                                                                                                                                                  Write(Model.BasketTotals.Quantity);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                    </noscript>-->\r\n\r\n                ");

WriteLiteral("\r\n");

            
            #line 430 "..\..\Views\Checkout\JSTracking.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<!-- LinkedIn -->\r\n");

            
            #line 433 "..\..\Views\Checkout\JSTracking.cshtml"
            if (linkedInId != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n                    <img");

WriteLiteral(" height=\"1\"");

WriteLiteral(" width=\"1\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 23719), Tuple.Create("\"", 23818)
, Tuple.Create(Tuple.Create("", 23725), Tuple.Create("https://dc.ads.linkedin.com/collect/?pid=", 23725), true)
            
            #line 436 "..\..\Views\Checkout\JSTracking.cshtml"
                                         , Tuple.Create(Tuple.Create("", 23766), Tuple.Create<System.Object, System.Int32>(linkedInId
            
            #line default
            #line hidden
, 23766), false)
, Tuple.Create(Tuple.Create("", 23779), Tuple.Create("&conversionId=", 23779), true)
            
            #line 436 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 23793), Tuple.Create<System.Object, System.Int32>(linkedInConvId
            
            #line default
            #line hidden
, 23793), false)
, Tuple.Create(Tuple.Create("", 23810), Tuple.Create("&fmt=gif", 23810), true)
);

WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

            
            #line 438 "..\..\Views\Checkout\JSTracking.cshtml"
            }
        }


        // Google Adwords
        if (!Convert.ToBoolean(HttpContext.Current.Session["U_IsPortalUser"]))
        {
            if (adwordsId1 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Google Adwords 1 -->\r\n");

            
            #line 448 "..\..\Views\Checkout\JSTracking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 448 "..\..\Views\Checkout\JSTracking.cshtml"
           Write(WriteGoogleTag(adwordsId1, adwordsLabel1, Model.BasketTotals.GrandTotalExcVat));

            
            #line default
            #line hidden
            
            #line 448 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                               
            }
            if (adwordsId2 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Google Adwords 2 -->\r\n");

            
            #line 453 "..\..\Views\Checkout\JSTracking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 453 "..\..\Views\Checkout\JSTracking.cshtml"
           Write(WriteGoogleTag(adwordsId2, adwordsLabel2, Model.BasketTotals.GrandTotalExcVat));

            
            #line default
            #line hidden
            
            #line 453 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                               
            }
            if (adwordsId3 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Google Adwords 3 -->\r\n");

            
            #line 458 "..\..\Views\Checkout\JSTracking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 458 "..\..\Views\Checkout\JSTracking.cshtml"
           Write(WriteGoogleTag(adwordsId3, adwordsLabel3, Model.BasketTotals.GrandTotalExcVat));

            
            #line default
            #line hidden
            
            #line 458 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                               
            }
            if (adwordsId4 != "")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<!-- Google Adwords 4 -->\r\n");

            
            #line 463 "..\..\Views\Checkout\JSTracking.cshtml"
                
            
            #line default
            #line hidden
            
            #line 463 "..\..\Views\Checkout\JSTracking.cshtml"
           Write(WriteGoogleTag(adwordsId4, adwordsLabel4, Model.BasketTotals.GrandTotalExcVat));

            
            #line default
            #line hidden
            
            #line 463 "..\..\Views\Checkout\JSTracking.cshtml"
                                                                                               
            }
        }

        // SLI Spark Tracking
        if (ConfigurationManager.AppSettings["SearchApplication"] == "SLI")
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("<!-- SLI Spark Tracking -->\r\n");

WriteLiteral("            ");

WriteLiteral("<script type=\"text/javascript\">\r\n");

WriteLiteral("            ");

WriteLiteral(@"
                (function(i,s,o,g,r,a,m){i[r]=i[r]||function(){
                (i[r].a=i[r].a||[]).push(arguments)};i[r].t=1;a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window, document, 'script', '//");

            
            #line 476 "..\..\Views\Checkout\JSTracking.cshtml"
                                              Write(Html.RawFromDict(Model.CommonData, "DomainName"));

            
            #line default
            #line hidden
WriteLiteral("data/static-files/cpy_slispark.js\', \'sliSpark\');\r\n            ");

WriteLiteral("\r\n");

            
            #line 478 "..\..\Views\Checkout\JSTracking.cshtml"
            foreach (BasketContents bc in Model.BasketContents)
            {
                if (!bc.IsDelivery && !bc.IsVoucher)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("\r\n                        sliSpark(\"sli:addProduct\", {\r\n                        i" +
"d: \"");

            
            #line 484 "..\..\Views\Checkout\JSTracking.cshtml"
                        Write(bc.ProductId);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        price: \"\'");

            
            #line 485 "..\..\Views\Checkout\JSTracking.cshtml"
                            Write(bc.PriceInc.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        quantity: \"");

            
            #line 486 "..\..\Views\Checkout\JSTracking.cshtml"
                              Write(bc.Quantity.ToString());

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        currency: \"GBP\"\r\n                        });\r\n       " +
"             ");

WriteLiteral("\r\n");

            
            #line 490 "..\..\Views\Checkout\JSTracking.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n                sliSpark(\"sli:setAction\", \"purchase\", {\r\n                id: \"");

            
            #line 494 "..\..\Views\Checkout\JSTracking.cshtml"
                Write(Model.CheckoutDetails.BackOfficeOrderRef);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                revenue: \"");

            
            #line 495 "..\..\Views\Checkout\JSTracking.cshtml"
                     Write(Model.BasketTotals.GrandTotalIncVat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                tax: \"");

            
            #line 496 "..\..\Views\Checkout\JSTracking.cshtml"
                 Write(Model.BasketTotals.Vat.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                shipping: \"");

            
            #line 497 "..\..\Views\Checkout\JSTracking.cshtml"
                      Write(Model.BasketTotals.Delivery.ToString("F2"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                currency: \"GBP\"\r\n                });\r\n                sliSpar" +
"k(\'send\', \'pageview\');\r\n            ");

WriteLiteral("\r\n");

WriteLiteral("            ");

WriteLiteral("</script>\r\n");

            
            #line 503 "..\..\Views\Checkout\JSTracking.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
