#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Checkout\OrderSummary.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Checkout\OrderSummary.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 3 "..\..\Views\Checkout\OrderSummary.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/OrderSummary.cshtml")]
    public partial class _Views_Checkout_OrderSummary_cshtml : System.Web.Mvc.WebViewPage<CheckoutViewModel>
    {
        public _Views_Checkout_OrderSummary_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Checkout\OrderSummary.cshtml"
   
    bool isVatExempt = HttpContext.Current.Session["D_IsVatExempt"] != null && Convert.ToBoolean(HttpContext.Current.Session["D_IsVatExempt"]);
    if (ViewBag.IsVatExempt != null)
    {
        isVatExempt = ViewBag.IsVatExempt;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"OrderSummaryTitleRow\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"pull-left col-md-12 col-lg-7 g-ws-nw\"");

WriteLiteral(">Order Summary</h2>\r\n");

            
            #line 17 "..\..\Views\Checkout\OrderSummary.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Checkout\OrderSummary.cshtml"
         if (ViewBag.AllowEdit)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-12 col-lg-5\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 619), Tuple.Create("\"", 637)
, Tuple.Create(Tuple.Create("", 626), Tuple.Create<System.Object, System.Int32>(Href("~/checkout/")
, 626), false)
);

WriteLiteral(" class=\"btn g-butt-second-reg g-butt-md-2 pull-right\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(">Edit Basket</a>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-12 g-m-t-10 visible-md\"");

WriteLiteral("></div>\r\n");

            
            #line 23 "..\..\Views\Checkout\OrderSummary.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"g-bc-s g-b-1-p\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral("><strong>Your Items <span");

WriteLiteral(" class=\"g-fc-s\"");

WriteLiteral(">(");

            
            #line 28 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                            Write(Model.BasketTotals.Quantity.ToString("##0"));

            
            #line default
            #line hidden
WriteLiteral(")</span></strong></div>\r\n    <hr />\r\n");

            
            #line 30 "..\..\Views\Checkout\OrderSummary.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Checkout\OrderSummary.cshtml"
     foreach (BasketContents bc in Model.BasketContents)
    {
        if (bc.ItemType == BasketItemType.Item || bc.ItemType == BasketItemType.AdminDiscount || bc.ItemType == BasketItemType.CompatibleDiscount)
        {
            string neg = (bc.ItemType == BasketItemType.AdminDiscount || bc.ItemType == BasketItemType.CompatibleDiscount) ? "-" : "";

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n                <div>");

            
            #line 36 "..\..\Views\Checkout\OrderSummary.cshtml"
                Write(bc.Description);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"g-m-t-5\"");

WriteLiteral(">\r\n                    Qty: <strong>");

            
            #line 38 "..\..\Views\Checkout\OrderSummary.cshtml"
                            Write(bc.Quantity.ToString("##0"));

            
            #line default
            #line hidden
WriteLiteral(" | ");

            
            #line 38 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                           Write(neg);

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                               Write(string.Format("{0:C}", bc.PriceEx));

            
            #line default
            #line hidden
WriteLiteral("</strong> <span");

WriteLiteral(" class=\"g-fc-tt g-fs-sm\"");

WriteLiteral(">ex VAT</span>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <hr />\r\n");

            
            #line 42 "..\..\Views\Checkout\OrderSummary.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pull-left g-w-40p\"");

WriteLiteral("><strong>Delivery</strong></div>\r\n            <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

            
            #line 48 "..\..\Views\Checkout\OrderSummary.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Checkout\OrderSummary.cshtml"
                 if (Model.BasketTotals.Delivery == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("FREE\r\n");

            
            #line 51 "..\..\Views\Checkout\OrderSummary.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Checkout\OrderSummary.cshtml"
               Write(Html.Raw("&pound;" + string.Format("{0:N2}", Math.Abs(Model.BasketTotals.Delivery))));

            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                                                                         
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pull-left g-w-40p\"");

WriteLiteral("><strong>Sub-Total</strong></div>\r\n            <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Checkout\OrderSummary.cshtml"
                               Write(string.Format("{0:C}", Model.BasketTotals.TotalExcVat - Model.BasketTotals.Delivery));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pull-left g-w-40p\"");

WriteLiteral("><strong>VAT</strong></div>\r\n            <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Checkout\OrderSummary.cshtml"
                               Write(string.Format("{0:C}", (!isVatExempt ? Model.BasketTotals.Vat + Model.BasketTotals.VoucherVat : decimal.Zero)));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 67 "..\..\Views\Checkout\OrderSummary.cshtml"
    
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Checkout\OrderSummary.cshtml"
     if (ViewBag.HideVoucher == false)
    {

            
            #line default
            #line hidden
WriteLiteral("        <hr />\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left g-w-40p\"");

WriteLiteral("><strong>Voucher</strong></div>\r\n                <div");

WriteLiteral(" class=\"pull-right g-i g-fc-pm\"");

WriteLiteral(">\r\n");

            
            #line 74 "..\..\Views\Checkout\OrderSummary.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Checkout\OrderSummary.cshtml"
                     if (Model.BasketTotals.Voucher == 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("FREE GIFT\r\n");

            
            #line 77 "..\..\Views\Checkout\OrderSummary.cshtml"
                    }
                    else
                    {
                        if (!isVatExempt)
                        {
                            
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                                       
                            
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Checkout\OrderSummary.cshtml"
                        Write((Model.BasketTotals.Voucher < 0 ? "-" : ""));

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                                          
                            
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Checkout\OrderSummary.cshtml"
                       Write(Html.Raw(("&pound;" + string.Format("{0:N2}", Math.Abs(Model.BasketTotals.Voucher + Model.BasketTotals.VoucherVat)) + " (inc VAT)")));

            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                                                                                                                                 
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Checkout\OrderSummary.cshtml"
                        Write((Model.BasketTotals.Voucher < 0 ? "-" : ""));

            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                                          
                            
            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Checkout\OrderSummary.cshtml"
                       Write(Html.Raw(("&pound;" + string.Format("{0:N2}", Math.Abs(Model.BasketTotals.Voucher + Model.BasketTotals.VoucherVat)))));

            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Checkout\OrderSummary.cshtml"
                                                                                                                                                  
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 100 "..\..\Views\Checkout\OrderSummary.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <hr />\r\n    <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pull-left g-w-40p\"");

WriteLiteral("><strong>Grand Total</strong></div>\r\n            <div");

WriteLiteral(" class=\"pull-right g-fs-lg\"");

WriteLiteral(">\r\n");

            
            #line 106 "..\..\Views\Checkout\OrderSummary.cshtml"
                
            
            #line default
            #line hidden
            
            #line 106 "..\..\Views\Checkout\OrderSummary.cshtml"
                 if (!isVatExempt)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <strong>");

            
            #line 108 "..\..\Views\Checkout\OrderSummary.cshtml"
                       Write(string.Format("{0:C}", Model.BasketTotals.GrandTotalIncVat));

            
            #line default
            #line hidden
WriteLiteral("</strong>");

WriteLiteral("<span");

WriteLiteral(" class=\"g-fc-tt g-fs-sm\"");

WriteLiteral("> inc VAT</span>\r\n");

            
            #line 109 "..\..\Views\Checkout\OrderSummary.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <strong>");

            
            #line 112 "..\..\Views\Checkout\OrderSummary.cshtml"
                       Write(string.Format("{0:C}", Model.BasketTotals.GrandTotalExcVat));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n");

            
            #line 113 "..\..\Views\Checkout\OrderSummary.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

            
            #line 118 "..\..\Views\Checkout\OrderSummary.cshtml"
 if (ViewBag.Stage1 != "active")
{
    if (Model.CheckoutDetails.DeliveryAddress != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"g-bc-s g-b-1-p g-m-t-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral("><strong>Delivering to</strong></div>\r\n            <hr />\r\n            <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n");

            
            #line 126 "..\..\Views\Checkout\OrderSummary.cshtml"
                
            
            #line default
            #line hidden
            
            #line 126 "..\..\Views\Checkout\OrderSummary.cshtml"
                 if (Model.CheckoutDetails.Name != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div>");

            
            #line 128 "..\..\Views\Checkout\OrderSummary.cshtml"
                     Write(Model.CheckoutDetails.RecipientName.Title + " " + Model.CheckoutDetails.RecipientName.Firstname + " " + Model.CheckoutDetails.RecipientName.Surname);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 129 "..\..\Views\Checkout\OrderSummary.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" id=\"summ-deladd-line1\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\Checkout\OrderSummary.cshtml"
                                       Write(Model.CheckoutDetails.DeliveryAddress.Line1);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" id=\"summ-deladd-line2\"");

WriteLiteral(">");

            
            #line 131 "..\..\Views\Checkout\OrderSummary.cshtml"
                                       Write(Model.CheckoutDetails.DeliveryAddress.Line2);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" id=\"summ-deladd-line3\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\Checkout\OrderSummary.cshtml"
                                       Write(Model.CheckoutDetails.DeliveryAddress.Line3);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" id=\"summ-deladd-line4\"");

WriteLiteral(">");

            
            #line 133 "..\..\Views\Checkout\OrderSummary.cshtml"
                                       Write(Model.CheckoutDetails.DeliveryAddress.Line4);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" id=\"summ-deladd-postcode\"");

WriteLiteral(">");

            
            #line 134 "..\..\Views\Checkout\OrderSummary.cshtml"
                                          Write(Model.CheckoutDetails.DeliveryAddress.PostCode);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 137 "..\..\Views\Checkout\OrderSummary.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"g-bc-s g-b-1-p g-m-t-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral("><strong>Billing Address</strong></div>\r\n            <hr />\r\n            <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n");

            
            #line 142 "..\..\Views\Checkout\OrderSummary.cshtml"
                
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Checkout\OrderSummary.cshtml"
                 if (Model.CheckoutDetails.Name != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div>");

            
            #line 144 "..\..\Views\Checkout\OrderSummary.cshtml"
                     Write(Model.CheckoutDetails.Name.Title + " " + Model.CheckoutDetails.Name.Firstname + " " + Model.CheckoutDetails.Name.Surname);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 145 "..\..\Views\Checkout\OrderSummary.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div>");

            
            #line 146 "..\..\Views\Checkout\OrderSummary.cshtml"
                Write(Model.CheckoutDetails.BillingAddress.Line1);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div>");

            
            #line 147 "..\..\Views\Checkout\OrderSummary.cshtml"
                Write(Model.CheckoutDetails.BillingAddress.Line2);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div>");

            
            #line 148 "..\..\Views\Checkout\OrderSummary.cshtml"
                Write(Model.CheckoutDetails.BillingAddress.Line3);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div>");

            
            #line 149 "..\..\Views\Checkout\OrderSummary.cshtml"
                Write(Model.CheckoutDetails.BillingAddress.Line4);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div>");

            
            #line 150 "..\..\Views\Checkout\OrderSummary.cshtml"
                Write(Model.CheckoutDetails.BillingAddress.PostCode);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 153 "..\..\Views\Checkout\OrderSummary.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
