#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 5 "..\..\Views\Checkout\ViewBasket.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Checkout\ViewBasket.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Checkout\ViewBasket.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 3 "..\..\Views\Checkout\ViewBasket.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Checkout\ViewBasket.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/ViewBasket.cshtml")]
    public partial class _Views_Checkout_ViewBasket_cshtml : System.Web.Mvc.WebViewPage<CheckoutViewModel>
    {
        public _Views_Checkout_ViewBasket_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

DefineSection("AddTags", () => {

WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Checkout\ViewBasket.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Checkout\ViewBasket.cshtml"
      
        int sessionTimeout = (Session.Timeout > 1 ? Session.Timeout - 1 : 1) * 60;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <meta");

WriteLiteral(" http-equiv=\"refresh\"");

WriteAttribute("content", Tuple.Create(" content=\"", 312), Tuple.Create("\"", 379)
            
            #line 14 "..\..\Views\Checkout\ViewBasket.cshtml"
, Tuple.Create(Tuple.Create("", 322), Tuple.Create<System.Object, System.Int32>(sessionTimeout.ToString()
            
            #line default
            #line hidden
, 322), false)
, Tuple.Create(Tuple.Create("", 348), Tuple.Create(";", 348), true)
, Tuple.Create(Tuple.Create(" ", 349), Tuple.Create("URL=/?pm=SessionExpired&sz=md", 350), true)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"preconnect\"");

WriteLiteral(" href=\"https://www.paypal.com/\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"preconnect\"");

WriteLiteral(" href=\"https://www.paypalobjects.com/\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"canonical\"");

WriteAttribute("href", Tuple.Create(" href=\"", 535), Tuple.Create("\"", 607)
, Tuple.Create(Tuple.Create("", 542), Tuple.Create("https://", 542), true)
            
            #line 17 "..\..\Views\Checkout\ViewBasket.cshtml"
, Tuple.Create(Tuple.Create("", 550), Tuple.Create<System.Object, System.Int32>(Model.DomainNameTrunc
            
            #line default
            #line hidden
, 550), false)
            
            #line 17 "..\..\Views\Checkout\ViewBasket.cshtml"
, Tuple.Create(Tuple.Create("", 572), Tuple.Create<System.Object, System.Int32>(Request.Url.AbsolutePath.ToLower()
            
            #line default
            #line hidden
, 572), false)
);

WriteLiteral(">\r\n");

});

WriteLiteral("\r\n<section");

WriteLiteral(" id=\"loadbg\"");

WriteLiteral(" class=\"\"");

WriteLiteral(" data-stellar-background-ratio=\"0.5\"");

WriteLiteral(" data-stellar-ratio=\"1\"");

WriteLiteral(" data-bgimg=\"");

            
            #line 20 "..\..\Views\Checkout\ViewBasket.cshtml"
                                                                                                Write(Html.RawFromDict(Model.CommonData, "FeatureBackground"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 comm-title-banner g-h-120 g-fc-st\"");

WriteLiteral(">\r\n");

            
            #line 24 "..\..\Views\Checkout\ViewBasket.cshtml"
                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Checkout\ViewBasket.cshtml"
                 if (!Model.IsMobile)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"bread-crumb hidden-xs hidden-sm\"");

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Views\Checkout\ViewBasket.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Checkout\ViewBasket.cshtml"
                         foreach (KeyValuePair<string, string> bc in Model.BreadcrumbTrail)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"second\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1207), Tuple.Create("\"", 1224)
, Tuple.Create(Tuple.Create("", 1214), Tuple.Create("/", 1214), true)
            
            #line 29 "..\..\Views\Checkout\ViewBasket.cshtml"
, Tuple.Create(Tuple.Create("", 1215), Tuple.Create<System.Object, System.Int32>(bc.Value
            
            #line default
            #line hidden
, 1215), false)
);

WriteLiteral(">");

            
            #line 29 "..\..\Views\Checkout\ViewBasket.cshtml"
                                                           Write(bc.Key);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("                            <i");

WriteLiteral(" class=\"fa fa-chevron-right g-fs-xs-i\"");

WriteLiteral("></i>\r\n");

            
            #line 31 "..\..\Views\Checkout\ViewBasket.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 33 "..\..\Views\Checkout\ViewBasket.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"g-m-t-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                        <h1>\r\n                            <span");

WriteLiteral(" class=\"\"");

WriteLiteral(">Your Basket</span>\r\n                        </h1>\r\n                        <div");

WriteLiteral(" class=\"g-m-t-10\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-reply\"");

WriteLiteral("></i>\r\n                            <a");

WriteLiteral(" class=\"second g-m-l-10 g-i\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">\r\n                                Continue Shopping\r\n                           " +
" </a>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 46 "..\..\Views\Checkout\ViewBasket.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Checkout\ViewBasket.cshtml"
                     if (!Model.IsMobile)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"pull-right hidden-xs hidden-sm\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Views\Checkout\ViewBasket.cshtml"
                       Write(Html.ShowSaleInfoButton(Model.IsCompatibleSaleActive, Model.IsOEMSaleActive, Model.IsStationerySaleActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");

            
            #line 51 "..\..\Views\Checkout\ViewBasket.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section" +
">\r\n\r\n<section");

WriteLiteral(" class=\"g-bc-p g-p-t-20 g-p-b-100\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container body-content g-ps-r\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row g-m-t-20\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <!-- Left Hand Column -->\r\n                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"vbBasketDetails\"");

WriteLiteral(">\r\n");

            
            #line 66 "..\..\Views\Checkout\ViewBasket.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Checkout\ViewBasket.cshtml"
                              
                                Html.RenderPartial("~/Views/Checkout/BasketDetails.cshtml", Model);
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"g-bc-s g-b-1-p g-m-t-20 visible-xs visible-sm restrict-images vb-pay-meth" +
"ods\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"g-p-10\"");

WriteLiteral(">\r\n                                <strong>Payment Methods</strong>\r\n            " +
"                </div>\r\n                            <hr />\r\n                    " +
"        <div");

WriteLiteral(" class=\"g-p-10 text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 77 "..\..\Views\Checkout\ViewBasket.cshtml"
                           Write(Html.Raw(Model.CheckoutData["PaymentMethods"].Replace("[newline]", "&#013;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"               <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-12 g-m-t-60\"");

WriteLiteral(">\r\n");

            
            #line 83 "..\..\Views\Checkout\ViewBasket.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Checkout\ViewBasket.cshtml"
                                  
                                    Html.RenderPartial("~/Views/Shared/LiveChat.cshtml", Model);
                                
            
            #line default
            #line hidden
WriteLiteral(@"
                            </div>
                        </div>
                    </div>

                    <!-- Right Hand Column -->
                    
                </div>
            </div>
        </div>
    </div>
</section>

<input");

WriteLiteral(" hidden=\"hidden\"");

WriteLiteral(" class=\"IsInCheckout\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 100 "..\..\Views\Checkout\ViewBasket.cshtml"
  
    if (Authentication.IsNotFullyAuthenticated())
    {
        Html.RenderPartial("~/Views/Checkout/Ident.cshtml", Model);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        $(document).on('click',
            '.checkout-button',
            function () {
                //if ($('.hdr-basket .basketTotal').html() == '0.00') {
                //    return;
                //}
                if (checkSessionExists('C_IsInCheckout')) {
                    launchPopup('IsInCheckout', 'popup', 'lg', '');
                    return;
                }
                if ('");

            
            #line 121 "..\..\Views\Checkout\ViewBasket.cshtml"
                 Write(Authentication.IsFullyAuthenticated());

            
            #line default
            #line hidden
WriteLiteral(@"' == 'True') {
                    // Authenticated
                    $('#co-form').submit();
                } else {
                    // Not Authenticated - so ask to Login/Register
                    $('#ident-modal').modal();
                }
            });

        $(function () {
            if (checkSessionExists('C_IsInCheckout')) {
                $('.IsInCheckout').val('true');
                $('#voucher-code, #apply-voucher').prop('disabled', true);
            } else {
                $('#voucher-code, #apply-voucher').prop('disabled', false);
            }
        });

        $(window).on('unload', function () {
            if ($('.paypal-checkout-sandbox').is(':visible') == true && $('.IsInCheckout').val() != 'true') {
                setSession(""C_IsInCheckout"", null);
            }
        });

    </script>
");

            
            #line 146 "..\..\Views\Checkout\ViewBasket.cshtml"
    
            
            #line default
            #line hidden
            
            #line 146 "..\..\Views\Checkout\ViewBasket.cshtml"
     if (!Convert.ToBoolean(Session["U_IsPortalUser"]) && Model.BasketTotals.GrandTotalIncVat > 0.01m)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5658), Tuple.Create("\"", 5938)
, Tuple.Create(Tuple.Create("", 5664), Tuple.Create("https://www.paypal.com/sdk/js?client-id=", 5664), true)
            
            #line 148 "..\..\Views\Checkout\ViewBasket.cshtml"
, Tuple.Create(Tuple.Create("", 5704), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["PayPalClientId"]
            
            #line default
            #line hidden
, 5704), false)
, Tuple.Create(Tuple.Create("", 5757), Tuple.Create("&currency=GBP&locale=en_GB&intent=authorize&components=messages,buttons&enable-fu" +
"nding=paylater&debug=", 5757), true)
            
            #line 148 "..\..\Views\Checkout\ViewBasket.cshtml"
                                                                                                                                         , Tuple.Create(Tuple.Create("", 5859), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["Environment"] == "Live" ? "false" : "true"
            
            #line default
            #line hidden
, 5859), false)
);

WriteLiteral(">\r\n        </script>\r\n");

            
            #line 150 "..\..\Views\Checkout\ViewBasket.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("AddScript", () => {

WriteLiteral("\r\n");

            
            #line 156 "..\..\Views\Checkout\ViewBasket.cshtml"
    
            
            #line default
            #line hidden
            
            #line 156 "..\..\Views\Checkout\ViewBasket.cshtml"
      
        Html.RenderPartial("~/Views/Checkout/JSTracking.cshtml", Model);
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 159 "..\..\Views\Checkout\ViewBasket.cshtml"
Write(Scripts.Render("~/bundles/checkoutBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("StructuredData", () => {

WriteLiteral("\r\n    [\r\n");

WriteLiteral("    ");

            
            #line 165 "..\..\Views\Checkout\ViewBasket.cshtml"
Write(Html.Raw(ViewBag.BreadcrumbJson));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ]\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
