//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP001DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBrandMatching
    {
        public int SupplierBrandMatchingID { get; set; }
        public int SupplierFK { get; set; }
        public string Reference { get; set; }
        public string BrandName { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
