#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\_Layout.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    #line 5 "..\..\Views\Shared\_Layout.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Layout.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_Layout.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_Layout.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<CommonViewModel>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
  
    BasketTotals bt = new BasketTotals();

    if (Session["B_BasketTotals"] != null)
    {
        bt = (BasketTotals)Session["B_BasketTotals"];
    }

    Tuple<string, decimal> basketTotal = Utilities.SetPrice(bt.GrandTotalIncVat, bt.GrandTotalExcVat);

    string searchadd = "";
    if (ConfigurationManager.AppSettings["SearchApplication"] == "SLI")
    {
        searchadd = "data-provide=\"rac\"";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"format-detection\"");

WriteLiteral(" content=\"telephone=no\"");

WriteLiteral(">\r\n    <!--meta name=\"theme-color\" content=\"#006699\" /-->\r\n    <title>");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
      Write(Html.RawFromDict(Model.MetaData, "Title"));

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 952), Tuple.Create("\"", 1010)
            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 962), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Description")
            
            #line default
            #line hidden
, 962), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"msvalidate.01\"");

WriteLiteral(" content=\"25C06F8BDF2376F495D44F19998FAE5F\"");

WriteLiteral(">\r\n\r\n    <meta");

WriteLiteral(" property=\"og:title\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1121), Tuple.Create("\"", 1173)
            
            #line 37 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1131), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Title")
            
            #line default
            #line hidden
, 1131), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:type\"");

WriteLiteral(" content=\"website\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:image\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1255), Tuple.Create("\"", 1325)
            
            #line 39 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1265), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1265), false)
, Tuple.Create(Tuple.Create("", 1305), Tuple.Create("/images/soc-logo.png", 1305), true)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:image:width\"");

WriteLiteral(" content=\"1200\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:image:height\"");

WriteLiteral(" content=\"630\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:url\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1462), Tuple.Create("\"", 1521)
, Tuple.Create(Tuple.Create("", 1472), Tuple.Create("//", 1472), true)
            
            #line 42 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1474), Tuple.Create<System.Object, System.Int32>(Model.DomainNameTrunc
            
            #line default
            #line hidden
, 1474), false)
            
            #line 42 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1496), Tuple.Create<System.Object, System.Int32>(Request.Url.PathAndQuery
            
            #line default
            #line hidden
, 1496), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:site_name\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1558), Tuple.Create("\"", 1615)
            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1568), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SiteName")
            
            #line default
            #line hidden
, 1568), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1654), Tuple.Create("\"", 1712)
            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1664), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Description")
            
            #line default
            #line hidden
, 1664), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:title\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1746), Tuple.Create("\"", 1798)
            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1756), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Title")
            
            #line default
            #line hidden
, 1756), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:card\"");

WriteLiteral(" content=\"summary_large_image\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1900), Tuple.Create("\"", 1958)
            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1910), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.MetaData, "Description")
            
            #line default
            #line hidden
, 1910), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"twitter:image\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1992), Tuple.Create("\"", 2062)
            
            #line 48 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2002), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 2002), false)
, Tuple.Create(Tuple.Create("", 2042), Tuple.Create("/images/soc-logo.jpg", 2042), true)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2098), Tuple.Create("\"", 2151)
, Tuple.Create(Tuple.Create("", 2105), Tuple.Create("//", 2105), true)
            
            #line 49 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2107), Tuple.Create<System.Object, System.Int32>(Model.DomainNameTrunc
            
            #line default
            #line hidden
, 2107), false)
, Tuple.Create(Tuple.Create("", 2129), Tuple.Create("/touch-icon-iphone.png", 2129), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"76x76\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2203), Tuple.Create("\"", 2254)
, Tuple.Create(Tuple.Create("", 2210), Tuple.Create("//", 2210), true)
            
            #line 50 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2212), Tuple.Create<System.Object, System.Int32>(Model.DomainNameTrunc
            
            #line default
            #line hidden
, 2212), false)
, Tuple.Create(Tuple.Create("", 2234), Tuple.Create("/touch-icon-ipad.png", 2234), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"120x120\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2308), Tuple.Create("\"", 2368)
, Tuple.Create(Tuple.Create("", 2315), Tuple.Create("//", 2315), true)
            
            #line 51 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2317), Tuple.Create<System.Object, System.Int32>(Model.DomainNameTrunc
            
            #line default
            #line hidden
, 2317), false)
, Tuple.Create(Tuple.Create("", 2339), Tuple.Create("/touch-icon-iphone-retina.png", 2339), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"152x152\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2422), Tuple.Create("\"", 2480)
, Tuple.Create(Tuple.Create("", 2429), Tuple.Create("//", 2429), true)
            
            #line 52 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2431), Tuple.Create<System.Object, System.Int32>(Model.DomainNameTrunc
            
            #line default
            #line hidden
, 2431), false)
, Tuple.Create(Tuple.Create("", 2453), Tuple.Create("/touch-icon-ipad-retina.png", 2453), true)
);

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" rel=\"manifest\"");

WriteLiteral(" href=\"/Content/manifest.json\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2558), Tuple.Create("\"", 2618)
            
            #line 56 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2565), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "GooglePlusPage")
            
            #line default
            #line hidden
, 2565), false)
);

WriteLiteral(" rel=\"publisher\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.RawFromDict(Model.CommonData, "HtmlHeaderExtras"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"application/ld+json\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
   Write(Html.RawFromDict(Model.CommonData, "Nap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 62 "..\..\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\_Layout.cshtml"
          
            Html.RenderPartial("~/Views/Shared/JSTrackingAllHdr.cshtml", Model);
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/cssBundle.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 68 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("AddTags", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 69 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jqueryBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</head>\r\n\r\n<body");

WriteAttribute("class", Tuple.Create(" class=\"", 3131), Tuple.Create("\"", 3256)
, Tuple.Create(Tuple.Create("", 3139), Tuple.Create("g-ps-r", 3139), true)
            
            #line 73 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 3145), Tuple.Create<System.Object, System.Int32>(Model.IsStationerySaleActive || Model.IsOEMSaleActive || Model.IsCompatibleSaleActive ? "saleIsActive" : ""
            
            #line default
            #line hidden
, 3146), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
     if (Model.IsFirstTime && Model.FirstTimePopup != "")
    {
        string[] firsttime = Model.FirstTimePopup.Split('~');

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"firsttimepopup\"");

WriteLiteral(" class=\"hidden-xs hidden-sm popup\"");

WriteLiteral("\r\n             data-popupname=\"");

            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
                        Write(firsttime[0]);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n             data-popupwidth=\"md\"");

WriteLiteral("\r\n             data-replacements=\"");

            
            #line 81 "..\..\Views\Shared\_Layout.cshtml"
                           Write(firsttime[2]);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>\r\n");

            
            #line 82 "..\..\Views\Shared\_Layout.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <section");

WriteLiteral(" id=\"firsttimemessage\"");

WriteLiteral(" class=\"ca-message hidden-lg hidden-md\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\Shared\_Layout.cshtml"
                                                                             Write(Html.Raw(Model.FirstTimeMessage));

            
            #line default
            #line hidden
WriteLiteral("</section>\r\n");

            
            #line 84 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <section");

WriteLiteral(" id=\"utility-bar\"");

WriteLiteral(" class=\"hdr-utility-menu g-fc-st visible-lg row-offcanvas\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"sidebar-offcanvas\"");

WriteLiteral(">\r\n");

            
            #line 88 "..\..\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Shared\_Layout.cshtml"
              
                Html.RenderPartial("~/Views/Shared/BasketSummary.cshtml");
                Html.RenderPartial("~/Views/Shared/RecentlyViewed.cshtml");
                Html.RenderPartial("~/Views/Shared/MyPrinters.cshtml", Model);
                Html.RenderPartial("~/Views/Shared/QuickReorder.cshtml", Model);
            
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"tab-closed\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"g-fs-n\"");

WriteLiteral("></span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"tab-open g-flex-allcenter\"");

WriteLiteral(" data-toggle=\"offcanvas-close\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-chevron-right fa-lg\"");

WriteLiteral("></i>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"basketMessage g-b-1-p g-br-3 g-bc-s\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-bc-secondary g-fc-st g-h-30 g-p-5 g-ps-r g-br-t-3\"");

WriteLiteral(">\r\n                Item added to basket - <span");

WriteLiteral(" class=\"g-i\"");

WriteLiteral(">Click here to view</span>\r\n                <div");

WriteLiteral(" class=\"g-ps-a g-fc-s g-arrow-r\"");

WriteLiteral(" style=\"top: 7px; right: -14px;\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"basketItem\"");

WriteLiteral(" class=\"g-m-b-10\"");

WriteLiteral("></div>\r\n            <hr />\r\n            <div");

WriteLiteral(" class=\"text-center g-m-tb-10 g-p-lr-10\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn g-butt-primary g-butt-100p\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4996), Tuple.Create("\"", 5014)
, Tuple.Create(Tuple.Create("", 5003), Tuple.Create<System.Object, System.Int32>(Href("~/checkout/")
, 5003), false)
);

WriteLiteral(" role=\"button\"");

WriteLiteral(">Checkout</a>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"printerMessage g-fs-sm g-b-1-p g-br-3 g-bc-s\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-bc-secondary g-fc-st g-h-30 g-p-5 g-ps-r g-br-t-3\"");

WriteLiteral(">\r\n                My printer added - <span");

WriteLiteral(" class=\"g-i\"");

WriteLiteral(">Click here to view</span>\r\n                <div");

WriteLiteral(" class=\"g-ps-a g-fc-s g-arrow-r\"");

WriteLiteral(" style=\"top: 9px; right: -14px;\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"printerItem\"");

WriteLiteral(" class=\"g-m-b-10\"");

WriteLiteral("></div>\r\n        </div>\r\n    </section>\r\n\r\n    <section");

WriteLiteral(" class=\"mobileBasketMessage hidden-lg hidden-md g-d-n\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"mobileBasketItem\"");

WriteLiteral(" class=\"g-m-b-10 g-w-90p center-block\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn g-butt-primary g-w-90p g-p-10 g-m-b-10 center-block\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5856), Tuple.Create("\"", 5874)
, Tuple.Create(Tuple.Create("", 5863), Tuple.Create<System.Object, System.Int32>(Href("~/checkout/")
, 5863), false)
);

WriteLiteral(" role=\"button\"");

WriteLiteral(">View Basket</a>\r\n                <button");

WriteLiteral(" class=\"btn-continue btn g-bc-s g-w-90p g-p-10 g-m-b-10 g-b-1-p center-block\"");

WriteLiteral(">Continue Shopping</button>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"mobileBasketClose g-f-b g-fs-20 g-w-100p text-center g-fc-st g-cur-p\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"g-fs-n\"");

WriteLiteral(">CLOSE </span><i");

WriteLiteral(" class=\"fa fa-times-circle g-va-m\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>\r\n        </div>\r\n    </section>\r\n\r\n\r\n");

            
            #line 137 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 137 "..\..\Views\Shared\_Layout.cshtml"
     if (Model.ShowCustomerAlert && !Convert.ToBoolean(Session["SuppressCustomerAlert"] ?? false))
    {

            
            #line default
            #line hidden
WriteLiteral("        <section");

WriteLiteral(" class=\"ca-message\"");

WriteLiteral(">\r\n");

            
            #line 140 "..\..\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\Shared\_Layout.cshtml"
             if (ConfigurationManager.AppSettings["AlertLevel"] == "4")
            {
                
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.RawFromDict(Model.CommonData, "Alert4Message"));

            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Shared\_Layout.cshtml"
                                                                    
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 146 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.RawFromDict(Model.CommonData, "CustomerAlertMessage"));

            
            #line default
            #line hidden
            
            #line 146 "..\..\Views\Shared\_Layout.cshtml"
                                                                           
            }

            
            #line default
            #line hidden
WriteLiteral("        </section>\r\n");

            
            #line 149 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"container\"");

WriteLiteral(" id=\"main-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row g-m-t-10 hidden-xs hidden-sm\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"quick-links g-flex-vcenter g-lh-30\"");

WriteLiteral(">\r\n");

            
            #line 155 "..\..\Views\Shared\_Layout.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 155 "..\..\Views\Shared\_Layout.cshtml"
                      
                        if (Authentication.IsAuthenticated())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <span");

WriteLiteral(" class=\"g-p-r-20\"");

WriteLiteral(">\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7189), Tuple.Create("\"", 7208)
, Tuple.Create(Tuple.Create("", 7196), Tuple.Create<System.Object, System.Int32>(Href("~/MyAccount/")
, 7196), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"msp_userDark\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7273), Tuple.Create("\"", 7308)
, Tuple.Create(Tuple.Create("", 7279), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 7279), false)
);

WriteLiteral(" />\r\n                                    <span");

WriteLiteral(" class=\"g-p-l-5\"");

WriteLiteral(">My Account</span>\r\n                                </a>\r\n                       " +
"     </span>\r\n");

WriteLiteral("                            <span");

WriteLiteral(" class=\"logout g-p-r-20 g-cur-p\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" class=\"msp_logOutDark\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7593), Tuple.Create("\"", 7628)
, Tuple.Create(Tuple.Create("", 7599), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 7599), false)
);

WriteLiteral(" />\r\n                                <span");

WriteLiteral(" class=\"g-p-l-5\"");

WriteLiteral(">Sign Out</span>\r\n                            </span>\r\n");

            
            #line 168 "..\..\Views\Shared\_Layout.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <span");

WriteLiteral(" id=\"sign-in\"");

WriteLiteral(" class=\"g-p-r-20 g-cur-p\"");

WriteLiteral("\r\n                                  data-toggle=\"modal\"");

WriteLiteral("\r\n                                  data-target=\"#SignIn\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" class=\"msp_logInDark\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8070), Tuple.Create("\"", 8105)
, Tuple.Create(Tuple.Create("", 8076), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 8076), false)
);

WriteLiteral(" />\r\n                                <span");

WriteLiteral(" class=\"g-p-l-5\"");

WriteLiteral(">Sign In</span>\r\n                            </span>\r\n");

            
            #line 177 "..\..\Views\Shared\_Layout.cshtml"
                        }
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span");

WriteLiteral(" class=\"g-p-r-20 open-utility g-cur-p visible-lg\"");

WriteLiteral(" data-utility=\"quick-order\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"msp_quickreorderDark\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8429), Tuple.Create("\"", 8464)
, Tuple.Create(Tuple.Create("", 8435), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 8435), false)
);

WriteLiteral(" />\r\n                        <span");

WriteLiteral(" class=\"g-p-l-5\"");

WriteLiteral(">Quick Reorder</span>\r\n                    </span>\r\n                    <span");

WriteLiteral(" class=\"g-p-r-20 hidden-lg\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"/MyAccount/Index/QuickReorder/\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" class=\"msp_quickreorderDark\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8750), Tuple.Create("\"", 8785)
, Tuple.Create(Tuple.Create("", 8756), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 8756), false)
);

WriteLiteral(" />\r\n                            <span");

WriteLiteral(" class=\"g-p-l-5\"");

WriteLiteral(">Quick Reorder</span>\r\n                        </a>\r\n                    </span>\r" +
"\n                    <span");

WriteLiteral(" class=\"g-p-r-20\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8993), Tuple.Create("\"", 9007)
, Tuple.Create(Tuple.Create("", 9000), Tuple.Create<System.Object, System.Int32>(Href("~/help/")
, 9000), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"g-d-ib g-p-r-20\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" class=\"msp_helpDark\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9104), Tuple.Create("\"", 9139)
, Tuple.Create(Tuple.Create("", 9110), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 9110), false)
);

WriteLiteral(" />\r\n                            <span");

WriteLiteral(" class=\"g-p-l-5\"");

WriteLiteral(">Help &amp; Information</span>\r\n                        </a>\r\n                   " +
" </span>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"hdr-right pull-right\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"hdr-info pull-right g-flex-vcenter\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-phone fa-lg\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"phone g-p-r-5 g-fs-lg\"");

WriteLiteral(">\r\n                                <strong>");

            
            #line 203 "..\..\Views\Shared\_Layout.cshtml"
                                   Write(Html.RawFromDict(Model.CommonData, "TelephoneNumber"));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                            </span>\r\n                        </div>\r\n " +
"                       <div");

WriteLiteral(" class=\"pull-right g-p-l-10\"");

WriteLiteral(">Mon-Thur 9 - 5:30 & Fri 10 - 5:30</div>\r\n                    </div>\r\n           " +
"     </div>\r\n            </div>\r\n        </div>\r\n\r\n        <hr");

WriteLiteral(" class=\"g-m-tb-10 hidden-xs hidden-sm\"");

WriteLiteral(" />\r\n\r\n        <div");

WriteLiteral(" class=\"row g-m-b-10-md\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-8 hidden-xs hidden-sm\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"g-w-320\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/Images/1pxTrans.png\"");

WriteLiteral(" class=\"msp_siteLogo img-responsive g-m-t-10\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 10359), Tuple.Create("\"", 10412)
            
            #line 218 "..\..\Views\Shared\_Layout.cshtml"
                                 , Tuple.Create(Tuple.Create("", 10365), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SiteName")
            
            #line default
            #line hidden
, 10365), false)
);

WriteLiteral(" />\r\n                    </a>\r\n                </div>\r\n            </div>\r\n      " +
"      <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"hdr-right pull-right\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"hdr-basket pull-right clearfix hidden-xs hidden-sm\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-left g-p-t-10\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-shopping-basket g-p-r-5\"");

WriteLiteral("></i>\r\n                            <a");

WriteLiteral(" class=\"primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 10841), Tuple.Create("\"", 10859)
, Tuple.Create(Tuple.Create("", 10848), Tuple.Create<System.Object, System.Int32>(Href("~/checkout/")
, 10848), false)
);

WriteLiteral(">\r\n                                <strong>Basket (<span");

WriteLiteral(" class=\"basketQuantity\"");

WriteLiteral(">");

            
            #line 228 "..\..\Views\Shared\_Layout.cshtml"
                                                                        Write(bt.Quantity);

            
            #line default
            #line hidden
WriteLiteral("</span>) - &pound;<span");

WriteLiteral(" class=\"basketTotal\"");

WriteLiteral(">");

            
            #line 228 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                 Write((bt.GrandTotalExcVat >= bt.Delivery ? basketTotal.Item2 - bt.Delivery : basketTotal.Item2).ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral("</span></strong> <span");

WriteLiteral(" class=\"g-fc-tt g-fs-sm\"");

WriteLiteral(">");

            
            #line 228 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                                                                                                                                     Write(basketTotal.Item1);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </a>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

            
            #line 232 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 232 "..\..\Views\Shared\_Layout.cshtml"
                             if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "Checkout")
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"checkout-button btn g-butt-primary g-butt-lg\"");

WriteLiteral(" title=\"Checkout\"");

WriteLiteral(">Checkout</button>\r\n");

            
            #line 235 "..\..\Views\Shared\_Layout.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"btn g-butt-primary g-butt-lg\"");

WriteAttribute("href", Tuple.Create(" href=\"", 11779), Tuple.Create("\"", 11797)
, Tuple.Create(Tuple.Create("", 11786), Tuple.Create<System.Object, System.Int32>(Href("~/checkout/")
, 11786), false)
);

WriteLiteral(" role=\"button\"");

WriteLiteral(">Checkout</a>\r\n");

            
            #line 239 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n                    <" +
"div");

WriteLiteral(" class=\"hdr-search g-p-t-10-md pull-right g-w-100p g-ps-r hidden-xs hidden-sm\"");

WriteLiteral(">\r\n");

            
            #line 243 "..\..\Views\Shared\_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 243 "..\..\Views\Shared\_Layout.cshtml"
                         using (Html.BeginForm("Index", "Search", FormMethod.Get))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" id=\"keyword\"");

WriteLiteral(" name=\"keyword\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control g-fs-sm g-bc-p\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" placeholder=\"Search by Brand, Printer or Cartridge Number ...\"");

WriteLiteral(" data-token=\"");

            
            #line 246 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                                            Write(Model.EncryptedDate);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 246 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                                                                  Write(searchadd);

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"token\"");

WriteLiteral(" name=\"token\"");

WriteAttribute("value", Tuple.Create(" value=\"", 12511), Tuple.Create("\"", 12539)
            
            #line 247 "..\..\Views\Shared\_Layout.cshtml"
   , Tuple.Create(Tuple.Create("", 12519), Tuple.Create<System.Object, System.Int32>(Model.EncryptedDate
            
            #line default
            #line hidden
, 12519), false)
);

WriteLiteral(" />\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" id=\"apply-search\"");

WriteLiteral(" class=\"g-butt-secondary g-butt-sm g-fs-n\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\r\n                                    </button>\r\n                           " +
"     </span>\r\n                            </div>\r\n");

            
            #line 254 "..\..\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"autocomplete-results g-ps-a g-w-100p g-bc-s g-b-1-p g-d-n g-m-t-5 g-p-10\"" +
"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </div>\r\n    </section>\r\n\r\n    <section");

WriteLiteral(" class=\"navbar navbar-inverse\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"mobile-menu\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" aria-label=\"mobile menu\"");

WriteLiteral(" class=\"navbar-toggle pull-left\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n                <a");

WriteLiteral(" href=\"/Home/\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"/Content/Images/1pxTrans.png\"");

WriteLiteral(" class=\"msp_siteLogo visible-xs-inline visible-sm-inline navbar-brand g-m-t-10\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 13817), Tuple.Create("\"", 13870)
            
            #line 271 "..\..\Views\Shared\_Layout.cshtml"
                                                               , Tuple.Create(Tuple.Create("", 13823), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SiteName")
            
            #line default
            #line hidden
, 13823), false)
);

WriteLiteral(" />\r\n                </a>\r\n                <div");

WriteLiteral(" class=\"pull-right visible-xs-inline visible-sm-inline small-screen-links g-m-r-1" +
"0\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"g-m-r-20\"");

WriteLiteral(" id=\"opensearch-mobile\"");

WriteLiteral(" aria-label=\"mobile search\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-search fa-2x\"");

WriteLiteral("></i>\r\n                    </a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 14213), Tuple.Create("\"", 14231)
, Tuple.Create(Tuple.Create("", 14220), Tuple.Create<System.Object, System.Int32>(Href("~/checkout/")
, 14220), false)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"basket-mobile fa-stack g-p-r-5\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-shopping-basket fa-stack-2x\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"basket-counter g-bc-primary g-fc-st g-fs-sm g-fw-b fa-stack-1x\"");

WriteLiteral(">");

            
            #line 280 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                 Write(bt.Quantity);

            
            #line default
            #line hidden
WriteLiteral("</i>\r\n                        </span>\r\n                    </a>\r\n                " +
"</div>\r\n            </div>\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 14624), Tuple.Create("\"", 14739)
, Tuple.Create(Tuple.Create("", 14632), Tuple.Create("navbar-collapse", 14632), true)
, Tuple.Create(Tuple.Create(" ", 14647), Tuple.Create("collapse", 14648), true)
, Tuple.Create(Tuple.Create(" ", 14656), Tuple.Create("g-ps-a", 14657), true)
            
            #line 285 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 14663), Tuple.Create<System.Object, System.Int32>(Authentication.IsAuthenticated() ? "authenticated" : "not-authenticated"
            
            #line default
            #line hidden
, 14664), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 286 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Raw(Model.Menu));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </section>\r\n\r\n    <section");

WriteLiteral(" id=\"comm-confidence\"");

WriteLiteral(" class=\"container hidden-xs hidden-sm\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 294 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 294 "..\..\Views\Shared\_Layout.cshtml"
                  
                    Dictionary<string, string> replacements = new Dictionary<string, string>();
                    replacements.Add("[Review-Score]", Html.RawFromDict(Model.FeeFoScore, "FiveStar").ToString());
                    replacements.Add("[Review-Count]", Html.RawFromDict(Model.FeeFoScore, "Count").ToString());
                
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 299 "..\..\Views\Shared\_Layout.cshtml"
            Write(Html.RawFromDict(Model.CommonData, "ConfidenceBanner", replacements));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </section>\r\n\r\n");

WriteLiteral("    ");

            
            #line 304 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 306 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 306 "..\..\Views\Shared\_Layout.cshtml"
      
        Html.RenderPartial("~/Views/Shared/Footer.cshtml");
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 310 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 310 "..\..\Views\Shared\_Layout.cshtml"
     if (!Authentication.IsFullyAuthenticated())
    {
        Html.RenderPartial("~/Views/MyAccount/SignIn.cshtml");
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"g-ps-f g-top-0 g-lf-50p text-center\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 15782), Tuple.Create("\"", 15817)
, Tuple.Create(Tuple.Create("", 15788), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 15788), false)
);

WriteLiteral(" class=\"msp_goToTop g-cur-p\"");

WriteLiteral(" style=\"padding-left: 50%; margin-left: -20px\"");

WriteLiteral(" alt=\"Go to top\"");

WriteLiteral(" />\r\n    </section>\r\n\r\n    <section");

WriteLiteral(" class=\"g-ps-f g-btm-50 hidden-xs hidden-sm\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"lhnChatButton\"");

WriteLiteral(" id=\"lhnChatButton1\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 16063), Tuple.Create("\"", 16098)
, Tuple.Create(Tuple.Create("", 16069), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 16069), false)
);

WriteLiteral(" class=\"msp_liveChatOnline g-m-b-10\"");

WriteLiteral(" id=\"liveagent_button_online1\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 16165), Tuple.Create("\"", 16247)
, Tuple.Create(Tuple.Create("", 16175), Tuple.Create("liveagent.startChat(\'", 16175), true)
            
            #line 321 "..\..\Views\Shared\_Layout.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 16196), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "LiveChatID")
            
            #line default
            #line hidden
, 16196), false)
, Tuple.Create(Tuple.Create("", 16245), Tuple.Create("\')", 16245), true)
);

WriteLiteral(" style=\"display: none; cursor: pointer;\"");

WriteLiteral(" />\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 16309), Tuple.Create("\"", 16344)
, Tuple.Create(Tuple.Create("", 16315), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/1pxTrans.png")
, 16315), false)
);

WriteLiteral(" class=\"\"");

WriteLiteral(" id=\"liveagent_button_offline1\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" />\r\n");

WriteLiteral("            ");

            
            #line 323 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Hidden("liveagent_id", Html.RawFromDict(Model.CommonData, "LiveChatID")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"ft_gcs\"");

WriteLiteral("></div>\r\n    </section>\r\n\r\n");

WriteLiteral("    ");

            
            #line 328 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrapBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 329 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jqueryvalBundle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 330 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--script src=\"https://");

            
            #line 331 "..\..\Views\Shared\_Layout.cshtml"
                        Write(Html.RawFromDict(Model.CommonData, "DomainName"));

            
            #line default
            #line hidden
WriteLiteral("data/static-files/cpy_googlereviewsbadge.js?onload=renderBadge\" async defer></scr" +
"ipt-->\r\n    <script");

WriteLiteral(" src=\"https://apis.google.com/js/platform.js?onload=renderBadge\"");

WriteLiteral(" async defer></script>\r\n    <!--script type=\"text/javascript\" src=\"https://c.la2w" +
"2.salesforceliveagent.com/content/g/js/43.0/deployment.js\"></script-->\r\n    <scr" +
"ipt");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 17156), Tuple.Create("\"", 17257)
, Tuple.Create(Tuple.Create("", 17162), Tuple.Create("https://", 17162), true)
            
            #line 334 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 17170), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "DomainName")
            
            #line default
            #line hidden
, 17170), false)
, Tuple.Create(Tuple.Create("", 17221), Tuple.Create("data/static-files/cpy_sfliveagent.js", 17221), true)
);

WriteLiteral("></script>\r\n");

            
            #line 335 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 335 "..\..\Views\Shared\_Layout.cshtml"
     if (ConfigurationManager.AppSettings["SearchApplication"] == "SLI")
    {

            
            #line default
            #line hidden
WriteLiteral("        <!--script type=\"text/javascript\" src=\"https://");

            
            #line 337 "..\..\Views\Shared\_Layout.cshtml"
                                                   Write(Html.RawFromDict(Model.CommonData, "DomainName"));

            
            #line default
            #line hidden
WriteLiteral("data/static-files/cpy_sliracsearch.js\" defer></script-->\r\n");

WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 17553), Tuple.Create("\"", 17716)
, Tuple.Create(Tuple.Create("", 17559), Tuple.Create("https://", 17559), true)
            
            #line 338 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 17567), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["SLIDomain"]
            
            #line default
            #line hidden
, 17567), false)
, Tuple.Create(Tuple.Create("", 17615), Tuple.Create("/autocomplete/rac-resources-", 17615), true)
            
            #line 338 "..\..\Views\Shared\_Layout.cshtml"
                                                , Tuple.Create(Tuple.Create("", 17643), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["WebsiteShortCode"]
            
            #line default
            #line hidden
, 17643), false)
, Tuple.Create(Tuple.Create("", 17698), Tuple.Create("/sli-rac.config.js", 17698), true)
);

WriteLiteral(" defer></script>\r\n");

            
            #line 339 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 341 "..\..\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 341 "..\..\Views\Shared\_Layout.cshtml"
          
            Html.RenderPartial("~/Views/Shared/JSTrackingAll.cshtml", Model);
            Html.RenderPartial("~/Views/Shared/JSTrackingStandard.cshtml", Model);
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </script>\r\n");

            
            #line 346 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 346 "..\..\Views\Shared\_Layout.cshtml"
      
        Html.RenderPartial("~/Views/Shared/JSGoogleAdTrackingAll.cshtml");
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 350 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("AddScript", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"SearchApplication\"");

WriteAttribute("value", Tuple.Create(" value=\"", 18170), Tuple.Create("\"", 18255)
            
            #line 351 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 18178), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["SearchApplication"] == "SLI" ? "1" : "0"
            
            #line default
            #line hidden
, 18178), false)
);

WriteLiteral(" />\r\n\r\n    <!--[if lt IE 9]> \r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            alert(\'");

            
            #line 355 "..\..\Views\Shared\_Layout.cshtml"
              Write(ConfigurationManager.AppSettings["UnsupportedBrowser"]);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        </script>\r\n    <![endif]-->\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
