#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Equipment\PopularCartridges.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Equipment\PopularCartridges.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Equipment\PopularCartridges.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Equipment\PopularCartridges.cshtml"
    using SharedUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Equipment/PopularCartridges.cshtml")]
    public partial class _Views_Equipment_PopularCartridges_cshtml : System.Web.Mvc.WebViewPage<WizardViewModel>
    {
        public _Views_Equipment_PopularCartridges_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Equipment\PopularCartridges.cshtml"
 if (Model.PopularCartridges != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <hr");

WriteLiteral(" class=\"g-m-t-60 g-m-b-20\"");

WriteLiteral("/>\r\n");

            
            #line 11 "..\..\Views\Equipment\PopularCartridges.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <h2>Popular ");

            
            #line 14 "..\..\Views\Equipment\PopularCartridges.cshtml"
                    Write(Model.Manufacturer == null ? "" : Model.Manufacturer.manufacturerName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 14 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                                                                            Write(Model.CartridgeTypeName);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"mini-product-container clearfix\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\Equipment\PopularCartridges.cshtml"
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Equipment\PopularCartridges.cshtml"
                 foreach (DataRow dr in Model.PopularCartridges.Rows)
                {
                    decimal mainPrice = 0;
                    string mainPriceVAT = "";
                    if (ConfigurationManager.AppSettings["UseVatInclusivePrices"] == "1")
                    {
                        mainPrice = Convert.ToDecimal(dr["PriceRetail"]);
                        mainPriceVAT = "inc VAT";
                    }
                    else
                    {
                        mainPrice = Decimal.Divide(Convert.ToDecimal(dr["PriceRetail"]), Model.VatMultiplier);
                        mainPriceVAT = "ex VAT";
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"mini-product-entry atb-entry\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"g-bc-s g-b-1-p g-h-140 g-w-140 text-center\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1364), Tuple.Create("\"", 1403)
            
            #line 34 "..\..\Views\Equipment\PopularCartridges.cshtml"
, Tuple.Create(Tuple.Create("", 1371), Tuple.Create<System.Object, System.Int32>(dr["ProductURL"].ToSafeString()
            
            #line default
            #line hidden
, 1371), false)
);

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/Content/Images/1pxTrans.png\"");

WriteLiteral(" class=\"lazy\"");

WriteLiteral(" data-original=\"");

            
            #line 35 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                                                                               Write(dr["ImageURL"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 1538), Tuple.Create("\"", 1577)
            
            #line 35 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                                         , Tuple.Create(Tuple.Create("", 1544), Tuple.Create<System.Object, System.Int32>(dr["Description"].ToSafeString()
            
            #line default
            #line hidden
, 1544), false)
);

WriteAttribute("onerror", Tuple.Create(" onerror=\"", 1578), Tuple.Create("\"", 1661)
, Tuple.Create(Tuple.Create("", 1588), Tuple.Create("this.src", 1588), true)
, Tuple.Create(Tuple.Create(" ", 1596), Tuple.Create("=", 1597), true)
, Tuple.Create(Tuple.Create(" ", 1598), Tuple.Create("\'", 1599), true)
            
            #line 35 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                                                                                                 , Tuple.Create(Tuple.Create("", 1600), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1600), false)
, Tuple.Create(Tuple.Create("", 1640), Tuple.Create("/Images/noimage.jpg\';", 1640), true)
);

WriteLiteral(" />\r\n                                <noscript>\r\n                                " +
"    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1751), Tuple.Create("\"", 1783)
            
            #line 37 "..\..\Views\Equipment\PopularCartridges.cshtml"
, Tuple.Create(Tuple.Create("", 1757), Tuple.Create<System.Object, System.Int32>(dr["ImageURL"].ToString()
            
            #line default
            #line hidden
, 1757), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 1784), Tuple.Create("\"", 1823)
            
            #line 37 "..\..\Views\Equipment\PopularCartridges.cshtml"
, Tuple.Create(Tuple.Create("", 1790), Tuple.Create<System.Object, System.Int32>(dr["Description"].ToSafeString()
            
            #line default
            #line hidden
, 1790), false)
);

WriteAttribute("onerror", Tuple.Create(" onerror=\"", 1824), Tuple.Create("\"", 1905)
, Tuple.Create(Tuple.Create("", 1834), Tuple.Create("this.src=\'", 1834), true)
            
            #line 37 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                                     , Tuple.Create(Tuple.Create("", 1844), Tuple.Create<System.Object, System.Int32>(ConfigurationManager.AppSettings["CDN"]
            
            #line default
            #line hidden
, 1844), false)
, Tuple.Create(Tuple.Create("", 1884), Tuple.Create("/Images/noimage.jpg\';", 1884), true)
);

WriteLiteral(">\r\n                                </noscript>\r\n                            </a>\r" +
"\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"g-m-t-10 g-h-40 g-of-h\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" class=\"primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2128), Tuple.Create("\"", 2167)
            
            #line 42 "..\..\Views\Equipment\PopularCartridges.cshtml"
, Tuple.Create(Tuple.Create("", 2135), Tuple.Create<System.Object, System.Int32>(dr["ProductURL"].ToSafeString()
            
            #line default
            #line hidden
, 2135), false)
);

WriteLiteral(">\r\n                                <strong>");

            
            #line 43 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                   Write(dr["Description"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                            </a>\r\n                        </div>\r\n    " +
"                    <div");

WriteLiteral(" class=\"g-m-t-10 g-fs-lg g-h-35 g-of-h\"");

WriteLiteral(">\r\n                            &pound;");

            
            #line 47 "..\..\Views\Equipment\PopularCartridges.cshtml"
                              Write(mainPrice.ToString("#,###,##0.00"));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"g-fc-tt g-fs-sm\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                                                                                Write(mainPriceVAT);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"g-fc-st text-center g-m-t-10 g-fs-sm g-lh-20\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 50 "..\..\Views\Equipment\PopularCartridges.cshtml"
                       Write(Html.ProductAvailability(int.Parse(dr["Availability"].ToString()), Convert.ToBoolean(Model.CommonData["DeliveryDateIsOverridden"].ToString()), true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"pull-right g-m-t-10 g-w-100p\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"atb-add g-butt-primary g-butt-100p\"");

WriteLiteral("\r\n                                    data-price=\"");

            
            #line 54 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                           Write(mainPrice.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                    data-productid=\"");

            
            #line 55 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                               Write(dr["ProductReference"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                    data-partno=\"");

            
            #line 56 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                            Write(dr["PartNo"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                    data-imageurl=\"");

            
            #line 57 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                              Write(dr["ImageURL"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                                    data-desc=\"");

            
            #line 58 "..\..\Views\Equipment\PopularCartridges.cshtml"
                                          Write(dr["Description"].ToSafeString());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                Add to Basket\r\n                            </b" +
"utton>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 63 "..\..\Views\Equipment\PopularCartridges.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 67 "..\..\Views\Equipment\PopularCartridges.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
