//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netGiant.Intranet.DataLayer.CustomerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterimOrder
    {
        public int InterimOrderId { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsOrdered { get; set; }
        public string Json { get; set; }
        public int WebsiteFk { get; set; }
    }
}
