#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Product\ProductAltFilters.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Product\ProductAltFilters.cshtml"
    using BusinessLogic.ViewModels;
    
    #line default
    #line hidden
    using CommonUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Product/ProductAltFilters.cshtml")]
    public partial class _Views_Product_ProductAltFilters_cshtml : System.Web.Mvc.WebViewPage<SearchViewModel>
    {
        public _Views_Product_ProductAltFilters_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Product\ProductAltFilters.cshtml"
   
    List<SearchList> products = Model.SearchList;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"g-fs-lg g-p-b-20 pull-left\"");

WriteLiteral(">Filter Products <span");

WriteLiteral(" class=\"g-fc-s\"");

WriteLiteral(">(<span");

WriteLiteral(" id=\"pl-product-count\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Product\ProductAltFilters.cshtml"
                                                                                                     Write(products.Count);

            
            #line default
            #line hidden
WriteLiteral("</span>)</span></div>\r\n<div");

WriteLiteral(" class=\"pull-right fltr-filters\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\Product\ProductAltFilters.cshtml"
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Product\ProductAltFilters.cshtml"
         if (products.Any(x => x.Product.BrandFlag == BrandFlag.Compatible))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"pull-left g-p-r-10 g-d-ib g-p-b-10\"");

WriteLiteral("><button");

WriteLiteral(" name=\"fltr_Y-*-*-*-*\"");

WriteLiteral(" class=\"g-butt-lg g-butt-secondary-inv-alt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-gbp g-p-r-10\"");

WriteLiteral("></i>Best Value</button></div>\r\n");

            
            #line 16 "..\..\Views\Product\ProductAltFilters.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 17 "..\..\Views\Product\ProductAltFilters.cshtml"
         if (products.Any(x => x.Product.PrimarySortSeq == ProductFlag.Assembly))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"pull-left g-p-r-10 g-d-ib g-p-b-10\"");

WriteLiteral("><button");

WriteLiteral(" name=\"fltr_*-Y-*-*-*\"");

WriteLiteral(" class=\"g-butt-lg g-butt-secondary-inv-alt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-clone g-p-r-10\"");

WriteLiteral("></i>Multi-Packs</button></div>\r\n");

            
            #line 20 "..\..\Views\Product\ProductAltFilters.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 21 "..\..\Views\Product\ProductAltFilters.cshtml"
         if (products.Any(x => x.Product.AttDesc8 == "Black"))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"pull-left g-p-r-10 g-d-ib g-p-b-10\"");

WriteLiteral("><button");

WriteLiteral(" name=\"fltr_*-*-Y-*-*\"");

WriteLiteral(" class=\"g-butt-lg g-butt-secondary-inv-alt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-stop g-p-r-10\"");

WriteLiteral("></i>Black</button></div>\r\n");

            
            #line 24 "..\..\Views\Product\ProductAltFilters.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 25 "..\..\Views\Product\ProductAltFilters.cshtml"
         if (products.Any(x => x.Product.AttDesc8 != "Black" && x.Product.PrimarySortSeq != ProductFlag.Ancillary))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"pull-left g-p-r-10 g-d-ib g-p-b-10\"");

WriteLiteral("><button");

WriteLiteral(" name=\"fltr_*-*-*-Y-*\"");

WriteLiteral(" class=\"g-butt-lg g-butt-secondary-inv-alt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa g-m-r-10 cc-33\"");

WriteLiteral(" style=\"height:12px;width:12px;\"");

WriteLiteral("></i>Colours</button></div>\r\n");

            
            #line 28 "..\..\Views\Product\ProductAltFilters.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 29 "..\..\Views\Product\ProductAltFilters.cshtml"
         if (products.Any(x => x.Product.PrimarySortSeq == ProductFlag.Ancillary))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"pull-left g-p-r-10 g-d-ib g-p-b-10\"");

WriteLiteral("><button");

WriteLiteral(" name=\"fltr_*-*-*-*-Y\"");

WriteLiteral(" class=\"g-butt-lg g-butt-secondary-inv-alt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-wrench g-p-r-10\"");

WriteLiteral("></i>Maintenance</button></div>\r\n");

            
            #line 32 "..\..\Views\Product\ProductAltFilters.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"pull-left g-d-ib g-p-b-10\"");

WriteLiteral("><button");

WriteLiteral(" name=\"fltr_*-*-*-*-*\"");

WriteLiteral(" class=\"g-butt-lg g-butt-secondary-inv-alt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-minus g-p-r-10\"");

WriteLiteral("></i>Clear all</button></div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

        }
    }
}
#pragma warning restore 1591
