#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\MyAccount\BillingAddress.cshtml"
    using BusinessLogic;
    
    #line default
    #line hidden
    using CommonUI;
    
    #line 2 "..\..\Views\MyAccount\BillingAddress.cshtml"
    using CommonUI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MyAccount/BillingAddress.cshtml")]
    public partial class _Views_MyAccount_BillingAddress_cshtml : System.Web.Mvc.WebViewPage<MyAccountDetails>
    {
        public _Views_MyAccount_BillingAddress_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\MyAccount\BillingAddress.cshtml"
 using (Ajax.BeginForm("UpdateAddress", 
    "MyAccount",
    null,
    new AjaxOptions { HttpMethod = "POST", OnBegin = "return verifyPassword('password-change')", OnComplete = "myAccountUpdateComplete", OnFailure = "logAjaxFormError" }, 
    new { id = "updateAddress" }))
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\MyAccount\BillingAddress.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\MyAccount\BillingAddress.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\MyAccount\BillingAddress.cshtml"
Write(Html.HiddenFor(x => x.Record));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\MyAccount\BillingAddress.cshtml"
                                  

    bool isDisabled = Convert.ToBoolean(Session["U_IsAccountCustomer"]);


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"update-address\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\MyAccount\BillingAddress.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\MyAccount\BillingAddress.cshtml"
         if (isDisabled)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"g-bc-note g-b-1-p g-p-10 g-m-t-20 clearfix\"");

WriteLiteral(">\r\n                <span>\r\n                    We have detected you are registere" +
"d with a credit account, please contact us to change your billing address. Call " +
"");

            
            #line 23 "..\..\Views\MyAccount\BillingAddress.cshtml"
                                                                                                                                 Write(Html.RawFromDict(Model.CommonData, "TelephoneNumber"));

            
            #line default
            #line hidden
WriteLiteral(" or email\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 892), Tuple.Create("\"", 957)
, Tuple.Create(Tuple.Create("", 899), Tuple.Create("mailto:", 899), true)
            
            #line 24 "..\..\Views\MyAccount\BillingAddress.cshtml"
, Tuple.Create(Tuple.Create("", 906), Tuple.Create<System.Object, System.Int32>(Html.RawFromDict(Model.CommonData, "SupportEmail")
            
            #line default
            #line hidden
, 906), false)
);

WriteLiteral(">");

            
            #line 24 "..\..\Views\MyAccount\BillingAddress.cshtml"
                                                                                    Write(Html.RawFromDict(Model.CommonData, "SupportEmail"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </span>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"g-bc-s g-b-1-p g-m-t-20 g-p-10\"");

WriteLiteral(">\r\n                <div>Your current billing address is:</div>\r\n");

WriteLiteral("                ");

            
            #line 29 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.DisplayAddressDetails(Model.CustomerAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 31 "..\..\Views\MyAccount\BillingAddress.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"g-m-t-20 clearfix\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">COMPANY NAME</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.EditorFor(x => x.CustomerAddress.Line1, new { htmlAttributes = Utilities.CondAddToDict(new RouteValueDictionary(new { placeholder = "Company Name", @class = "g-b-1-p" }), isDisabled, "disabled", "disabled")}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">ADDRESS LINE 1*</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.EditorFor(x => x.CustomerAddress.Line2, new { htmlAttributes = Utilities.CondAddToDict(new RouteValueDictionary( new { placeholder = "Address Line1", @class = "g-b-1-p" }), isDisabled, "disabled", "disabled") }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">ADDRESS LINE 2</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 58 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.EditorFor(x => x.CustomerAddress.Line3, new { htmlAttributes = Utilities.CondAddToDict(new RouteValueDictionary(new { placeholder = "Address Line2", @class = "g-b-1-p" }), isDisabled, "disabled", "disabled") }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">TOWN OR CITY*</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.EditorFor(x => x.CustomerAddress.Line4, new { htmlAttributes = Utilities.CondAddToDict(new RouteValueDictionary(new { placeholder = "Town or City", @class = "g-b-1-p" }), isDisabled, "disabled", "disabled") }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">COUNTY</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 78 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.EditorFor(x => x.CustomerAddress.Line5, new { htmlAttributes = Utilities.CondAddToDict(new RouteValueDictionary(new { placeholder = "County", @class = "g-b-1-p" }), isDisabled, "disabled", "disabled") }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">POSTCODE*</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 88 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.EditorFor(x => x.CustomerAddress.PostCode, new { htmlAttributes = Utilities.CondAddToDict(new RouteValueDictionary(new { placeholder = "Postcode", @class = "g-b-1-p" }), isDisabled, "disabled", "disabled") }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md\"");

WriteLiteral(">CURRENT PASSWORD*</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-m-t-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"g-inp-md clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 98 "..\..\Views\MyAccount\BillingAddress.cshtml"
           Write(Html.PasswordFor(x => x.OldPassword, new { placeholder = "Current Password", @class = "g-b-1-p" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix g-fc-nm g-m-t-10 g-i g-h-20 g-of-h\"");

WriteLiteral("></div>\r\n\r\n");

            
            #line 103 "..\..\Views\MyAccount\BillingAddress.cshtml"
        
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\MyAccount\BillingAddress.cshtml"
         if (!isDisabled)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"g-butt-primary g-butt-xl g-m-t-20\"");

WriteLiteral(">Save Changes</button>\r\n            </div>\r\n");

            
            #line 108 "..\..\Views\MyAccount\BillingAddress.cshtml"
            
            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\MyAccount\BillingAddress.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\MyAccount\BillingAddress.cshtml"
                                     


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"g-d-ib\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"error-message g-d-n g-m-t-20-i\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-exclamation-triangle g-fs-20 g-p-r-10\"");

WriteLiteral("></i>\r\n                    <p");

WriteLiteral(" class=\"g-m-0 g-d-i g-p-r-10\"");

WriteLiteral("></p>\r\n                </div>\r\n            </div>\r\n");

            
            #line 116 "..\..\Views\MyAccount\BillingAddress.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"password-success\"");

WriteLiteral(" class=\"g-m-t-20 g-fc-pm g-d-n\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-check g-p-r-5\"");

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"\"");

WriteLiteral(">Changes successfully saved!</span>\r\n            </div>\r\n");

            
            #line 121 "..\..\Views\MyAccount\BillingAddress.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 123 "..\..\Views\MyAccount\BillingAddress.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var form = $(\"#updateAddress\");\r\n    form.removeData(\'validator\');\r\n    fo" +
"rm.removeData(\'unobtrusiveValidation\');\r\n    $.validator.unobtrusive.parse(form)" +
";\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
